DEFRA/water-abstraction-service

migrations/20180615124134-notification-expiry.js, migrations/20180615133905-notification-resume.js, migrations/20180615140637-notification-stop.js, migrations/20180615141310-notification-warning.js, migrations/sqls/20180615124134-notification-expiry-down.sql, migrations/sqls/20180615124134-notification-expiry-up.sql, migrations/sqls/20180615133905-notification-resume-down.sql, migrations/sqls/20180615133905-notification-resume-up.sql, migrations/sqls/20180615140637-notification-stop-down.sql, migrations/sqls/20180615140637-notification-stop-up.sql, migrations/sqls/20180615141310-notification-warning-down.sql, migrations/sqls/20180615141310-notification-warning-up.sql
Further changes to the notification templates.
- Moves the default content out into separate `letter` and `email` content
properties to deal with different treatment of titles.
- Updates the titles and render the title in the emails.
- Fixes a plural in the expiry notification.
- Changes any instances of 'The Water Resources Act' to 'Water Resources
Act'.
=> WATER-1151 and WATER-1153

migrations/20180618102503-notification-expiry-add-page-title.js, migrations/20180618102515-notification-resume-add-page-title.js, migrations/20180618102528-notification-stop-add-page-title.js, migrations/20180618102544-notification-warning-add-page-title.js, migrations/sqls/20180618102503-notification-expiry-add-page-title-down.sql, migrations/sqls/20180618102503-notification-expiry-add-page-title-up.sql, migrations/sqls/20180618102515-notification-resume-add-page-title-down.sql, migrations/sqls/20180618102515-notification-resume-add-page-title-up.sql, migrations/sqls/20180618102528-notification-stop-add-page-title-down.sql, migrations/sqls/20180618102528-notification-stop-add-page-title-up.sql, migrations/sqls/20180618102544-notification-warning-add-page-title-down.sql, migrations/sqls/20180618102544-notification-warning-add-page-title-up.sql
Fixes an issue where the title was being used for the email titles
instead of the subject.
The title field drives the title in the UI, rather than the email title,
so have switched to using the subject, which is the same value.
=> WATER-1151: Email titles.

src/modules/import/transform-crm.js, test/modules/import/lib/transform-crm.js
Changes the crm transform to set the `IsCurrent` property in the saved
metadata if the licence effective date is in the future, or if the
licence has expired.
=> Feat: Future licences are not deemed to be current

src/modules/returns/lib/model-returns-mapper.js, src/modules/returns/routes.js, test/modules/returns/lib/model-returns-mapper.js
Changes the return model to have a meters property that is mapped into
the metadata of the version.
=> Feat: Handle meter readings in return model

.labrc.js, .travis.yml, package.json, src/modules/import/lib/transform-returns-helpers.js, src/modules/import/transform-returns.js, src/modules/returns/lib/model-returns-mapper.js, test/modules/import/lib/transform-returns-helpers.js, test/modules/returns/lib/model-returns-mapper.js
Adds a `due_date` to the imported returns.
Also separates out the test tasks for local dev and Travis execution.
=> Feat: Improved due returns messaging

src/modules/returns/routes.js
The dueDate has been recently added to the returns model. Therefore the
validation on the endpoint needs to include this otherwise the request
is rejected.
=> Fix: Adds the dueDate to the expected payload

src/modules/import/lib/transform-returns-helpers.js, test/modules/import/lib/transform-returns-helpers.js
WATER-1392
Fixes an issue where format purposes could have a string value of 'null'
which was then being shown in the UI.
This change does not import the alias into the metadata if the value is
falsey, or once trimmed and lower cased, is equal to 'null'.
=> Fix: Handle null purposes aliases

src/modules/returns/lib/api-connector.js
Throws the original error returned from the api client to retain the
name and message
Adds start and finish markers to the `persistReturnData` function to
potentially help identity which return is causing a lot of logging
errors in QA where performance tests are being run.
=> Feat: Api connector logging improvement

import.js, index.js, src/lib/nald-dates.js, src/modules/import/lib/transform-returns-helpers.js, src/modules/pdf-notifications/view-helpers.js, src/modules/returns/lib/model-returns-mapper.js, test/lib/nald-dates.js, test/modules/import/lib/transform-returns-helpers.js, test/modules/pdf-notifications/view-helpers.js, test/modules/returns/lib/model-returns-mapper.js
WATER-1632
Changes week calculations to us weeks that start on Sundays.
Sets the global moment locale to en-gb, but then adds a nald-dates
module for calculating the weeks, where a local locale of `en` is used
which treats weeks as running Sun - Sat.
Updates any existing code that used `startOf` or `endOf` and routes
through nald-dates.
=> Fix: Use Sun - Sat weeks for NALD

.codeclimate.json, .env.example, .labrc.js, .travis.yml, README.MD, config.js, index.js, src/lib/connectors/permit.js, src/lib/logger/index.js, src/lib/slack.js, src/modules/notify/connectors/notify.js, src/modules/returns-notifications/lib/message-helpers.js, src/modules/returns-notifications/lib/send.js, test/modules/notify/connectors/notify.js, test/modules/returns-notifications/lib/message-helpers.js
- Always use `NODE_ENV` and remove `environment` and `NODEENV`
- Use `production` rather than `prod` for the live environment variable.
- Moves `licenseTypeId` and `licenceRegimeId` to config
- Uppercase env variable keys
- Removes unused vars from .env.example file.
- Removes errbit from travis (not used).
=> Feat: Consolidate env variables

src/modules/import/extract.js
WATER-1667
Removes the logic that would try the old password if the new password
failed. This is the second part of a story that had to span two release
cycles.
=> Feat: Remove old NALD password from zip extract

src/lib/licence-transformer/csv-transformer.js, src/lib/licence-transformer/nald-helpers.js, src/modules/licences/lib/extractConditions.js, src/modules/licences/lib/extractPoints.js, test/lib/licence-transformer/nald-helpers.js, test/modules/licences/lib/extractConditions.js, test/modules/licences/lib/extractPoints.js
Create a truly unique id for points and conditions when found via the
`/documents/{documentId}/licences/points` URL.
This is to overcome the legacy problem of non unique ids because each
region had its own datastore.
Also adds a reverse function to parse the unique id if required to break
down into type, region code and id.
=> Uses a unique id for points and conditions data

src/modules/import/lib/nald-returns-queries.js, src/modules/import/lib/transform-returns-helpers.js, src/modules/import/transform-returns.js, test/modules/import/lib/transform-returns-helpers.js
WATER-1819
Update the `getFormatEndDate` function to use any dates on the licence
that suggested the licence has lapsed, expired or been revoked
Changes the return entry for the now revised return from:
```
{ 
return_id: 'test-return-id',
regime: 'water',
licence_type: 'abstraction',
licence_ref: 'test-licence-id,
start_date: '2017-11-01',
end_date: '2018-10-31',
due_date: '2018-11-28',
returns_frequency: 'month',
status: 'due',
metadata: 'test-metadata,
received_date: null,
return_requirement: 'format-id' 
}
```
to
```
{ 
return_id: 'test-return-id',
regime: 'water',
licence_type: 'abstraction',
licence_ref: 'test-licence-id,
start_date: '2017-11-01',
end_date: '2018-03-31',
due_date: '2018-04-28',
returns_frequency: 'month',
status: 'due',
source: 'NALD',
metadata: 'test-metadata, …
```
=> Fix: Updates format cycle end date calculation

src/modules/users/controller.js, test/modules/users/controller.js
WATER-1833
Updates the user status endpoint so that it handles internal users.
These users won't have companies so don't request them.
Also fixes an issue with the user.isLocked calculation handling the data
being a string and not a number.
=> Feat: Handles internal users in user status endpoint

src/modules/communications/controller.js, src/modules/licences/controller.js, test/modules/communications/controller.js, test/modules/licences/controller.js
WATER-1891
- Adds a flag to the message responses to indicate if the communication
was a PDF.
- Adds the recipient address data to the notification object when viewing
a communication item
=> Feat: Adds additional data to communication responses

src/modules/licences/lib/queries.js
WATER-1892
Only returns communications that are delivered by, or received at notify
=> Fix: Filter communications by successful send

.codeclimate.json, package-lock.json, package.json, src/controllers/taskRunner.js, src/lib/slack.js, src/modules/ar-analysis/controller.js, src/modules/ar-analysis/lib/update-licence-row.js, src/modules/import/index.js, src/modules/import/load.js, src/modules/import/transform-crm.js, src/modules/import/transform-permit.js, src/modules/licences/controller.js, src/modules/notify/index.js, src/modules/returns-invitation/index.js, src/modules/returns/controller.js, src/modules/returns/lib/api-connector.js, src/modules/returns/lib/jobs/start-xml-upload.js, src/modules/returns/lib/jobs/xml-to-json.js, src/modules/returns/lib/route-helpers.js, test/modules/ar-analysis/controller.js, test/modules/licences/controller.js, test/modules/returns/controller.js, test/modules/returns/lib/jobs/start-xml-upload.js, test/modules/returns/lib/jobs/xml-to-json.js, test/modules/returns/lib/route-helpers.js
This automatically adds the context->controller value to the error so it
is no longer required to add this before calling `logger.error`.
=> Implements the latest version of the logger

src/lib/connectors/permit.js, src/modules/returns-notifications/controller.js, src/modules/returns-notifications/lib/request-parser.js, test/lib/connectors/permit.js, test/modules/returns-notifications/controller.js, test/modules/returns-notifications/lib/request-parser.js
WATER-1950
Changes the paper form preview endpoint to include any dates that a
licence has ended. (Expired | Revoked | Lapsed)
Updates the default role priority for returns recipients so that a
returns contact is the first point of contact, then the licence holder.
=> Feat: Update paper form issuing

src/modules/internal-search/lib/search-documents.js, src/modules/licences/controller.js, src/modules/licences/routes.js, test/modules/internal-search/lib/search-documents.js, test/modules/licences/controller.js
WATER-1976
Updates the internal search to include expired licences as well when
search for a licence internally.
Allow communications to be acquired for expired licences
Adds partial document details to the licence response
Adds earliest expiry date and reason to the licence response
=> Feat: Include expired licences in internal search

src/lib/returns.js, src/modules/import/lib/transform-returns-helpers.js, src/modules/returns/lib/csv-schema-validation.js, src/modules/returns/schema.js, test/lib/returns.js, test/modules/returns/lib/csv-schema-validation.js
WATER-2070
Adds CSV validator which validates that the CSV is in the expected
shape.
Moves return id parser and regex to `src/lib/returns`
=> Feat: Adds returns CSV validator

test/modules/returns/lib/xml-adapter/mapper.js, test/modules/returns/lib/xml-files-for-tests/estimated-monthly-return.xml, test/modules/returns/lib/xml-files-for-tests/nil-return.xml, test/modules/returns/lib/xml-files-for-tests/single-yearly-return.xml, test/modules/returns/lib/xml-to-json-integration.js, test/modules/returns/schema.js
WATER-2117
Adds an integration test that takes example xml returns data, transforms
it to JSON, then validates it using the return model schema to ensure
that these components work together and to provide an early warning if
any future changes introduced a breaking change.
=> Feat: Adds XML upload tests

src/modules/import/lib/void-invalid-cycles.js, test/modules/import/lib/void-invalid-cycles.js
WATER-2123
Chunks up requests to returns.findAll when dealing with large numbers of
return ids that are to be voided.
=> Fix: Prevent large void return requests

src/modules/import/load.js
WATER-2130
Updates the importing of licences to abort an import if the licence has
no versions.
=> Fix: Do not import licences without a version

src/modules/batch-notifications/lib/jobs/check-status.js, src/modules/batch-notifications/lib/status-check-helpers.js, test/modules/batch-notifications/lib/status-check-helpers.js
WATER-2158
Updates the `getNextCheckTime` function in status-check-helpers so that
if the `send_after` value is null, the current time is used to determine
the next check status.
=> Fix: Update next check dates for notify status checks

src/modules/returns/lib/csv-adapter/mapper.js, test/modules/returns/lib/csv-adapter/mapper.js
WATER-2153
Changes the method of determining the return frequency when uploading
via CSV format using either the number of data rows (12 for a year, > 12
for daily) or the content of the date field (week ending ....)
Then with a good idea of the frequency, and list of accepted date
formats can be used to attempt to mitigate against client programs auto
formatting dates before export to CSV.
=> Fix: Updates means of determining return frequency

src/modules/batch-notifications/lib/status-check-helpers.js, test/modules/batch-notifications/lib/status-check-helpers.js
Fixes an issue when the email status check could too quickly create a
number of minutes to be added to now, that exceeded the max JS date.
=> Fix: Prevent email status check time getting to large

src/modules/returns/lib/csv-adapter/validator.js, test/modules/returns/lib/csv-adapter/validator.js
WATER-2153
Changes the regex in the CSV schema validation stage to be more tolerant
of date formats to try and handle the unexpected date formats found when
a spreadsheet client exports to CSV.
=> Fix: Loosens csv schema validation

src/modules/users/controller.js, test/modules/users/controller.js
WATER-2184
Add 'isDisabled' flag and 'dateDisabled' to user status based on 'enabled' db field.
=> Add disabled account user data when getting user status.

ecosystem.config.json, src/lib/licence-transformer/csv-transformer.js, src/lib/licence-transformer/nald-functional.js, src/lib/licence-transformer/nald-transformer.js, src/lib/models/factory/contact-list.js, src/modules/import/transform-crm.js, src/modules/internal-search/lib/search-documents.js, test/lib/licence-transformer/nald-functional.js, test/modules/import/lib/transform-crm.js, test/modules/internal-search/lib/search-documents.js
WATER-2212
Prevents an attempts to access the parties of the current version if the
licence has no current version.
=> Fix: Only create contacts for non null version

src/modules/import/transform-crm.js, test/modules/import/lib/transform-crm.js
bugfix/WATER-2399
-- name for contacts from licence roles fixed
-- unit tests now cover scenarios for licences with and without a role
=> BUG FIX - name for returns contact

src/modules/returns-notifications/index.js
Fixes an issue where the message queue subscription handler does not
contain the `done` callback and instead it should be accessed of the
`job` argument.
=> Fix: Returns notifications job completion

src/lib/models/invoice-licence.js, src/lib/models/role.js, src/lib/models/validators.js, test/lib/models/invoice-licence.js, test/lib/models/role.js
WATER-2450
Allows multiple licence holders to be stored against one invoice. Currently, only licenceHolder role is valid.
=> Create Role model. Add roles to InvoiceLicence model.

migrations/20200108170348-add-undertaker-and-regions-to-licences.js, migrations/sqls/20200108170348-add-undertaker-and-regions-to-licences-down.sql, migrations/sqls/20200108170348-add-undertaker-and-regions-to-licences-up.sql
WATER-2463
Updates the 'water.licences' table
- Adds the regions field to maintain the historic and charge regions required for charging
- Adds a flag to determine if the licence is owned by a water undertaker
- Adds a unique constraint so that a postgres upsert can be run by the import module when persisting a licence.
=> Feat: Capture region data for licences

src/lib/connectors/repository/BillingInvoiceRepository.js
Remove old batch invoice table from query to retrieve all the invoices
and transactions for a batch.
=> Fix: Removes old table name from query

migrations/20200110135211-update-batch-status-enum.js, migrations/sqls/20200110135211-update-batch-status-enum-down.sql, migrations/sqls/20200110135211-update-batch-status-enum-up.sql, src/lib/connectors/crm-v2/invoice-accounts.js, src/lib/connectors/repository/BillingTransactionRepository.js, src/modules/billing/controller.js, src/modules/billing/routes.js, src/modules/billing/services/invoice-accounts-service.js, test/lib/connectors/crm-v2/invoice-accounts.js, test/lib/connectors/repository/BillingTransactionRepository.js, test/modules/billing/controller.js, test/modules/billing/routes.js, test/modules/billing/services/invoice-accounts-service.js
WATER-2411
- Adds new DELETE route for /batches/{batchId}/account/{accountId}
Checks if the batch exists and if it has invoices for the account, then
deletes the transactions from `water.billing_transactions`.
Requires more work in the future to delete the transactions from the
charge module.
=> Feat: Remove customer from a bill run

migrations/20200116133950-notifications-index.js, migrations/sqls/20200116133950-notifications-index-down.sql, migrations/sqls/20200116133950-notifications-index-up.sql, src/controllers/taskRunner.js, src/controllers/tasks/refreshS3data.js, src/modules/import/extract.js, src/modules/import/index.js, src/routes/water.js
WATER-2472
- Fixes an issue in the scheduler where the job was always being
scheduled to run again in one minute.
- Due to the nature of the jobs maintained by the scheduler, reduces
the polling time down to once every 1 min
- Adds some required indexes for the query speed
=> Fix: Correct scheduling of next job

config.js, src/modules/import/repositories.js
Redistributes the available database connections between the services to try and prevent waiting in the import and water service processes.
=> Chore: Update connection pool distribution

package-lock.json, src/lib/connectors/repos/billing-batches.js, src/modules/billing/controller.js, src/modules/billing/services/batch-service.js, test/lib/connectors/repos/billing-batches.js, test/modules/billing/controller.js, test/modules/billing/services/batch-service.js
WATER-2510
In order to provide more detail in the front end, this change updates
the endpoint responsible for creating a new batch so that if there is
already a batch that is processing for the region, a 409 is returned
including the batch that is already processing.
=> Feat: Updates batch creation for better 409 response

src/lib/connectors/bookshelf/BillingBatchChargeVersionYear.js, src/lib/connectors/bookshelf/index.js, src/lib/connectors/repos/billing-batch-charge-version-years.js, src/lib/connectors/repos/index.js, src/lib/connectors/repos/queries/billing-transactions.js, src/lib/connectors/repository/BillingBatchChargeVersionYearsRepository.js, src/lib/models/charge-version-year.js, src/modules/billing/jobs/process-charge-version.js, src/modules/billing/services/charge-version-year.js, test/lib/connectors/repos/billing-batch-charge-version-years.js, test/lib/connectors/repository/BillingBatchChargeVersionYearsRepository.js, test/lib/models/charge-element-year.js, test/modules/billing/jobs/process-charge-version.js, test/modules/billing/services/charge-version-year.js
Some recent work has renamed the batch statuses, and also the enum type in the database.
This type was also used for the charge version year status, however this code had not been updated.
This PR:
- Begins work on a Bookshelf repo for charge version years
- Creates a service for it
- Updates the job to use the new service
=> Fixes issue with status of water.billing_batch_charge_version_years

src/lib/connectors/charge-module/ChargeModuleRequest.js, test/lib/connectors/charge-module/ChargeModuleRequest.js
If a proxy is set in config.proxy, use it when making requests to the Charge Module
=> Use config.proxy for requests to charge module

src/modules/returns/lib/xml-adapter/mapper.js, test/modules/returns/lib/xml-adapter/mapper.js
WATER-2443
If the serial number element is missing then default to a dash.
=> Fix: Allow missing serial number in returns xml

src/modules/billing/controller.js, src/modules/billing/routes.js, src/modules/billing/services/batch-service.js, test/modules/billing/controller.js, test/modules/billing/routes.js, test/modules/billing/services/batch-service.js
WATER-2568
Allows batches to be cancelled when in the ready, review and error
states.
Updates the delete batch service to expect the latest batch model shape.
=> Fix: Loosen delete batch status validation

migrations/20200306164300-empty-batch-status.js, migrations/sqls/20200306164300-empty-batch-status-down.sql, migrations/sqls/20200306164300-empty-batch-status-up.sql, src/lib/connectors/repos/queries/billing-transactions.js, src/lib/models/batch.js, src/modules/billing/controller.js, src/modules/billing/jobs/populate-batch-charge-versions-complete.js, src/modules/billing/jobs/prepare-transactions-complete.js, src/modules/billing/services/batch-service.js, src/modules/billing/services/job-service.js, test/lib/models/batch.js, test/modules/billing/controller.js, test/modules/billing/jobs/populate-batch-charge-versions-complete.js, test/modules/billing/jobs/prepare-transactions-complete.js, test/modules/billing/services/batch-service.js, test/modules/billing/services/job-service.js
WATER-2561
- Database migrations for new empty batch status
- Updates the batch status enum
- Updates the job service to update a batch to empty status
- Updates the complete handler for charge versions to mark an empty batch
- Updates the prepare transactions complete handler to mark a batch as empty if there are no transactions
- Sets a batch to empty if no remaining transactions when deleting an account
=> Feat: Adds new empty status for a batch

src/modules/billing/services/invoice-service.js
Fixes an issue on the bill detail page where the totals were for the whole billing batch, not an individual customer.
This was found to be because the customer invoice account number was not being passed to the Charge Module bill run API correctly
=> Fixes issue where invoice totals were for whole batch

src/modules/billing/controller.js, src/modules/billing/jobs/create-charge-complete.js, src/modules/billing/jobs/refresh-totals.js, test/modules/billing/controller.js, test/modules/billing/jobs/create-charge-complete.js, test/modules/billing/jobs/refresh-totals.js
When a customer is removed from a bill run, a job is published to refresh the net total / bill counts.
=> Refresh net total / bill counts when customer is deleted from bill run

src/lib/connectors/repos/billing-invoice-licences.js, src/lib/connectors/repos/queries/billing-invoice-licences.js, src/modules/billing/controller.js, src/modules/billing/routes.js, src/modules/billing/services/invoice-licences-service.js, test/lib/connectors/repos/billing-invoice-licences.js, test/modules/billing/controller.js, test/modules/billing/routes.js, test/modules/billing/services/invoice-licences-service.js
WATER-2519
Adds a resource that get the licences in a batch including an aggregate
of the two part tariff error codes
=> Feat: Adds batch licences api

src/modules/billing/jobs/create-charge-complete.js, src/modules/billing/jobs/create-charge.js, src/modules/billing/jobs/lib/batch-job.js, src/modules/billing/jobs/process-charge-version-complete.js, src/modules/billing/jobs/process-charge-version.js, test/modules/billing/jobs/create-charge-complete.js, test/modules/billing/jobs/lib/batch-job.js, test/modules/billing/jobs/process-charge-version-complete.js
Because the onComplete handlers in the billing run more slowly than the jobs themselves, they continue being called after that phase of processing is complete.
This fix:
- Empties onComplete queues when a phase of the billing processing is complete
=> Feat/water 2609 prevent multiple onComplete handlers

migrations/20200410160941-update-batches-season-to-is-summer-flag.js, migrations/sqls/20200402122015-charge-module-bill-run-id-up.sql, migrations/sqls/20200410160941-update-batches-season-to-is-summer-flag-down.sql, migrations/sqls/20200410160941-update-batches-season-to-is-summer-flag-up.sql, src/lib/connectors/repos/billing-batch-charge-versions.js, src/lib/connectors/repos/queries/billing-batch-charge-versions.js, src/lib/models/batch.js, src/modules/billing/controller.js, src/modules/billing/mappers/batch.js, src/modules/billing/routes.js, src/modules/billing/service/charge-version-year.js, src/modules/billing/services/batch-service.js, src/modules/billing/services/charge-version-service.js, src/modules/billing/services/two-part-tariff-service/returns-helpers.js, test/lib/connectors/repos/billing-batch-charge-versions.js, test/lib/models/batch.js, test/modules/billing/controller.js, test/modules/billing/mappers/batch.js, test/modules/billing/routes.js, test/modules/billing/service/charge-version-year.js, test/modules/billing/services/batch-service.js, test/modules/billing/services/charge-version-service.js, test/modules/billing/services/two-part-tariff-service/returns-helpers.js, test/modules/billing/services/two-part-tariff-service/test-batch.js
WATER-2611
Changes batches to have the concept of is_summer rather than season.
This defaults to false and would be true only for some two part tariff
bill runs.
Changes batches table to have is_summer flag
=> Feat: Handles seasons with two part tariff

src/lib/models/invoice-licence.js, src/modules/billing/mappers/invoice-licence.js, test/lib/models/invoice-licence.js, test/modules/billing/mappers/invoice-licence.js, test/modules/billing/services/invoice-service.js, test/modules/billing/services/supplementary-billing-service.js
Adds the invoiceId to the invoiceLicence model.
This is so the UI can request the parent invoice when it only has an invoiceLicence model
=> Include invoiceId in invoiceLicence model

config.js
Reduces water-service connection pool count, as when considering the connection pools required for knex in the water service and CRM, the available connection count was exceeded.
=> Tweak water-service connection pool

src/lib/connectors/crm-v2/invoice-accounts.js
An issue was found where for large bill runs, the number of invoice accounts requested from the CRM caused the max advisable query length of 1024 to be exceeded.
This fix resolves this by chunking the queries.
=> Fixes issue with CRM v2 invoice accounts connector

src/lib/connectors/crm-v2/addresses.js, src/lib/connectors/crm-v2/companies.js, src/lib/connectors/crm-v2/contacts.js, src/lib/connectors/crm-v2/documents.js, src/lib/connectors/crm-v2/invoice-accounts.js, src/lib/connectors/crm-v2/test-data.js, test/lib/connectors/crm-v2/addresses.js, test/lib/connectors/crm-v2/companies.js, test/lib/connectors/crm-v2/contacts.js, test/lib/connectors/crm-v2/documents.js, test/lib/connectors/crm-v2/invoice-accounts.js, test/lib/connectors/crm-v2/test-data.js
WATER-2642
Adds the connector code for
- addresses
- companies
- contacts
- documents
- invoice-accounts
- test data
=> Feat: Add connector code from CRM test data endpoints

src/modules/import/services/zip-service.js, test/modules/import/services/zip-service.js
7z demands no space after switches on linux
=> Fix: Fixes a syntax issue with 7z on linux

package-lock.json, src/modules/acceptance-tests/lib/batches.js, test/modules/acceptance-tests/lib/batches.js
During acceptance test teardown null batch ids are filtered to prevent
bookshelf throwing an error
=> Fix: Prevents attempting to deal null batch ids

src/modules/returns/lib/csv-adapter/csv-parser.js, src/modules/returns/lib/csv-adapter/mapper.js, src/modules/returns/lib/csv-adapter/validator.js
Fixes an issue where empty lines at the bottom of an uploaded CSV caused the mapping stage to fail.
This is fixed by using the same CSV parsing options that were already used for the validation stage.
=> Fix issue with empty lines in CSV for returns upload

src/lib/connectors/returns.js, test/lib/connectors/returns.js
Fixes an issue where very large volumes could not be submitted via CSV.
At one stage in the process, active returns are fetched from the returns module, and a very long query string was generated.
This fix requests active returns in batches to avoid the query string exceeding around 2048 chars.
=> Fixes bulk returns upload issue with large volume of returns in CSV

src/lib/connectors/repos/index.js, src/lib/connectors/repos/licence-versions.js, src/lib/mappers/licence-version.js, src/lib/models/licence-version.js, src/lib/services/licences.js, src/modules/licences/controllers/licences.js, src/modules/licences/routes/licences.js, test/lib/connectors/repos/licence-versions.js, test/lib/mappers/licence-version.js, test/lib/models/licence-version.js, test/lib/services/licences.js, test/modules/licences/controllers/licences.js, test/modules/licences/routes.js, test/test-helpers.js
WATER-2705
Adds the resource endpoint at /water/1.0/licences/{id}/versions to get
all the licence versions for the given licence
Includes new models and mappers
=> Feat: Licence Versions endpoint

src/lib/models/charge-element.js, src/lib/models/transaction.js, test/lib/models/charge-element.js, test/lib/models/transaction.js
Permits transaction volume to go to max of charge element auth and billable volume.
This is because in many cases the billable volume is higher.
=> Fix issue setting transaction volume to billable volume

src/lib/connectors/repos/queries/billing-batch-charge-versions.js
Fixes issue where a charge version with only expired time-limited elements of the selected season was being included in a bill run.
=> Consider time-limited dates when getting charge versions for TPT

src/lib/connectors/repos/index.js, src/lib/connectors/repos/purpose-uses.js, src/lib/mappers/return-line.js, src/lib/mappers/return-version.js, src/lib/mappers/return.js, src/lib/models/constants.js, src/lib/models/return-line.js, src/lib/models/return-version.js, src/lib/models/return.js, src/lib/models/validators.js, src/lib/services/returns/api-connector.js, src/lib/services/returns/index.js, test/lib/connectors/repos/purpose-uses.js, test/lib/models/return-line.js, test/lib/models/return-version.js, test/lib/models/return.js, test/lib/services/returns/api-connector.js, test/lib/services/returns/index.js
In preparation for changes to two-part tariff matching, this PR:
- Adds service models for returns, versions and lines
- Adds mappers for the above from the returns service
- Adds a returns service which retrieves returns in the service model structure for a given licence within a financial year
This code is not currently used.
=> Initial work to create service models for returns, lines and versions

src/lib/models/batch.js, src/lib/models/financial-year.js, src/lib/models/invoice.js, src/lib/models/transaction.js, src/modules/billing/mappers/invoice.js, src/modules/billing/services/supplementary-billing-service.js, test/lib/models/batch.js, test/lib/models/financial-year.js, test/lib/models/invoice.js, test/lib/models/transaction.js, test/modules/billing/services/billing-volumes-service.js, test/modules/billing/services/charge-processor-service/data.js, test/modules/billing/services/supplementary-billing-service.js, test/modules/billing/services/two-part-tariff-service/test-batch.js, test/modules/billing/test-data/test-billing-data.js
Fixes an issue where due to a recent change (where invoices are now per financial year) the supplementary billing service was not correctly assembling the object graph of batch / invoices / invoice licences / transactions before persisting credits.
=> Fix issue where supplementary billing process did not create credits

integration-tests/billing/services/data/licences.js, migrations/20200728085519-update-licences-include-in-supplementary-billing.js, migrations/sqls/20200728085519-update-licences-include-in-supplementary-billing-down.sql, migrations/sqls/20200728085519-update-licences-include-in-supplementary-billing-up.sql, src/lib/connectors/repos/licences.js, src/lib/connectors/repos/queries/billing-batch-charge-versions.js, src/lib/connectors/repos/queries/licences.js, src/lib/models/constants.js, src/lib/models/invoice.js, src/lib/services/licences.js, src/modules/billing/jobs/lib/batch-job.js, src/modules/billing/services/batch-service.js, src/modules/billing/services/invoice-licences-service.js, test/lib/connectors/repos/licence.js, test/lib/connectors/repository/LicenceRepository.js, test/lib/models/invoice.js, test/lib/services/licences.js, test/modules/billing/jobs/lib/batch-job.js, test/modules/billing/services/batch-service.js, test/modules/billing/services/invoice-licences-service.js
WATER-2728
Updates the water.licences table to use an enum rather than a flag for
include_in_supplementary_billing
Updates references to use the new enum value
Sets licence status when invoice is deleted from batch
If an invoice or invoice licence is deleted from a batch then set the
licence's include-in-supplementary billing status from 'yes' to
'reprocess'
Updates the licence's includeInSupplementaryBilling status when the
batch is ended, either through error or cancellation, or when the batch
is sent.
=> Feat: Licence include in supplementary billing

src/lib/connectors/crm/documents.js, src/modules/communications/controller.js, test/lib/connectors/crm/documents.js, test/modules/communications/controller.js
WATER-2788
For notifications sent to many licences there was an issue with the
generated querystring becoming too large.
This change chucks the queries into batches of 20 to prevent exceeding
the max querystring size
=> Fix: Chucks documents query to prevent large query string

migrations/sqls/20200529094058-add-batchId-to-billing-volumes-table-up.sql
The column already exists on the development server for some reason so
this prevents the migrations from failing so future migrations can
execute.
=> Fix: Updates a migration that won't run on dev server

migrations/sqls/20200618093833-add-volume-to-billing-volumes-table-down.sql, migrations/sqls/20200618093833-add-volume-to-billing-volumes-table-up.sql
Fixes an issue where migrations didn't run in some environments due to column already being present
=> Fix issue with migrations when volume column already exists

src/lib/models/charge-element.js, test/lib/models/charge-element.js
WATER-2772
Exposes the charge element maxAnnualQuantity property to the JSON object
created when calling ChargeElement.toJSON
=> Feat: Adds charge element maxAnnualQuantity to JSON

migrations/20200813133609-return-version-tables.js, migrations/sqls/20200813133609-return-version-tables-down.sql, migrations/sqls/20200813133609-return-version-tables-up.sql
Adds return requirement tables to the water service.
This is so that two-part tariff billing can take into account which returns seasons are needed for a particular licence.
=> Feat/water 2799 - adds return requirements tables to water service

src/lib/connectors/repos/charge-version-workflows.js, src/lib/connectors/repos/lib/helpers.js, src/lib/controller.js, src/modules/billing/controller.js, src/modules/billing/services/batch-service.js, src/modules/charge-versions/controllers/charge-version-workflow.js, src/modules/charge-versions/controllers/pre-handlers.js, src/modules/charge-versions/routes/charge-version-workflows.js, src/modules/charge-versions/services/charge-version-workflows.js, test/lib/connectors/repos/charge-version-workflows.js, test/lib/connectors/repos/lib/helpers.js, test/modules/billing/controller.js, test/modules/billing/services/batch-service.js, test/modules/charge-versions/controllers/charge-version-workflows.js, test/modules/charge-versions/routes/charge-version-workflows.js, test/modules/charge-versions/services/charge-version-workflows.js
WATER-2818
Adds further endpoints to charge version workflows to:
* patch an existing record
* delete an existing record.
The endpoint to POST /water/1.0/charge-versions/create-from-workflow/{chargeVersionWorkflowId} 
will be submitted in a separate PR
=> Add endpoints to patch and delete charge version workflows

src/lib/connectors/crm-v2/companies.js, src/lib/connectors/crm-v2/documents.js, src/lib/services/licences.js, src/modules/licences/controllers/licences.js, src/modules/licences/routes/licences.js, test/lib/connectors/crm-v2/documents.js, test/modules/licences/controllers/licences.js
Original ticket for context: https://eaflood.atlassian.net/browse/WATER-2786
This adds an endpoint that proxies the two newly added CRMv2 Routes for fetching information about the responsible company for a licence, and the invoice accounts associated with that licence.
=> WATER-2786 - Added GET /water/1.0/licences/licence-accounts

src/modules/billing/services/transactions-service.js, test/modules/billing/services/transactions-service.js
WATER-2783
This behaviour is no longer required because it is now handled in the
charge module.
=> Feat: Stop deleting zero value transactions

config.js, src/lib/connectors/charge-module/bill-runs-with-retry.js, src/lib/connectors/charge-module/bill-runs.js, src/modules/billing/controller.js, src/modules/billing/jobs/create-charge-complete.js, src/modules/billing/mappers/charge-module-decorators.js, src/modules/billing/services/batch-service.js, src/modules/billing/services/invoice-service.js, test/lib/connectors/charge-module/bill-runs-with-retry.js, test/modules/billing/jobs/create-charge-complete.js, test/modules/billing/mappers/charge-module-decorators.js, test/modules/billing/services/batch-service.js, test/modules/billing/services/invoice-service.js
WATER-2870
Fixes issues arising because the CM now responds with an incomplete payload depending on bill run status.
* Wraps the CM API connector code in a method which will retry up to 10 times with exponential back-off
* Does not move batch from 'processing' to 'ready' until the 'refreshTotals' job has completed
* Puts the batch back into 'processing' status while a customer is removed
=> Fix bill run issues due to CM statuses

src/lib/mappers/return-requirement.js, src/lib/models/return-requirement.js, test/lib/mappers/return-requirement.js, test/lib/models/return-requirement.js
WATER-2853
Adds the `legacyId` property to the ReturnRequirement model and mapper code.
This property is needed to support the paper forms UI flow.
=> Add legacyId to returnRequirement model and mapper

config.js, src/lib/connectors/repos/licences.js, src/lib/connectors/repos/queries/licences.js, src/lib/services/documents-service.js, src/lib/services/licences.js, src/modules/charge-versions/services/charge-version-workflows.js, src/modules/licences/controllers/licences.js, src/modules/licences/routes/licences.js, test/lib/connectors/repos/licences.js, test/lib/services/documents-service.js, test/lib/services/licences.js, test/modules/charge-versions/services/charge-version-workflows.js, test/modules/licences/controllers/licences.js, test/modules/licences/routes/licences.js
WATER-2888
Adds the start date for fetching licences without charge version to the
config file.
Adds SQL query to find all licences that have no charge versions where
the licence version is current or superseded.
Adds new route, controller handler and service code to combine licences
with licence holder role.
=> Feat: Get licences without charge versions

src/modules/licences/controllers/documents.js, src/modules/returns/pre-handlers.js, test/modules/licences/controllers/documents.js, test/modules/returns/pre-handlers.js
WATER-2430
Removes any extra args passed to Boom.unauthorized where they do not
adhere to the signature of the function.
=> Fix: Updates the use of Boom.unauthorized

src/lib/mappers/return.js, src/lib/models/return.js, test/lib/mappers/return.js, test/lib/models/return.js
Fixes an issue in the paper forms flow where the return mapper failed to map returns with "null" values in the abs period.
=> Fixes issue in paper forms flow for returns with "null" values in abs period

src/lib/connectors/repos/queries/events.js
bug/kpi-reporting
-- KPI SQL for returns by month updated to include the new subtype in events for paper form requests 
-- SQL also updated to count multiple licences for paper form requests recorded in one event to align figures on the kpi page with the number of actual paper form sent via notify
=> Bugfix - KPI reporting - returns by month query fixed

package-lock.json, package.json, src/lib/connectors/db.js
Moves the logic for mapping pool.query queries to knex.raw from service to helpers, since it is used in multiple projects.
=> Use shared knex query mapper from helpers

src/lib/connectors/repos/billing-volumes.js, src/modules/billing/jobs/create-charge.js, src/modules/billing/services/batch-service.js, test/lib/connectors/repos/billing-volumes.js, test/modules/billing/jobs/create-charge.js, test/modules/billing/services/batch-service.js
WATER-2991
Updates call to billing volumes service when marking batch as errored making the update not required as this throws an error when no rows are updated.
=> Bugfix: Marking billing volumes are errored not required.

src/modules/billing/services/cm-refresh-service.js
Adds a missing await to ensure CM refresh processing is complete when batch is marked as `ready`
=> Add missing await in CM refresh service

src/lib/connectors/repos/queries/billing-transactions.js, src/lib/connectors/repos/queries/charge-versions.js
Charge version workflows now have a `date_deleted` column for soft deleting.
This PR modifies SQL queries so that deleted charge version workflows are ignored during the billing process, and fixes a bug where they were not accounted for at all in supplementary billing.
=> Respect charge version workflow date_deleted when processing supplementary billing

src/lib/connectors/repos/billing-volumes.js, src/modules/billing/services/billing-volumes-service.js, test/lib/connectors/repos/billing-volumes.js
WATER-3069
* If all billing volumes are removed in Review stage, will not throw error
=> Fix: Makes approving billing volumes not required

src/modules/billing/services/charge-version-service.js, test/modules/billing/services/charge-version-service.js
Fixes an issue where the charge versions service could attempt to insert multiple records in `water.billing_batch_charge_version_years` breaking a unique constraint.
The cause for this was imported NALD data where multiple winter/all year TPT runs can exist in a year, causing duplicate records.
This PR:
* Re-writes the service to make it easier to understand/maintain
* Fixes above bug
* Adds test case for above scenario
=> Fix issue with TPT transactions in supplementary

src/modules/billing/services/cm-refresh-service.js
For invoices that encompass multiple licences, transactions do not appear under the correct licences. All transactions are being grouped under one licence.
=> Bugfix 1 of many for CMV2 migration

src/lib/models/invoice.js, src/modules/billing/mappers/invoice.js, test/lib/models/invoice.js
Fixes an issue where validation added to `netTotal` property of invoice model could not cope with `null` which is allowed in the DB.
=> Fix issue with invoice net total validation/mapping

src/lib/models/charge-element.js
bugfix/ce-annual-qty
-- reverts CE model annual quantity to not nullable
=> bugfix - Charge element model annual quantity set to not nullable

src/modules/billing/services/charge-processor-service/transactions-processor.js, test/modules/billing/services/charge-processor-service/transactions-processor.js
WATER-3099
* Updates calculation for authorised and billable days when creating a transaction
=> Feat: Auth and Billable days set to 0 for TPT supplementary transactions

src/modules/billing/jobs/create-charge.js, test/modules/billing/jobs/create-charge.js
`WATER-3150`
* Due to recent changes in the CM API responses, removes 409 handling (as the transaction ID is not present the invoked code cannot correctly process the response payload)
* Ensures the transaction is in "candidate" status before creating the tx in the CM
We may still need to:
* Get CM team to re-implement transaction ID in 409 response payload
* Re-introduce the 409 handling removed here
=> Skip request to CM unless transaction in "candidate" status.  

src/lib/connectors/charge-module/lib/got-with-proxy.js, test/lib/connectors/charge-module/lib/got-with-proxy.js
Parses the domain and port out of the proxy URL before passing as arguments to `tunnel`
=> Set domain and port separately in tunnel module

src/modules/billing/jobs/create-charge.js, src/modules/billing/jobs/populate-batch-charge-versions.js, src/modules/billing/jobs/prepare-transactions.js, src/modules/billing/jobs/process-charge-versions.js, src/modules/billing/services/batch-service.js, src/modules/billing/services/cm-refresh-service.js, src/modules/billing/services/job-service.js, test/modules/billing/jobs/create-charge.js, test/modules/billing/jobs/populate-batch-charge-versions.js, test/modules/billing/jobs/process-charge-versions.js, test/modules/billing/services/batch-service.js, test/modules/billing/services/invoice-licences-service.js, test/modules/billing/services/job-service.js
`WATER-3106`
Previously an empty batch was detected at various points in the billing process, and the process was aborted early.
With re-billing, a supplementary batch can contain re-billed transactions only, and this isn't known until the `refresh-totals` job is finished.  This is at the end of the process.
Therefore all empty batch detection is moved to after this process has completed.
=> Move empty batch detection to end of CM refresh

src/modules/billing/controllers/two-part-tariff-review.js, src/modules/billing/services/billing-volumes-service.js, test/modules/billing/controllers/two-part-tariff-review.js, test/modules/billing/services/billing-volumes-service.js
`WATER-3167`
Include charge period in billing volume API response, so that the charge period can be displayed during TPT review
=> Include charge period in billing volume endpoint response

src/lib/models/billing-volume.js, src/modules/billing/services/volume-matching-service/models/charge-element-container.js, test/lib/models/billing-volume.js, test/modules/billing/services/volume-matching-service/matching-service.js
`WATER-3166`
To avoid the risk of double-billing, when automatically setting billing volumes, only set the full billable volume if the billing volume season matches the charge element abstraction period season.
=> Set full billable volume only when season matches

src/modules/billing/services/charge-processor-service/lib/agreements.js, test/modules/billing/services/charge-processor-service/lib/agreements.js
`WATER-3186`
Fixes issue in charge processor where agreement history not correctly computed if agreements supplied out of chronological order.
=> Add agreements history processor test cases

src/lib/connectors/repos/licences.js, src/lib/services/licences.js, src/modules/licences/controllers/documents.js, src/modules/licences/controllers/licences.js, src/modules/licences/routes/licences.js, test/lib/connectors/repos/licences.js, test/lib/services/licences.js, test/modules/licences/controllers/documents.js, test/modules/licences/controllers/licences.js
`WATER-3191`
* Adds new endpoint to get licence model by licence number
* Refactors repo method to use helper
* Refactors service method to not require region code as argument, since licence numbers are globally unique
=> WATER-3191 - licence links broken in internal returns flows

src/lib/connectors/repos/billing-invoices.js, src/lib/connectors/repos/queries/billing-invoices.js, src/lib/services/invoice-service.js, src/modules/billing/services/batch-service.js, test/lib/connectors/repos/billing-invoices.js, test/lib/services/invoice-service.js, test/modules/billing/services/batch-service.js
Feat/water 3105
-- new delete invoice by original invoice id repo method added to billing invoices
-- delete invoice batch service method updated to revert changes to rebilling invoices, update original invoice by resetting rebillling flags, delete new rebilled invoices.
=> WATER - 3105 Water service process to safely delete rebilling invoices

src/modules/billing/services/cm-refresh-service.js
Fixes an issue where minimum charge transactions have "candidate" status instead of "charge_created"
=> Ensure min charge transactions have correct status

migrations/20210602132436-empty-event-status.js, migrations/sqls/20210602132436-empty-event-status-down.sql, migrations/sqls/20210602132436-empty-event-status-up.sql, src/lib/mappers/event.js, test/lib/mappers/event.js
`WATER-3214`
Fixes an issue where some events have an empty string as their status, which caused a validation error when mapped to the service model.
This appears to only be present for some very old events (e.g. circa 2018).
* Existing records in the DB are migrated
* Mapper is tweaked to map empty string to null
=> Fix issue on licence summary tab caused by events with empty string status

src/modules/internal-search/lib/search-returns.js
`WATER-3216`
Includes the due date in the returns search results, fixing an issue with the search results
=> Fetch due_date when getting returns by format ID

config.js, src/modules/billing/jobs/delete-errored-batch.js, src/modules/billing/register-subscribers.js, src/modules/billing/services/batch-service.js, test/modules/billing/jobs/delete-errored-batch.js, test/modules/billing/services/batch-service.js
`WATER-3246`
* Deletes CM batch on failed batch at WRLS - this allows re-billed invoices to re-billed again
* Creates a new `billing.delete-errored-batch` job to enable the deletion to be retried on failure
=> Add job handler to delete errored CM batch

src/modules/licences/controllers/documents.js, test/modules/licences/controllers/documents.js
`WATER-3257` licence summary endpoint by document ID should return not found if the CRM v1 document header is not found
=> Return not found from licence summary if document header not found

src/modules/returns/schema.js
bugfix/joi-fix-returns-schema
-- allow start reading to be 0
=> Allow meter readings for returns to start with 0

migrations/20210810160000-add-rebilling-state.js, migrations/sqls/20210810160000-add-rebilling-state-down.sql, migrations/sqls/20210810160000-add-rebilling-state-up.sql, src/lib/connectors/bookshelf/BillingInvoice.js, src/lib/connectors/repos/billing-invoices.js, src/lib/mappers/invoice.js, src/lib/models/invoice.js, src/modules/billing/jobs/rebilling.js, test/lib/connectors/bookshelf/BillingInvoice.js, test/lib/connectors/repos/billing-invoices.js, test/lib/mappers/invoice.js, test/lib/models/invoice.js, test/modules/billing/jobs/rebilling.js
feat/water-3245
-- rebilling process tweaked to allow rebilling only where
rebill status = rebill or null
-- invoice model now includes original invoice in
linked invoices for the UI
-- rebilling job updated to update the source invoice to status rebilled
-- migration to add new rebill status rebilled
=> WATER-3245 - alter re-billing logic

src/lib/connectors/repos/queries/billing-transactions.js
bugfix/water-3295
-- sql updated to only select historic transactions for licences
with an invoice that was created and still in the batch
=> bugfix-water-3295 - creating credits for licences that has been removed from the batch

src/lib/connectors/repos/queries/billing-transactions.js
Updates query to exclude 2pt transactions from supplementary processing where the charge element does not have a billing volume in the current batch
=> WATER-3323 bug fix

src/modules/billing/services/charge-version-service/two-part-tariff-seasons.js, src/modules/billing/services/supplementary-billing-service/supplementary-processor.js, test/modules/billing/services/charge-version-service/two-part-tariff-seasons.js
Bugfix/water 3321
-- charge version year records were not created for historic years for new charge versions with a start date in the past. 
-- removed the flag to add 2PT season for WRSL charge versions with historic start date. 
-- this PR also reverts an earlier fix to avoid zero balance invoices. This has a negative impact on 2PT bill runs and has to be reverted. Zero balance invoices for supp. bill runs are unavoidable due to the imported bill runs from NALD because NALD did not run separate winter and summer 2PT bill runs.
=> Bugfix - WATER - 3321

src/modules/gauging-stations/routes/index.js, test/modules/gauging-stations/routes.js
See: https://eaflood.atlassian.net/browse/WATER-3329
This is a prerequisite for: https://github.com/DEFRA/water-abstraction-ui/pull/1983
=> WATER 3329: Addition of SLD as a unit type in the tagging flow

migrations/20211201114914-sroc-flags.js, migrations/sqls/20211201114914-sroc-flags-down.sql, migrations/sqls/20211201114914-sroc-flags-up.sql, src/lib/models/charge-version.js, src/modules/charge-versions/services/charge-version-workflows.js, test/lib/models/charge-version.js, test/modules/charge-versions/services/charge-version-workflows.js
This PR adds a migration script to create a new ENUM type column for the `water.charge_versions` table to be extended, so that it can house a definition of whether a given charge version belongs to the old charging scheme or the new charging scheme.
This change does not have a corresponding user story ticket.
=> Adds a migration script and amends model

src/lib/models/billing-volume.js, test/modules/billing/mappers/billing-volume.js, test/modules/billing/services/volume-matching-service/matching-service.js
See: https://eaflood.atlassian.net/browse/WATER-3451
- Make sure the calculated volume is equal to the original volume if it has been set to null
Please note that this is a prerequisite for:  https://github.com/DEFRA/water-abstraction-ui/pull/2010
=> WATER-3451: Edit flag not set correctly

src/lib/connectors/repos/queries/charge-versions.js
bugfix/water-3387
-- charge version years query fixed to include
charge versions on the financial year boundaries
=> BUGFIX WATER 3387 - 1 day missing when charge version starts on financial year end date

integration-tests/billing/services/queries/charge-versions.js
To be really clear:
Currently, we only delete Charge Version Workflows in a Cypress run for licences which are 'test' licences.
This change will delete *all* charge version workflows instead.
Requested in https://eaflood.atlassian.net/browse/WATER-3598 to aid QA efforts.
=> Removes all Charge Version Workflows when Cypress is run

src/lib/connectors/repos/charge-categories.js
The total quantity to use for a charge reference can now be zero.
=> BUGFIX: Fix zero volume issue in connector

integration-tests/billing/fixtures/test-licences.yaml
-- changes southern test region  nald region id to 9 to avoid conflicts with the import process using the same nald region id.
=> Test data fix

integration-tests/billing/fixtures/2PT1.yaml, integration-tests/billing/fixtures/2PT2.yaml, integration-tests/billing/fixtures/AB1.yaml, integration-tests/billing/fixtures/AB2.yaml, integration-tests/billing/fixtures/SB1-1.yaml, integration-tests/billing/fixtures/SB2-1.yaml, integration-tests/billing/fixtures/SB3-1.yaml, integration-tests/billing/fixtures/charge-version-workflows.yaml, integration-tests/billing/fixtures/historic-billing-2PT1.yaml, test/lib/mappers/charge-version.js, test/lib/mappers/region.js
It was flagged by @jozzey when first building their local environment that NALD imports weren't working. It was tracked down to the Test Region that was being created having a duplicate ID to an existing real region.
We thought we had fixed the problem in [Test data fix](https://github.com/DEFRA/water-abstraction-service/pull/1683) but turns out that was for something else.
This change goes through all the places in the test fixtures where we create the **Test Region** and ensures the ID is set to `9`.
=> Fix Test Region ID in test data

src/modules/billing/controllers/batches.js, src/modules/billing/routes/batches.js, src/modules/billing/services/batch-service.js, test/modules/billing/controllers/batches.js, test/modules/billing/routes/batches.js, test/modules/billing/services/batch-service.js
https://eaflood.atlassian.net/browse/WATER-3679
By default when creating a 2-part tariff bill run the current financial year is built. The users have identified scenarios where previous financial years have not been billed. This means they currently cannot generate the bill runs for them.
This change adds a new endpoint that when passed a batch (bill run) type, region, season and current financial will return an array of `unsent` financial years.
It queries the DB for batches that have been created (ignoring, for example, errored ones). It also generates a list of financial years counting 3 back from the current financial year. Any in the second list that appears in the first is removed.
For example
- `2020` exists and has been sent
- `2022` is the current financial year
- `[2020]` is …
=> Add simplified endpoints to retrieve the data relating to batches for a financial year

test/modules/returns/controllers/csv-upload.test.js
We hadn't spotted in [use standard js for linting](https://github.com/DEFRA/water-abstraction-service/pull/1696) that a `test.only()` had been added, no doubt as the team was trying to figure out why a test wasn't passing.
We already have a fix to our CI pipeline which will check for these and fail the build. But that has not yet been added to the service CI.
Anyway, this is a quick fix to remove the `only()` and get _all_ the unit tests running again.
=> Fix only() left in unit tests

src/modules/billing/routes/batches.js
https://eaflood.atlassian.net/browse/WATER-3712
There is a feature when the app is running in a non-production mode which enables in the UI the ability to delete all bill runs.
It relies on an endpoint in the service enabled via a feature toggle. Unfortunately, it looks like we broke it when tidying up the modules in `src/modules/billing/routes/batches.js` as part of [Fix module.exports](https://github.com/DEFRA/water-abstraction-team/issues/28).
This change fixes the issue and makes the endpoint accessible again.
=> Fix non-prod delete all bill runs function

src/modules/billing/mappers/transaction.js
https://eaflood.atlassian.net/browse/WATER-3586
Most of the changes needed for exporting bill run CSV files are done in the UI. However while working on this we have spotted some issues where data is not being correctly persisted in the service.
=> Persist data for sroc bill run CSV export

src/modules/gauging-stations/routes/index.js, test/modules/gauging-stations/routes.test.js
https://eaflood.atlassian.net/browse/WATER-3616
There are licences that have hands-off levels measured in mBOD. mBOD = metres below ordinance datum. As an Environment Officer, I want to tag licences with hands-off levels measured in metres below ordinance datum, so that I can send water abstraction alerts to these licences.
This adds mBOD to the unit of measurement drop down when specifying a threshold as part of the tagging flow.
=> Addition of mBOD as a unit type in the tagging flow

src/modules/charge-versions-upload/lib/validator/tests.js, test/modules/charge-versions-upload/lib/validator/validator.test.js
https://eaflood.atlassian.net/browse/WATER-3700
As part of the SRoC charge creation process, users need to enter a description for the charge reference. B&D want to be able to use ; (semi colon) and ' (apostrophe) in this description.
The list of allowed characters in WRLS is currently limited to letters (lower and upper case), hyphen (dash), numbers, forward slash, ampersand (&), asterisk , commas, brackets.
The following characters are not accepted by SOP “ ? ^ £ ≥ ≤ — (long dash).
We should allow ; and ' in WRLS, in addition to the currently accepted characters. We are amending to a 'not allowed' list instead, and only exclude those characters not accepted by SOP.
=> SRoC charge creation - additional characters required in charge reference description

src/modules/charge-categories/routes.js, src/modules/charge-versions-upload/lib/validator/csvFields.js, src/modules/charge-versions-upload/lib/validator/tests.js, test/modules/charge-categories/routes.test.js, test/modules/charge-versions-upload/lib/validator/validator.test.js
https://eaflood.atlassian.net/browse/WATER-3696
If 0 sent to charge module, it will always generate nil charge. WRLS should change validation to accept anything greater than 0.
=> Handle 0 Volumes

src/modules/charge-versions-upload/lib/helpers.js, src/modules/charge-versions-upload/lib/validator/csvFields.js, src/modules/charge-versions-upload/lib/validator/tests.js, test/modules/charge-versions-upload/lib/validator/validator.test.js
https://eaflood.atlassian.net/browse/WATER-3702
We add validation to the sroc upload feature to reject rows where the public water field is `Y` but the licence holder is not a water undertaker.
=> Sroc upload -- allow public water only for water undertakers

config.js, ecosystem.config.json, index-background.js, src/routes/background.js, test/routes/background.test.js
The service is responsible for handling multiple background processes as well as all requests from the other apps. It is the main point of contact for anything to do with the water schema for example.
This means if it needs to run any intensive processes all those other things slow down and in some cases, errors are seen. For example, the charge versions import seems to be causing the service to use 100% of the available resources allocated to it, which was leading to other requests erroring.
We want to look to see if, like the UI, we can create a second instance of the service using pm2 to manage it. If we can, we can then start to look at using the 'background' instance to run the more intensive jobs and the normal instance handling …
=> Config 2nd instance to run background jobs

src/modules/charge-versions-upload/jobs/update-charge-information-save.js, src/modules/charge-versions-upload/jobs/update-charge-information-start.js, src/modules/charge-versions-upload/jobs/update-charge-information-to-json.js
https://eaflood.atlassian.net/browse/WATER-3742
During BAT It was noted that some uploads were failing and the system was erroring in various places.
From reviewing the logs we know one of the reasons was that BullMQ was failing to ‘lock jobs' in a sufficient amount of time. Digging into the BullMQ issues on its repo we found a primary cause of this is low system resources. We could see that the API service which runs the job was hogging 100% of CPU time, which was the cause of the errors being seen i.e. low system resources.
=> SRoC - increase the timeout for the import/ upload process

src/modules/charge-versions-upload/lib/validator/csvFields.js, src/modules/charge-versions-upload/lib/validator/index.js, src/modules/charge-versions-upload/lib/validator/tests.js, test/modules/charge-versions-upload/lib/validator/validator.test.js
We are trying further optimisations to see if we can make the CSV upload even more performant. The main changes are:
- Rewritten the field names in `csvFields` from camel case to snake case to avoid unnecessary case conversion
- Remove unneeded `testNotBlank` validation, where we were first validating the field isn't blank and then validating for specific values; we now only test for the values as this will reject if the field is empty
- Specify exact columns where we can instead of looking up the column, as the CSV layout will not be changing
- Rework `testNumber` to use native JS instead of Joi, for a performance boost
- Refactor `csvFields` so generic `skip` and `allow` properties (which were only being used in very specific …
=> Further CSV upload refactoring

src/modules/charge-versions-upload/routes.js
https://github.com/DEFRA/water-abstraction-ui/pull/2179
We spotted that the charge version upload UI says the max upload is 20MB. But behind the scenes, the UI code actually allowed 50MB. We sorted that to be consistent but then spotted that the service also has a max bytes check, and it too is inconsistent with what we tell users.
Again, we don't like inconsistency! So, this updates the route config to match what we are stating on the upload page.
N.B. They also expressed the max bytes using different formats. Yeahhh! 😩
=> Make charge version max upload consistent

config.js
https://github.com/DEFRA/water-abstraction-team/issues/4
As part of [Apply consistent CI workflow](https://github.com/DEFRA/water-abstraction-service/pull/1710) we inadvertently broke the `isPermitsTestDatabase` property in `config.js`. This is used to determine which DB to use in Redis.
You may not be aware, but you can setup [multiple DB's in Redis](https://redis.io/commands/select/). You need to give it a number and Redis will create a DB for it. By default, it uses 0 but you can select something else in the connection and Redis will create a DB there.
We take advantage of this feature to
- use different db's for different apps (though it's not consistent)
- use a different db when running the unit tests (again, it's not consistent)
Recently, we've hit an issue when trying to shut down …
=> Fix tests not using test redis DB

src/lib/connectors/repos/queries/licence-versions.js
This issue was found whilst working on [Remove node-cron for BullMQ jobs](https://github.com/DEFRA/water-abstraction-service/pull/1780). In the module `charge-versions` node-cron is used to kick off a process that creates a job for every licence version ID not in the charge workflow.
We needed to recreate that with a BullMQ repeatable job so got cracking. The current process is scheduled to kick off every 6 hours but we wanted to see it running so amended the schedule to every minute.
Well, the job triggered and then we waited for the `onComplete` to fire. And waited, and waited, _and waited_! 🤔
It just didn't seem to be completing. So, we traced through the code and ended up at `src/lib/connectors/repos/queries/licence-versions.js`.
We ran …
=> Fix slow licence versions 4 charge workflow query

.env.example, config.js, src/modules/billing/jobs/check-for-updated-invoice-accounts.js, src/modules/billing/register-subscribers.js, src/modules/charge-versions/jobs/licence-not-in-charge-version-workflow.js, src/modules/charge-versions/plugin.js, test/modules/billing/jobs/check-for-updated-invoice-accounts.test.js, test/modules/charge-versions/jobs/licence-not-in-charge-version-workflow.test.js, test/modules/charge-versions/plugin.test.js
This forms part of the work we are doing to [move all background processes to a background instance of the app](https://github.com/DEFRA/water-abstraction-service/pull/1766).
Another step to that is [Refactoring message-queue to centralise job registrations](https://github.com/DEFRA/water-abstraction-service/pull/1775). At the moment each module does its own thing when it comes to registering BullMQ jobs. The problem is it makes it really hard to see just what on earth is going on in the background of the service.
It has also led to inconsistencies, one of which is using both repeatable BullMQ jobs and [node-cron](https://github.com/node-cron/node-cron) to achieve the same thing.
This change is targeted where **node-cron** is being used to …
=> Remove node-cron for BullMQ jobs

ecosystem.config.json, index-background.js, index.js, src/lib/queue-manager/queue-manager.js, src/modules/billing/jobs/process-charge-version-year.js, src/modules/billing/jobs/update-invoices.js, test/lib/queue-manager/queue-manager.test.js
> We have started this change again because [PR #1766](https://github.com/DEFRA/water-abstraction-service/pull/1766) had gone so far done a possible path that it made merging/rebasing overly complex. Simpler to start again!
We are separating out our background BullMQ tasks so that they run on a background instance. The foreground (existing instance) can then just focus on handling requests from the UI, including adding the initial jobs that kick off background processes.
We had initially looked at splitting out `QueueManager` into a `WorkerManager` (see [PR #1766](https://github.com/DEFRA/water-abstraction-service/pull/1766)). But we then found that the background instance also needs to know about queues. This is because a number of the …
=> Set up background tasks module

test/routes/background.test.js, test/routes/water.test.js
water.test is erroring with a port conflict if the tests are run while the service is running locally.
=> Fix port conflict with test

test/modules/returns/lib/xml-adapter/mapper.test.js, test/modules/returns/lib/xml-adapter/validator.test.js, test/modules/returns/lib/xml-to-json-integration.test.js
While trying to update `libxmljs` to the latest version, we found an issue where some of our unit tests start failing. This seems to be down to the newer version doing additional type checking -- previously we could simply pass a parsed XML object to it and it would simply accept it (which is what the tests were doing) but now it throws an error if you try this.
Before we update the version (which has other issues besides this!) we update the unit tests so we correctly pass through a string and not parsed XML.
=> Fix `libxmljs` unit tests

src/lib/models/financial-year.js, test/lib/models/financial-year.test.js
Whilst going through the suplementary code we spotted an unused function so we are gong to remove it.
=> Remove unused getFinancialYears function

ecosystem.config.json
We deployed the updated version of this project to production where the `service-background` instance has been kicked off for the first time.
We expected the logs pm2 generates to behave as it does with the other apps, especially as we used the `ecosystem.config.js` file from [water-abstraction-ui](https://github.com/DEFRA/water-abstraction-ui) as our template.
By this, we mean `service-background-error.log` and a `service-background-out.log` files would be generated. Instead, pm2 is suffixing the process ID into the log name, for example, `service-background-out-10.log`.
What this means is, if the process gets stopped and restarted and assigned a different process ID the logs will not follow on. It also means we can't script our AWS CloudWatch logs to pick up the right files across the …
=> Fix pm2 logs for service-background not combining

migrations/20221017134036-remove-problem-licences.js, migrations/sqls/20221017134036-remove-problem-licences-down.sql, migrations/sqls/20221017134036-remove-problem-licences-up.sql
https://eaflood.atlassian.net/jira/software/c/projects/WATER/boards/96?modal=detail&selectedIssue=WATER-3710 https://eaflood.atlassian.net/jira/software/c/projects/WATER/boards/96?modal=detail&selectedIssue=WATER-3756
We have two licences that hold problematic data currently in the water schema in the database. Here we are creating a migration script for both to remove these records.
=> Fix problem licence data

package-lock.json, package.json
https://github.com/DEFRA/water-abstraction-team/issues/58
To reduce dependencies and to make the process consistent we are moving `auto-changelog` out of the project. Instead we will use `npx` to run it directly.
=> Make `auto-changelog` external

src/modules/health/controller.js, src/modules/health/routes.js, test/modules/health/controller.test.js
https://github.com/DEFRA/water-abstraction-service/pull/1862
We are going to rename the endpoint from status to info to avoid confusion with other such endpoints.
=> Rename health status endpoint

src/routes/background.js
https://github.com/DEFRA/water-abstraction-system/pull/8
Add the health/info route to the background service as previously it was only accessible from the foreground service.
=> Add health route to background service

integration-tests/billing/fixtures/sets.json, integration-tests/billing/fixtures/sroc-charge-info.yaml, integration-tests/billing/fixtures/sroc-crm-v1.yaml, integration-tests/billing/fixtures/sroc-crm-v2.yaml, integration-tests/billing/fixtures/sroc-licences.yaml, integration-tests/billing/fixtures/sroc-permits.yaml, integration-tests/billing/fixtures/sroc-purposes.yaml
https://eaflood.atlassian.net/browse/WATER-3787
We're adding to our new SROC fixture set a pres-roc licence that we will then update the billing account on.
In the UI this would mean updating both pre-sroc and sroc charge versions. In this scenario, the 'licence' would be picked up for SROC supplementary billing because we added a new SROC charge version. But the new presroc charge version would be ignored.
=> Add new presroc billing acc. change to fixture

integration-tests/billing/fixtures/sroc-charge-info.yaml, integration-tests/billing/fixtures/sroc-crm-v1.yaml, integration-tests/billing/fixtures/sroc-crm-v2.yaml, integration-tests/billing/fixtures/sroc-licences.yaml, integration-tests/billing/fixtures/sroc-permits.yaml
https://eaflood.atlassian.net/browse/WATER-3787
This adds the fixture data for our 3rd scenario; a licence with a PRESROC and SROC charge version. Only in our test for this, the PRESROC charge version is beyond the 5-year window. So, when the change is made it should _not_ be included in a PRESROC bill run.
The SROC charge version should still be though!
=> Add SROC sup. billing scenario 3 fixture data

migrations/20221122000155-fix-leap-year-charge-purposes.js, migrations/sqls/20221122000155-fix-leap-year-charge-purposes-down.sql, migrations/sqls/20221122000155-fix-leap-year-charge-purposes-up.sql
https://eaflood.atlassian.net/browse/WATER-3827
> Users can search for and find `7/35/01/*S/001`2 without issue and see the charge versions screen. But when the select 'View' in the first charge information record they get a "Sorry, the requested URL was rejected error".
We've investigated the issue and identified the cause. The charge version has been set up with 2 `charge_purposes`:
- Spray irrigation at Marsh Dykes at Frostenden - 1-Apr to 30-Sep
- Spray irrigation storage at Marsh Dykes at Frostenden - 1-Nov to 29-Feb
When the UI attempts to show this information it makes a 'date' out of the abstraction period by bolting the current year onto the `start` and `end` days and months.
In this case, it means it's trying to make a 'date' of **29-Feb-2022**, which doesn't exist hence things …
=> Data migration fix for leap year charge purposes

src/modules/billing/services/batch-service.js, test/modules/billing/services/batch-service.test.js
https://eaflood.atlassian.net/browse/WATER-3845
This week the users tried to cancel a bill run only to see the error page. When they went back to the bill runs tab it was still listed as ready.
When we looked into the logs from both WRLS and the [SROC Charging Module API](https://github.com/DEFRA/sroc-charging-module-api) we could see
- then a request to delete the bill run in the CHA API had first failed `401`
- a new Cognito token was grabbed and then the `DELETE` request was sent again
- this time it succeeded
- it was followed by more `DELETE` requests for the same bill run
Based on the timings, some could be down to users trying again. But a number were milliseconds after the first and each other. Our suspicion is that the initial auth failure causes the WRLS service to go into a …
=> Fix cancelling billing batch error

integration-tests/billing/fixtures/sroc-charge-info.yaml, integration-tests/billing/fixtures/sroc-crm-v1.yaml, integration-tests/billing/fixtures/sroc-crm-v2.yaml, integration-tests/billing/fixtures/sroc-licences.yaml, integration-tests/billing/fixtures/sroc-permits.yaml
https://eaflood.atlassian.net/browse/WATER-3834
We need to create a scenario where we have a licence with a charge version that has multiple charge categories (elements). Then linked to those categories are multiple charge purposes with different abstraction dates.
The intent is to help us confirm we are calculating the abstraction period for each category (element) in a charge version correctly. In this change, we are currently able to generate a new SROC licence with multiple categories, and one of those categories has multiple purposes (the other just has one).
It's a start but doesn't actually represent a real-life scenario. This is because the category is not defined through fixtures but via the logic in the fixture loader. That's going to take a bit more unpicking so we'll tackle …
=> Add new SROC test fixture

integration-tests/billing/fixtures/sroc-charge-info.yaml, integration-tests/billing/services/bookshelf-loader.js
https://eaflood.atlassian.net/browse/WATER-3834
When working on the various scenarios needed to calculate the abstraction period for a charge version in a given billing period we realised there is one we could not cover.
A `charge_version` can be linked to multiple `charge_elements` and each charge element can be linked to different `billing_charge_categories`. But the current fixture logic only makes one  `billing_charge_category` available to use.
This change makes it possible to pick from 3 different `billing_charge_categories` in our fixtures.
<details>
<summary>Result after change</summary>
</details>
=> Make more charge categories available in fixtures

migrations/20230120140933-queued-batch-status.js, migrations/sqls/20230120140933-queued-batch-status-down.sql, migrations/sqls/20230120140933-queued-batch-status-up.sql, src/lib/models/batch.js, src/modules/billing/jobs/create-bill-run.js, src/modules/billing/jobs/lib/batch-status.js, src/modules/billing/services/batch-service.js, test/modules/billing/jobs/create-bill-run.test.js, test/modules/billing/jobs/process-charge-versions.test.js, test/modules/billing/jobs/two-part-tariff-matching.test.js, test/modules/billing/services/batch-service.test.js
https://eaflood.atlassian.net/browse/WATER-3877
When a supplementary bill run is started, we'll be creating both a PRESROC and SROC one at the same time.
The PRESROC one will then begin `processing` (labelled as BUILDING in the UI) whilst the SROC one is `queued` waiting to be processed.
At the moment though, all we can do is initialise the SROC bill run with a status of processing as that is all that is available to us. In the UI this will give the impression both are building when their not.
So, we need to add a new `queued` status to the code and DB. We'll make it so all new bill runs are given this status initially. Then, once processing starts the status will be updated. This is what happens at the moment. The bill run is created and then a job is added to a 'queue' for it to be …
=> Add new queued batch status

src/modules/billing/services/charge-processor-service/transactions-processor.js
A recent change as part of our efforts to remove the code base's dependency on Lodash has introduced an error. The Lodash `get()` method doesn't care if the object you are getting a property from is undefined. It will just return whatever default value you provide.
Our issue is that the existing code nor the tests gave any clue this might be the case. So, though we test for the property `triggersMinimumCharge` we were assuming `changeReason` was defined.
Turns out this is not the case. So, this change fixes the issue and prevents an error from being thrown.
=> Fix Cannot read property 'triggersMinimumCharge'

src/modules/billing/services/supplementary-billing-service/data-service.js, test/modules/billing/services/supplementary-billing-service/data-service.test.js
A recent change as part of our efforts to remove the code base's dependency on Lodash has introduced an error. The Lodash `pick()` method will only 'pick' properties on the provided object if they exist.
We replaced its use `src/modules/billing/services/supplementary-billing-service/data-service.js` with direct calls to the properties thinking the list of keys previously being provided to `pick()` was valid.
It turns out the previous team [moved fields specific to 2 part tariff](https://github.com/DEFRA/water-abstraction-service/pull/932) to a different table (`billing_volumes`) and dropped them from `billing_transactions`. But they didn't update the list of keys being used in `getReversedTransaction()`.
So, we're not assigning …
=> Fix column "calculated_volume" does not exist

src/modules/billing/jobs/create-charge.js
A recent change as part of our efforts to remove the code base's dependency on Lodash has introduced an error. The Lodash `get()` method expects a string which represents the path on the object to find a property.
When we refactored the code away from Lodash it wasn't obvious that the string was being pulled from another module. Instead, it was interpreted as a property on the object we were expecting to find.
For context, this check was being done in the create-charge billing job. Unfortunately (stupidly! 🤬), this job which is created for _every_ transaction that is a candidate in a bill run (so possibly thousands) is also being used to control when to tell the Charging Module API to `/generate` the bill run. This should only be …
=> Fix billing create charge job isReady status check

integration-tests/billing/services/fixture-loader/FixtureLoader.js, src/lib/camel-case-keys.js, src/lib/dates.js, src/lib/licence-transformer/nald-transformer.js, src/lib/make-array.js, src/lib/mappers/change-reason.js, src/lib/mappers/event.js, src/lib/mappers/invoice.js, src/lib/models/batch.js, src/lib/models/validators.js, src/lib/object-mapper.js, src/modules/billing/jobs/rebilling.js, src/modules/companies-house/mappers/companies-house.js, src/modules/licences/controllers/documents.js, src/modules/notify/connectors/scheduled-notification.js, src/modules/returns/lib/csv-adapter/validator.js, test/lib/mappers/change-reason.test.js
Lodash is used a lot in our codebase. Although we are not totally removing this module, some of the functions in the code using lodash are unnecessary. Here we are removing the unnecessary ones are replacing it with vanilla js.
This PR is focusing on the  'isString', 'isArray' and 'isEmpty' functions
=> Remove Lodash 'isString', 'isArray' and 'isEmpty' functions

.github/workflows/ci.yml, src/lib/connectors/charge-module/lib/AccessTokenManager.js, src/lib/connectors/charge-module/lib/got-cm.js, test/lib/connectors/charge-module/lib/AccessTokenManager.test.js
Whilst digging into an issue with the bill run process we spotted a a number of log messages about the access token being invalid when trying to authenticate. So, we started digging into that and found it is not working on first use.
The previous team chose to take advantage of [Got's hooks](https://github.com/sindresorhus/got/blob/main/documentation/9-hooks.md) to add the authentication header. So, we have this [beforeRequest() hook](https://github.com/sindresorhus/got/blob/main/documentation/9-hooks.md#beforerequest).
```javascript
const beforeRequestHook = async () => {
if (!accessTokenManager.isTokenValid()) {
logger.info('Fetching a new Cognito token')
// Save for further requests
const accessToken = await …
```
=> Fix broken AccessTokenManager

src/lib/connectors/charge-module/lib/got-cm.js, src/lib/connectors/charge-module/lib/got-with-proxy.js
One of the other things we've spotted with the legacy billing process is it's using both [Got](https://github.com/sindresorhus/got) and [BullMQ](https://docs.bullmq.io/) to retry failed requests.
In [Fix broken AccessTokenManager](https://github.com/DEFRA/water-abstraction-service/pull/1993) we've hopefully nullified the repeated `401` errors we see in the logs.
But sometimes a request will timeout, for example when requesting a token from the AWS Cognito service for the first time (it is like you kick it awake on the first attempt each day 🤷🫤). With the current setup, it's not **Got** that retries these, but **BullMQ** (if configured in the job).
Using our experience on [sroc-charging-module-api](https://github.com/DEFRA/sroc-charg …
=> Make Got http request retries more robust

src/lib/connectors/charge-module/lib/got-cm.js, src/lib/connectors/charge-module/lib/got-with-proxy.js
In the recent change [Make Got http request retries more robust](https://github.com/DEFRA/water-abstraction-service/pull/2000) we remarked that config we would expect to see in `src/lib/connectors/charge-module/lib/got-cm.js` was in `got-with-proxy.js`. So, we moved it!
We very quickly realised why it was there when everything broke! 🤦
What we _should_ have spotted is that `src/lib/connectors/charge-module/lib/AccessTokenManager.js` uses `got-with-proxy.js` because of the hooks built into `got-cm.js`. These automatically call AccessTokenManager, which would lead to a right mess if we used it.
So, when we moved the config we broke AccessTokenManager. This means what we _should_ have done is move our general config down into …
=> Revert and move Got config

src/modules/billing/jobs/create-charge.js, test/modules/billing/jobs/create-charge.test.js
Currently, the `src/modules/billing/jobs/create-charge.js` job will retry creating the charge if an error occurs. Prior to our changes to [make Got http request retries more robust](https://github.com/DEFRA/water-abstraction-service/pull/2000) this is what the process depended on.
It was most obvious in the logs when a timeout error was thrown by **Got**.
```
2023-02-07T17:45:58.607Z - info: Handling: billing.create-bill-run.6d740335-5e6a-43b3-b0d4-b32f936b0217
2023-02-07T17:45:58.652Z - info: No cognito token found
2023-02-07T17:45:58.652Z - info: Fetching a new Cognito token
2023-02-07T17:46:17.401Z - error: Error handling: billing.create-charge.6d740335-5e6a-43b3-b0d4-b32f936b0217.622162f4-1d69-4e65-930b-e798b72d47d3 …
```
=> Stop create-charge job retrying on error

src/modules/billing/jobs/create-charge.js, src/modules/billing/jobs/lib/batch-job.js, src/modules/billing/jobs/prepare-transactions.js, test/modules/billing/jobs/create-charge.test.js, test/modules/billing/jobs/lib/batch-job.test.js, test/modules/billing/jobs/prepare-transactions.test.js
The legacy code, because of its use of [BullMQ](https://docs.bullmq.io/) is left with a bit of a problem to crack. Each step of the bill run process is represented as a 'queue' in **BullMQ**. To kick things off a job is added to the first queue (step) in the process. Typically, when one job completes it handles adding the next job to the next appropriate queue in the process.
But the point of BullMQ was for steps like creating transactions in the Charging Module; there could be thousands. So, you add all of them as individual jobs to a queue, and you have multiple workers process them asynchronously.
What happens if the next step should only happen once? For example, after adding your thousand transactions you need to tell the …
=> Stop hammering DB for batch state during bill run

src/modules/users/controller.js, test/modules/users/controller.test.js
A recent change as part of our efforts to remove the code base's dependency on Lodash has introduced an error. The Lodash `get()` method doesn't care if the object you are getting a property from is undefined. It will just return whatever default value you provide.
Our issue is that the existing code nor the tests gave any clue this might be the case. So, though we test for the property `name` we were assuming `doc.metadata.contacts[0]` would always be defined.
Turns out this is not the case. So, this change fixes the issue and prevents an error from being thrown.
For reference the error we saw was `Uncaught TypeError: Cannot read property '0' of undefined`.
=> Fix no contacts in external login

src/lib/contact-list.js, src/lib/licence-transformer/csv-transformer.js, src/lib/licence-transformer/nald-transformer.js, src/lib/mappers/company.js, src/lib/mappers/contact.js, src/lib/mappers/user.js, src/lib/models/contact-list.js, src/lib/models/factory/contact-list.js, src/lib/models/model.js, src/lib/object-mapper.js, src/lib/repository-helpers.js, src/lib/services/invoice-service.js, src/lib/services/returns/api-connector.js, src/lib/services/returns/index.js, src/lib/services/returns/returns-mapping-service.js, src/lib/stringify-values.js, src/modules/ar-analysis/lib/licence-row-mapper.js, src/modules/batch-notifications/config/returns/lib/create-notification-data.js, src/modules/batch-notifications/controller.js, src/modules/batch-notifications/lib/batch-notifications.js, src/modules/batch-notifications/lib/event-helpers.js, src/modules/billing/lib/charge-period.js, src/modules/internal-search/lib/search-returns.js, src/modules/licences/controllers/documents.js, src/modules/returns/controllers/csv-upload.js, src/modules/returns/lib/jobs/persist-returns.js, src/modules/returns/lib/returns-upload-validator.js, src/modules/returns/lib/xml-adapter/mapper.js, test/lib/services/invoice-service.test.js, test/modules/returns/lib/csv-adapter/mapper.test.js
Lodash is used a lot in our codebase. Although we are not totally removing this module, some of the functions in the code using lodash are unnecessary. Here we are removing the unnecessary ones are replacing it with vanilla js. 
This PR is focusing on the 'isObject', 'first', 'isUndefined', and 'find' functions
=> Remove 'isObject', 'first', 'isUndefined', and 'find' lodash function

integration-tests/billing/fixtures/sroc-charge-info.yaml
https://eaflood.atlassian.net/browse/WATER-3906
https://eaflood.atlassian.net/browse/WATER-3920
When trying to test the SROC supplementary bill run changes we hit an unexpected error. We were using the test data `sroc-billing-data` creates for us (see `integration-tests/billing/fixtures/sets.json`) but the bill run kept erroring unexpectedly.
We were able to diagnose the issue as a fault with the test data. The `adjustments` JSONB field in `charge_elements` is always populated for any SROC charge versions in the production data. If there are no adjustments it defaults to `{}`. This is unlike its neighbouring `additional_charges` JSONB field which is left `NULL` when empty 😩🤦.
So, we need to fix the SROC test data to ensure `adjustments` is always populated.
=> Fix missing adjustments in SROC test fixture data

src/modules/billing/controllers/batches.js, src/modules/billing/routes/batches.js, test/modules/billing/controllers/batches.test.js, test/modules/billing/routes/batches.test.js
https://eaflood.atlassian.net/browse/WATER-3906
https://eaflood.atlassian.net/browse/WATER-3912
> This is part of the [SROC supplementary bill run work](https://eaflood.atlassian.net/browse/WATER-3803)
In the supplementary bill run process the [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system) is taking things as far as having the batch, invoice, invoice licence and transaction records created in the DB and the Charging Module API.
It will then hand over control to the legacy service to extract ‘post-generate’ info from the charging module and update our data with it, and all other actions from that point on.
So, we need a way of passing control to the legacy service. Currently, in the `src/modules/billing/jobs/create-charge.js` job, once the transactions have …
=> Add new batch refresh totals endpoint

migrations/20230315122011-remove-constraint-from-billing-transactions.js, migrations/sqls/20230315122011-remove-constraint-from-billing-transactions-down.sql, migrations/sqls/20230315122011-remove-constraint-from-billing-transactions-up.sql
https://eaflood.atlassian.net/browse/WATER-3906
Somehow (seriously, how!? :angry: :sob: ) our local DB schema does not match the `dev` schema (and most likely all AWS DB schemas).
Our solution is premised on the constraint `CONSTRAINT billing_transactions_billing_invoice_licence_id_fkey FOREIGN KEY (billing_invoice_licence_id) REFERENCES water.billing_invoice_licences(billing_invoice_licence_id)` not being there. So, we just need to throw together a fix migration and re-deploy to `dev` and all will be well. :weary:
=> Remove constraint from `billing_transactions` table

src/lib/connectors/repos/queries/billing-invoices.js
https://eaflood.atlassian.net/browse/WATER-3937
We had an issue logged with our live environment. Users were attempting to run a supplementary bill run for Midlands. However, all attempts resulted in an errored bill run.
When we checked the logs, all we could find was
```
2023-03-13T09:17:34.860Z - [31merror[39m: Failed to mark invoice 26d58547-b6d4-4d72-98ca-621b327bd5ba for rebilling in charge module
2023-03-13T09:17:34.863Z - [31merror[39m: Rebilling failed 1e5649c9-448b-49d3-bbd2-1a080f045281
2023-03-13T09:17:34.881Z - [31merror[39m: Batch 1e5649c9-448b-49d3-bbd2-1a080f045281 failed with error code 90
```
After some investigation, we managed to track down the cause. An invoice created as part of the Midland 2022 Annual bill run had been flagged for re-issue. This means it's an SROC …
=> Fix SROC invoices flagged for re-issue

migrations/20230322114830-remove-constraint-from-billing-invoice-licences.js, migrations/sqls/20230322114830-remove-constraint-from-billing-invoice-licences-down.sql, migrations/sqls/20230322114830-remove-constraint-from-billing-invoice-licences-up.sql
Remove the constraint on the foreign key `billing_invoice_id` to give us more flexibility in the order we persist the data.
=> Remove constraint from `billing_invoice_licences` table

migrations/20230327150452-add-include-in-sroc-supplementary-billing-flag.js, migrations/sqls/20230327150452-add-include-in-sroc-supplementary-billing-flag-down.sql, migrations/sqls/20230327150452-add-include-in-sroc-supplementary-billing-flag-up.sql, src/lib/mappers/licence.js, src/lib/services/licences.js, src/modules/charge-versions/services/charge-version-workflows.js, test/lib/mappers/licence.test.js, test/lib/services/licences.test.js, test/modules/charge-versions/services/charge-version-workflows.test.js
https://eaflood.atlassian.net/browse/WATER-3948
We have an issue that the current `include_in_supplementary_billing` was added at a time there was only 1 charge scheme. A licence gets flagged irrespective of whether the change relates to PRESROC or SROC.
Where that has impacted us is when sending a billing batch. When it gets sent it clears the flag for _all_ licences included. But if we cancel one, for example, the PRESROC bill run, and send the SROC one we lose which licences still need to be processed on the PRESROC one.
Our solution is to add a new `include_in_sroc_supplementary_billing` flag to the `licences` table. This change covers
- a migration to add it to the table
- updating the logic which sets the include in supp. billing flags when a charge version is approved to update …
=> Add SROC include in supplementary billing flag

src/lib/connectors/repos/licences.js, src/lib/connectors/repos/queries/licences.js, src/lib/services/licences.js, src/modules/billing/services/batch-service.js, test/lib/connectors/repos/licences.test.js, test/modules/billing/services/batch-service.test.js
https://eaflood.atlassian.net/browse/WATER-3948
We have an issue that the current `include_in_supplementary_billing` was added at a time there was only 1 charge scheme. A licence gets flagged irrespective of whether the change relates to PRESROC or SROC.
Where that has impacted us is when sending a billing batch. When it gets sent it clears the flag for _all_ licences included. But if we cancel one, for example, the PRESROC bill run, and send the SROC one we lose which licences still need to be processed on the PRESROC one.
Our solution was to add a new `include_in_sroc_supplementary_billing` flag to the `licences` table in [Add SROC include in supplementary billing flag](https://github.com/DEFRA/water-abstraction-service/pull/2077). That also covered setting the new flag when a new …
=> Clear Include In SROC supp. billing flag on send

migrations/20230331071630-flag-include-sroc-supplementary.js, migrations/sqls/20230331071630-flag-include-sroc-supplementary-down.sql, migrations/sqls/20230331071630-flag-include-sroc-supplementary-up.sql
https://eaflood.atlassian.net/browse/WATER-3951
We had an issue that the current `include_in_supplementary_billing` flag was added when there was only 1 charge scheme. A licence gets flagged irrespective of whether the change relates to PRESROC or SROC.
Where that has impacted us is when sending a billing batch. When it gets sent it clears the flag for _all_ licences included. But if we cancel one, for example, the PRESROC bill run, and send the SROC one we lose which licences still need to be processed on the PRESROC one.
[Our solution](https://github.com/DEFRA/water-abstraction-service/pull/2077) was to add a new `include_in_sroc_supplementary_billing` flag to the `licences` table and only set it to 'true' when an SROC charge version is approved. That is all now working for new charge …
=> Migration to flag sroc supp. billing invoices

src/lib/mappers/charge-category.js, src/lib/mappers/charge-module.js, src/lib/mappers/supported-source.js, src/lib/models/charge-element.js, src/lib/models/charge-purpose.js, src/lib/object-helpers.js, src/modules/returns/lib/nald-returns-mapper.js
Lodash is used a lot in our codebase. Although we are not totally removing this module, some of the functions in the code using lodash are unnecessary. Here we are removing the unnecessary ones are replacing it with vanilla js. This PR focuses on removing 'truncate', 'max' and 'maxBy'.
=> Remove 'truncate', 'max' and 'maxBy' Lodash function

package-lock.json, package.json
https://github.com/DEFRA/water-abstraction-team/issues/80
Bumping puppeteer has caused it to try to download a later version of Chromium. This is fine locally and in CI but it is failing in our AWS environments. Most likely there is a firewall or something blocking it but we need to ship a release to production so we are reverting it to the last known working version and will look into it properly when we have more time.
=> Revert Puppeteer to 19.8.0

src/modules/billing/services/batch-service.js
https://eaflood.atlassian.net/browse/WATER-3944
A bug has been found in calculating the number of years to go back for ALCS supplementary billing.
The issue was caused because the `toFinancialYearEnding` variable was being modified for alcs if it was greater than 2022. Unfortunately, this value was then being used to calculate the number of years to process for alcs which was incorrect as the variable's value had been changed to 2022 prior to this step.
This fix moves the step of modifying the variable to below where it is used to calculate the number of financial years to process.
=> Supplementary Billing - Too many previous years

src/modules/batch-notifications/lib/event-helpers.js, test/modules/batch-notifications/lib/event-helpers.test.js
https://eaflood.atlassian.net/browse/WATER-3976
We've just spotted that the `src/modules/batch-notifications/lib/jobs/refresh-event.js` job is generating thousands of error notifications in our [Errbit](https://github.com/errbit/errbit) instance.
When we checked our production logs we found this error reported
```
2023-04-24T12:10:03.900Z - [31merror[39m: Error refreshing batch message event stack=TypeError: Cannot read property 'count' of undefined
at getStatusCount (/srv/app/node/water-abstraction-service/releases/20230405_073950/src/modules/batch-notifications/lib/event-helpers.js:75:29)
at Object.refreshEventStatus (/srv/app/node/water-abstraction-service/releases/20230405_073950/src/modules/batch-notifications/lib/event-helpers.js:96:16)
at runMicrotasks (<anonymous>)
at …
```
=> Fix error in Batch Notifications Refresh event job

migrations/20230516165807-unflag-non-sroc-licences.js, migrations/sqls/20230516165807-unflag-non-sroc-licences-down.sql, migrations/sqls/20230516165807-unflag-non-sroc-licences-up.sql
When we made the change [Migration to flag sroc supp. billing invoices](https://github.com/DEFRA/water-abstraction-service/pull/2088) we just assumed that all licences by now would have an SROC charge version. In testing, we have found there are licences
- with only PRESROC charge versions
- with no charge versions at all!
This means our premise that the flags would be cleared once a bill run has been run is invalid. Some licences will never be cleared! 🤦
So, we're adding this migration to clean up our mess. It will unflag any licence flagged for SROC supplementary that doesn't have at least 1 charge version with a start date >= 2022-04-01.
=> Add migration to unflag non-SROC licences

migrations/20230517070041-delete-empty-error-bill-runs.js, migrations/sqls/20230517070041-delete-empty-error-bill-runs-down.sql, migrations/sqls/20230517070041-delete-empty-error-bill-runs-up.sql
We made a change to the UI that finally allows users to [delete empty and errored bill runs](https://github.com/DEFRA/water-abstraction-ui/pull/2349).
So any new ones that get added can be dealt with. Unfortunately, we have loads of existing ones that unnecessarily drag down the performance of the bill runs page and make it harder to find meaningful bill runs.
So, this change adds a migration that will do a 'clean-up' of these empty and errored billing batches when deployed. It will be on the users then to delete any new ones created.
=> Add migration to delete empty & errored bill runs

migrations/20230522064721-unflag-non-presroc-licences.js, migrations/sqls/20230522064721-unflag-non-presroc-licences-down.sql, migrations/sqls/20230522064721-unflag-non-presroc-licences-up.sql
https://eaflood.atlassian.net/browse/WATER-3995
We added a migration recently to [unflag non-SROC licences](https://github.com/DEFRA/water-abstraction-service/pull/2150). At the same time, we learnt that the [water-import-service](https://github.com/DEFRA/water-abstraction-import) was setting `include_in_supplementary_billing` for any licence where a change in the revoked, lapsed or expired date was noticed. It wasn't checking if the licence has only SROC charge versions, or if it had none.
This causes the same problem our previous migration was fixing; licences get flagged for PRESROC supplementary billing but there is no way to clear it because they'll never be processed when billing runs.
We've [updated the water-abstraction-import](https://github.com/DEFRA/water-abstraction-import/pull …
=> Add migration to unflag non-PRESROC licences

integration-tests/billing/fixtures/sroc-licences.yaml, integration-tests/billing/fixtures/sroc-users.yaml
https://eaflood.atlassian.net/browse/WATER-4034
Since making changes to the billing process to support SROC supplementary billing some of our acceptance tests have broken. We've had to rewrite the tests to use the SROC billing data set we created to get them working again.
2 key bits it was missing were flagging licences for supplementary billing, and access to the billing & data user. Whilst running the tests we came to the conclusion the region name was causing confusion so we also change that as well.
=> Update SROC integration test data

src/modules/billing/jobs/refresh-totals.js, test/modules/billing/jobs/refresh-totals.test.js
https://eaflood.atlassian.net/browse/WATER-4000
When a bill run is created that contains invoices, and those invoices are then removed from the bill run. Upon removal of the final invoice from the bill run it is correctly set to "empty" but still shows 1 bill in the bill run along with the value of the last invoice.
When invoices are removed it checks to see if there are any left in the batch. If the number of invoices was 0 it was setting the batch status to “empty” but that was it, it didn’t update any of the values. So the billing batch record retained the values of the last invoice it was linked to since these weren’t cleared out.
This PR will fix this by clearing the remaining invoice data at the same time as setting the billing batch `status` to "empty".
=> Empty supplementary bill run showing a credit bill

src/modules/billing/jobs/lib/update-invoices-worker.js
https://eaflood.atlassian.net/browse/WATER-4056
Upon investigation, it has been found that when a bill run is created and sent that the values for the `baselineCharge` and `waterCompanyCharge` that are written to our DBs `billing_transactions` table are incorrect. These values are being taken from the Charging Modules `decisionPoints` data which should not be used, instead the values in the main `WRLSChargingResponse` should be used instead.
This PR will correct this issue for future bill runs. A script will need to be run separately to correct the data that is already in the DB.
=> Use the correct values from CM to populate DB

src/lib/connectors/charge-module/lib/got-with-proxy.js
https://eaflood.atlassian.net/browse/WATER-4055
We spotted this when an annual bill run after being 'sent' appeared to become stuck. The service failed with a timeout whilst firing the `/approve` and `/send` requests to the [Charging Module API](https://github.com/DEFRA/sroc-charging-module-api). The fact the CHA responded with `204` to both requests immediately is a thing to look into another day!
But WRLS thought it got a timeout and then blew up, leaving the bill run in a state of sending but the bill run in the Charging Module flagged as 'billed' and on its merry way to be sent out.
Things _might_ have been ok if it could have retried the request. If nothing else it brings the config in line with what we do in [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system …
=> Tell Got to retry PATCH requests

src/lib/queue-manager/queue-manager.js, src/modules/billing/controllers/batches.js, test/lib/queue-manager/queue-manager.test.js, test/modules/billing/controllers/batches.test.js
https://eaflood.atlassian.net/browse/WATER-4055
The need for this was discovered when an Annual bill run became stuck in 'SENDING'. The service failed with a timeout whilst firing the `/approve` and `/send` requests to the [Charging Module API](https://github.com/DEFRA/sroc-charging-module-api). The fact the CHA responded with `204` to both requests immediately is a thing to look into another day!
But WRLS thought it got a timeout and then blew up. When we tested we found the first time this happens the bill run is sent back to the `READY` status. But when you try again the bill run becomes stuck in `SENDING`.
Our observation was that the controller updates the billing batch's status to `SENDING` after adding the 'approve-batch' job to the queue. Only nothing then happened. The reason is …
=> Add remove job method to QueueManager

src/modules/billing/jobs/lib/update-invoices-worker.js
https://eaflood.atlassian.net/browse/WATER-4036
When `update-invoices-worker` handles sroc transactions, it maps the CM transaction to a billing transaction then updates some sroc-specific fields. This fails when handlng transactions created during reissuing.
The problem lies in the way that it determines the transaction's `billingTransactionId`: it takes the field `clientId` on the CM transaction (ie. our own billing transaction id), which is fine when we have sent a "create transaction" request across, as we include this in the request. However if the transaction was created by the CM itself during reissuing, it won't have a client id and therefore we would be trying to work with a transaction that has no transaction id!
The fix for this is straightforward. Our `mapTransaction` function …
=> Fix `update-invoices-worker` for sroc reissuing

src/lib/connectors/service-version-factory.js, test/lib/connectors/crm/service-version.test.js, test/lib/connectors/idm.test.js, test/lib/connectors/import/index.test.js, test/lib/connectors/permit.test.js
https://eaflood.atlassian.net/browse/WATER-4096
Currently, the `/service-status` endpoint in the UI is getting the versions for the various services from their `/status` endpoints. As these endpoints are going to be updated to just return a static response of `{ "status": "alive" }`, this has been updated to `/health/info` which is an endpoint created for each repo a while ago to serve the repo's version.
This work is the first task in the issue: https://github.com/DEFRA/water-abstraction-team/issues/67
=> Update /service-status version endpoints

src/routes/background.js, src/routes/water.js, test/routes/background.test.js, test/routes/water.test.js
https://eaflood.atlassian.net/browse/WATER-4096
AWS ELBs require an endpoint they can hit to confirm whether an app is running. They are commonly referred to as health checks and are used to determine whether the ELB should route traffic through to an app instance. In our apps, it is the `/status` endpoint.
The endpoint in all our repos currently reads in the `package.json` file to get the app's version number. This information is then used to support the `/service-status` page in the water-abstraction-ui. Some of the repos also include a test query to the DB to confirm it can connect.
Having checks that confirm you can connect to dependent services (databases, other apps etc) is a good thing. But the ELB health checks are made multiple times a second across all instances. They only care …
=> Start doing the minimum in /status checks

src/modules/billing/jobs/approve-batch.js, src/modules/billing/services/batch-service.js, test/modules/billing/jobs/approve-batch.test.js
In our current codebase, we utilize BullMQ for queuing bill-run jobs, with each bill run assigned a unique ID that doubles as the job ID within the queue. BullMQ's behavior prevents the existence of two jobs with the same ID in the queue. Initially, we believed that double-clicking the "Send to Bill Run" button would result in the second request being ignored, as the subsequent job would share the same ID and BullMQ would naturally dismiss it.
However, upon closer examination, we realized that the job processes on the queue with remarkable speed, allowing it to be removed from the queue before the same job can re-enter when the user inadvertently double-clicks the button. This rapid processing has led to bill runs getting stuck, as the queue attempts to process the second request, which …
=> Improve Bill Run Queue Handling to Prevent Duplicate Jobs

src/modules/batch-notifications/lib/send-batch.js, test/modules/batch-notifications/lib/send-batch.test.js
https://eaflood.atlassian.net/browse/WATER-4104
This pull request aims to improve the handling of 'return invitation' notifications specifically that multiple requests are not being processed. Upon investigation, I can see that the legacy code already addresses multiple requests. The code examines the event's status, and if it doesn't match the 'processed' status, an error is raised.
This approach is beneficial as it guarantees that the service never sends duplicate notifications. However, it has a drawback: it displays an error page to the user, implying an issue with sending the batch, when, in fact, the batch still sends correctly. It's just that subsequent requests after the initial one aren't sent.
The changes introduced in this pull request involve an additional check. This new …
=> Prevent error page showing for multiple return invitation requests

src/modules/batch-notifications/config/paper-returns/index.js, src/modules/batch-notifications/controller.js
https://eaflood.atlassian.net/browse/WATER-4106
This pull request primarily addresses the prevention of multiple requests being processed for paper return forms. In the current system, if multiple requests are made, such as by a user double-clicking, all these requests get processed, resulting in multiple sets of paper return forms being sent out. The changes introduced in this pull request involve the creation of a uniqueJobId within the (UI repository https://github.com/DEFRA/water-abstraction-ui/pull/2458) when a user starts entering their information. This unique ID is then passed across all pages and is included in the event record stored in the database. A new check is now performed at the start of handling send requests to verify whether the same ID already exists in the database. …
=> Stop duplicate paper forms

migrations/20231102122939-delete-broken-licence.js, migrations/sqls/20231102122939-delete-broken-licence-down.sql, migrations/sqls/20231102122939-delete-broken-licence-up.sql
https://eaflood.atlassian.net/browse/WATER-4182
This PR contains the migrations to remove a licence that is containing a carriage return at the end of the licence ref. This is causing the UI to error and our acceptance tests to fail.
=> Delete bugged licence

src/modules/communications/controller.js
https://eaflood.atlassian.net/browse/WATER-4246
In the service, it is possible to click on the communications tab within a licence and view all the previous letters and emails that have been sent. When you click onto the link for an email or letter with an expired/lapsed or revoked licence instead of viewing the communication this errors and sends the user to a reject URL page. 
Upon investigation, this is because a default parameter called `includeExpired?` is set to false. This parameter is linked to the documents table in CRM. It's referring to the metadata column and the property `isCurrent`. When the parameter is set to false, it uses this as a filter and will ignore any documents that are not current. This means when we are trying to view communications for expired/lapsed and …
=> Expired Licence Communications Bug

package-lock.json, package.json
> See [Bump moment from 2.29.4 to 2.30.1](https://github.com/DEFRA/water-abstraction-service/pull/2375) for Dependabot bump that exposed this issue
**Dependabot** recently tried to bump [Moment](https://github.com/moment/moment) to a new minor version. However, when it did Ci started failing with breaking tests.
When we dug in we discovered the reason was any dates we tested where the day had a leading zero, for example, `03 August 2019`. One of the changes between **Moment** 2.29.4 and 2.30 was [[bugfix] Stricter single digit date parsing](https://github.com/moment/moment/pull/5592).
[The issue](https://github.com/moment/moment/issues/5314) that got fixed was that if you specify a date format of `['D MMMM YYYY']` then test if `03 August 2019` is valid **Moment** should say no. Before the …
=> Lock version of moment due to breaking changes

migrations/20240207123613-delete-broken-licence.js, migrations/sqls/20240207123613-delete-broken-licence-down.sql, migrations/sqls/20240207123613-delete-broken-licence-up.sql
https://eaflood.atlassian.net/browse/WATER-4357
It looks like the [water-abstraction-import](https://github.com/DEFRA/water-abstraction-import) has managed to import a duplicate NALD licence record (again!) this time because it differs from an existing one due to a leading space.
The Billing & Data team can clean up NALD by removing the problem record. But now it's been created in our DB the only way to remove it is with a migration. Until we remove it any searches where `NW/075/0012/011` appears in the results cause an error.
=> Fix - Delete licence with invalid leading space

src/modules/billing/jobs/lib/update-invoices-worker.js, src/modules/billing/jobs/update-invoices.js, src/modules/billing/services/batch-service.js, test/modules/billing/services/batch-service.test.js
https://eaflood.atlassian.net/browse/WATER-4345
We have been working on replacing the legacy SROC annual billing engine with one in [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system). That engine is based on the one we built for supplementary billing which is also in **water-a
bstraction-system**.
We needed to deliver supplementary billing as soon as we could so only replaced part of the work the legacy service was doing. The new engines extract the transaction information and send it to the [Charging Module API](https://github.com/DEFRA/sroc-charging-module-api). They even tell it to generate the bill run. But they then send a request to this legacy service's `/water/1.0/billing/batches/{id}/refresh` endpoint. This does the job of querying the CHA for the …
=> Stop marking bill runs as ready when they are not

src/modules/billing/jobs/update-invoices.js
https://eaflood.atlassian.net/browse/WATER-4345
We have been working on replacing the legacy SROC annual billing engine with one in [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system). That engine is based on the one we built for supplementary billing, also in **water-abstraction-system**.
In the previous change, we updated this project to [Stop marking bill runs as ready when they are not](https://github.com/DEFRA/water-abstraction-service/pull/2442).
The refresh job was marking the bill run as ready and _then_ kicking off the process to refresh WRLS with data from the Charging Module API.
As part of that, we also tried to make the process more robust and stop depending on creating a child process.
All seemed well until we tested with our largest region. The …
=> Ensure update-invoices sets bill run to ready

src/lib/constants.js, src/lib/queue-manager/job-registration-service.js, src/modules/billing/jobs/refresh-totals.js, src/modules/billing/jobs/update-invoice-references.js, src/modules/billing/services/batch-service.js, src/modules/billing/services/cm-refresh-service.js, test/modules/billing/jobs/refresh-totals.test.js, test/modules/billing/services/batch-service.test.js, test/modules/billing/services/cm-refresh-service.test.js
https://eaflood.atlassian.net/browse/WATER-4345
We have been working on replacing the legacy SROC annual billing engine with one in [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system). That engine is based on the one we built for supplementary billing, also in **water-abstraction-system**.
In a previous change, we updated this project to [Stop marking bill runs as ready when they are not](https://github.com/DEFRA/water-abstraction-service/pull/2442).
The refresh job was marking the bill run as **ready** and _then_ kicking off the process to refresh WRLS with data from the Charging Module API. That process entails making a request for every bill in the bill run to the CHA and then updating our local invoice and transactions with the result.
You can't **SEND** a …
=> Fix broken send bill run functionality

src/modules/billing/jobs/refresh-totals.js, test/modules/billing/jobs/refresh-totals.test.js
https://eaflood.atlassian.net/browse/WATER-4345
In [Fix broken send bill run functionality](https://github.com/DEFRA/water-abstraction-service/pull/2446) we removed some config from the `src/modules/billing/jobs/refresh-totals.js` job that allowed it to be retried within BullMQ.
We figured this exponential retry is why the job gets stuck in the background. But actually, we were just displaying our ignorance. Because it can take a moment for the CHA to complete the 'send' process, it likely won't have a status of `billed` if immediately queried after sending it.
It turns out the previous team used the BullMQ mechanism for retrying to get the CHA bill run summary rather than their own for this job. So, removing the config broke the process. We didn't spot this until put it in one of our AWS …
=> Fix refresh totals job

src/lib/connectors/repos/billing-batches.js
https://eaflood.atlassian.net/browse/WATER-4387
We need to add this to support our work to make cancelling bill runs visible to users.
Cancelling a bill run, especially a large one, can impact the service and take a considerable amount of time (30 minutes for the largest ones!) We want to let users know when a bill run is being cancelled so that they can make a more informed decision as to when it is best to try creating a new bill run.
When the [water-abstraction-ui](https://github.com/DEFRA/waterr-abstraction-ui) returns the list of bill runs for the bill runs page this service was filtering out any that had a status of 'cancel'. We can't make them visible if they are not returned!
So, this change updates the project to stop the filtering.
=> Stop filtering cancel bill runs in results

src/modules/billing/services/invoice-licences-service.js
https://eaflood.atlassian.net/browse/WATER-4415
We spotted that our new billing views had dropped the button that allows a user to remove a licence from a bill run (only applies to `READY`` bill runs and bills with more than one licence).
We put the button back in and even gave the confirmation page a refresh. But we're not in a position to migrate the actual work yet. So, our page like the old one pings the same legacy endpoint as [water-abstraction-ui](https://github.com/DEFRA/water-abstraction-ui).
Our QA team being as conscientious as always double-checked all aspects, following up on the message that both the old and new pages display stating the licence will be flagged for the next supplementary bill run.
They have found it only flags it for the old (PRESROC) charge scheme.
We need …
=> Fix remove bill licence supplementary flagging

src/modules/billing/services/batch-service.js, test/modules/billing/services/batch-service.test.js
https://eaflood.atlassian.net/browse/WATER-4416
We spotted that our new billing views had dropped the button that allows a user to remove a licence from a bill run (only applies to `READY` bill runs and bills with more than one licence).
We put the button back in and even gave the confirmation page a refresh. But we're not in a position to migrate the actual work yet. So, our page like the old one pings the same legacy endpoint as [water-abstraction-ui](https://github.com/DEFRA/water-abstraction-ui).
Our QA team being as conscientious as always double-checked all aspects, following up on the message that both the old and new pages display stating the licence will be flagged for the next supplementary bill run. They found it always flags them for PRESROC, when it should have been flagging …
=> Fix remove bill not flagging licences for supp.

integration-tests/billing/fixtures/sroc-crm-v2.yaml
When we run our [acceptance-tests](https://github.com/DEFRA/water-abstraction-acceptance-tests) they trigger the legacy test data setup process found in this service. We create records in the DB based on yml files.
So that the tests have consistency a number of the references are hardcoded, for example, billing account numbers. The problem is within the service these are dynamically generated. Some of the team have encountered clashes when trying to run the test data setup processes. Other actions within their environment have created accounts that clash with those the test setup process is trying to create.
We think when the process was set up, the previous team knew that the service was always doing the last account + 1 to determine the next account number. So, they opted for a very low …
=> Fix acceptance test account number clashes

integration-tests/billing/fixtures/sets.json, integration-tests/billing/fixtures/sroc-annual-bill-run.yaml, integration-tests/billing/services/fixture-loader/FixtureLoader.js
https://eaflood.atlassian.net/browse/WATER-4403
In [Bump supplementary end year if no annual bill run](https://github.com/DEFRA/water-abstraction-system/pull/875) we amended our billing engine for supplementary. We made it possible for users to generate supplementary bill runs in years where no annual has yet been created and sent.
Previously, the Billing & Data team would have to put a block on creating bill runs until the annuals were generated. This is because supplementary takes into account previous transactions whereas annual doesn't. Without the change creating a supplementary followed by an annual bill run would result in the customer getting charged twice.
We now determine when the last annual bill run was sent and use its financial end year as the end year for the supplementary …
=> Update SROC test data to always include annual

migrations/20240415100933-tag-updated-to-setup-workflows.js, migrations/sqls/20240415100933-tag-updated-to-setup-workflows-down.sql, migrations/sqls/20240415100933-tag-updated-to-setup-workflows-up.sql
https://eaflood.atlassian.net/browse/WATER-4437
For context, we found out legacy background jobs scheduled in BullMQ only run intermittently. One we found hadn't run for the last 2 years so we agreed to bin it. Two we need to deal with at some point but intermittent is fine for now. The critical job, which is putting updated licences into workflow, we solved by migrating to [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system/pull/903).
As part of solving it we took the opportunity to add data to the workflow record to allow us to identify that the record was added because of an updated licence. We also spotted that our time-limited job was broken 😱 so [fixed that](https://github.com/DEFRA/water-abstraction-system/pull/908) and updated it to _also_ add some info to …
=> Identify workflow setup records with chg versions

migrations/20240429132856-add-include-in-sroc-tpt-supplementary-billing-flag.js, migrations/sqls/20240429132856-add-include-in-sroc-tpt-supplementary-billing-flag-down.sql, migrations/sqls/20240429132856-add-include-in-sroc-tpt-supplementary-billing-flag-up.sql
https://eaflood.atlassian.net/browse/WATER-4216
Part of the ticket to remove a two-part tariff licence from a bill run is to flag that licence for supplementary billing once removed.
No column exists in the database to flag a licence for two-part tariff supplementary billing. So in this PR a migration will be created to add it to the licence table.
The migrations to update the view and legacy tables will be done in the `system` repo as part of the work to remove the licence from a 2PT bill run in this PR https://github.com/DEFRA/water-abstraction-system/pull/927
=> Add column to `licences` table to flag for 2PT supplementary billing

migrations/20240518095436-water-return-versions-add-reason-column.js, migrations/sqls/20240518095436-water-return-versions-add-reason-column-down.sql, migrations/sqls/20240518095436-water-return-versions-add-reason-column-up.sql
https://eaflood.atlassian.net/browse/WATER-4470
The new return requirements setup journey captures a reason for the requirement, and we don't currently have a place to store it. This change adds a column to the `water.return _versions` table to store it.
=> Add reason column to water.return_versions table

migrations/20240519141924-fix-missing-licence-holders.js, migrations/sqls/20240519141924-fix-missing-licence-holders-down.sql, migrations/sqls/20240519141924-fix-missing-licence-holders-up.sql
https://eaflood.atlassian.net/browse/WATER-4433
https://eaflood.atlassian.net/browse/WATER-4434
When working on the new view licence page, we have been working under the premise that the licence holder for all licences is known. Unfortunately, during testing, we found this is not the case. At the time of creating this fix migration there are 38 licences that do not have the correct record in `crm_v2.document_roles` to denote who the licence holder is.
When we looked at how the legacy service behaved we found that in some cases it _did_ show a licence holder! Further digging found that of the 38, 20 have the information stored in `crm.document_header.metadata`. Why these 20 never got a `crm_v2.document_roles` created we're chalking up to the brittleness of the legacy code.
This change is a …
=> Fix missing licence holder crm_v2 records

migrations/20240520074017-water-return-versions-add-multiple-upload-column.js, migrations/sqls/20240520074017-water-return-versions-add-multiple-upload-column-down.sql, migrations/sqls/20240520074017-water-return-versions-add-multiple-upload-column-up.sql
https://eaflood.atlassian.net/browse/WATER-4471
As part of our work in replacing NALD for use for returns we need to identify if a return is part of a multiple upload. This PR adds a boolean column to do just that.
=> Add multiple_upload column to return_versions table

migrations/20240521125247-water-return-versions-add-notes-column.js, migrations/sqls/20240521125247-water-return-versions-add-notes-column-down.sql, migrations/sqls/20240521125247-water-return-versions-add-notes-column-up.sql
https://eaflood.atlassian.net/browse/WATER-4472
As part of the work to replace NALD we want to be able to store a note against the return version rather than the return requirements. This PR is to create that notes column on the return_versions table.
=> Add notes column to return-versions table

migrations/20240524080831-water-add-return-requirement-points-table.js, migrations/sqls/20240524080831-water-add-return-requirement-points-table-down.sql, migrations/sqls/20240524080831-water-add-return-requirement-points-table-up.sql
https://eaflood.atlassian.net/browse/WATER-4475
As part of our plan to replace NALD we need to be able to store the detail of the points of abstraction. This PR creates the table that will store the data.
=> Create return-requirement-points table

migrations/20240531093133-return-requirements-alter-column-name.js, migrations/sqls/20240531093133-return-requirements-alter-column-name-down.sql, migrations/sqls/20240531093133-return-requirements-alter-column-name-up.sql
https://eaflood.atlassian.net/browse/WATER-4474
As part of the work to replace NALD in handling return requirements we need to know if the use has selected any agreements or exceptions for the return. This PR renames a misspelt column name.
=> Rename misspelt column on return-requirements table

migrations/20240604163239-alter-return-requirement-tables.js, migrations/sqls/20240604163239-alter-return-requirement-tables-down.sql, migrations/sqls/20240604163239-alter-return-requirement-tables-up.sql
https://eaflood.atlassian.net/browse/WATER-4467
In recent changes, we have either added new fields to the `water.return_requirement[..]` tables or added a whole new one (`return_requirement_points`). But as we have come to use them in [water-abstraction-system] (https://github.com/DEFRA/water-abstraction-system) we have found there are some further corrections and fix-ups we can do to make our lives easier.
This change is those fix-ups.
=> Fix up the water schema Return requirement tables

migrations/20240605155346-alter-return-requirement-points.js, migrations/sqls/20240605155346-alter-return-requirement-points-down.sql, migrations/sqls/20240605155346-alter-return-requirement-points-up.sql
https://eaflood.atlassian.net/browse/WATER-4493
Returns submitted to the service are sent back to NALD. There are then data reports that link the return submissions to their relevant points. But when we take over the returns functionality from NALD the link between a return submission (form log) and the point will be lost if we don't have some way of capturing the NALD unique point ID.
The submissions (returns.returns) link to `water.return_requirements` which in turn is linked to `water.return_requirement_points`. If that table contains the NALD point ID then they should be able to link submissions to specific points when creating reports.
This change adds a new column to the `water.return_requirement_points` table to hold the NALD point ID.
=> Add NALD point ID to return req points table

migrations/20240610104955-alter-return-requirements.js, migrations/sqls/20240610104955-alter-return-requirements-down.sql, migrations/sqls/20240610104955-alter-return-requirements-up.sql
https://eaflood.atlassian.net/browse/WATER-4473
We recently extended the import of return requirements from NALD to include the frequency with which returns need to be collected. We thought with this and `returns_frequency` we would have the data we need to support the return requirements setup journey.
However, we now realise we made an incorrect assumption about what `returns_frequency` represents. We thought it was the reporting frequency; however it turns out NALD has 3 frequency levels.
- Return to agency (`ARTC_RET_FREQ_CODE`)
- Recording (`ARTC_REC_FREQ_CODE`)
- Collection (`ARTC_CODE`)
Because we assumed `ARTC_RET_FREQ_CODE` was reporting, we're importing `ARTC_REC_FREQ_CODE` as collection. Now we know it should have been
- `ARTC_REC_FREQ_CODE` is reporting frequency
- `ARTC_CODE` …
=> Fix return req frequency fields being imported

migrations/20240619194829-alter-return-versions.js, migrations/sqls/20240619194829-alter-return-versions-down.sql, migrations/sqls/20240619194829-alter-return-versions-up.sql
https://eaflood.atlassian.net/browse/WATER-4522
> Part of the work to replace NALD for handling return requirements
When we take control of the setup of return requirements, we'll be persisting them in the same tables that they are currently imported into.
One omission though, is that there is no means to identify who created the return version. Admittedly there is nothing in NALD to indicate this hence nothing to import. But we intend to capture this information when we start persisting the records.
This adds a migration to add `created_by` to `water.return_versions`.
=> Add created_by to return versions table

migrations/20240809155344-water-versions-add-mod-log-column.js, migrations/sqls/20240809155344-water-versions-add-mod-log-column-down.sql, migrations/sqls/20240809155344-water-versions-add-mod-log-column-up.sql
https://eaflood.atlassian.net/browse/WATER-4563
https://eaflood.atlassian.net/browse/WATER-4564
https://eaflood.atlassian.net/browse/WATER-4565
> Part of the work to display a licence's history to users (mod log)
NALD has a concept called 'mod log'. Essentially, when someone creates a new licence, charge or return version, they are required to provide a reason and can also add a note.
Rather than this being stored against each record, the 'mod log' is stored in a single place. Users can then view a licence's 'mod logs' to get a sense of the history of the licence.
When charging switched from NALD to WRLS, we (the previous team) built the ability to record a reason and note against a new charge version but didn't import any historic data. With return requirements also soon to switch from …
=> Add mod_log fields 2 return, licence & charge ver.

migrations/20240812135353-alter-water-notes.js, migrations/sqls/20240812135353-alter-water-notes-down.sql, migrations/sqls/20240812135353-alter-water-notes-up.sql
https://eaflood.atlassian.net/browse/WATER-4566
During the creation of the licence history page, we noticed we were missing the model and helper for the notes table. This is being referenced when extracting charge versions for a licence and any relating notes created. This is being worked on in the [Create notes table model, helper, and view](https://github.com/DEFRA/water-abstraction-system/pull/1240) in the water-abstraction-system repo.
While working on the change we realised the notes table has fields that are unused:
- `licence_id` - is never populated
- `type` - is always set to 'charge-version'
- `type_id` - is set to the charge version's id and is not needed to link the two together
We do not these fields included in the view for the notes table that we will add to …
=> Fix type defaults on the water notes table

.env.example, config.js, src/lib/connectors/system/supplementary-billing.js, src/lib/services/charge-versions.js, test/lib/services/charge-versions.test.js
https://eaflood.atlassian.net/browse/WATER-4622
As part of the work for two-part tariff supplementary billing, we need to add the system config for the service repo to hit a new endpoint we have created. The endpoint is to flag a licence for supplementary billing. As there are 5 different ways a licence can get flagged with 3 of them triggered from the service repo, this PR will allow us to hit the system endpoint and add the flag if necessary.
=> Add System config for Supplementary billing flags

migrations/20240814102304-alter-licence-version-created-and-updated-at.js, migrations/20240814103242-alter-licence-version-purposes-created-and-updated-at.js, migrations/sqls/20240814102304-alter-licence-version-created-and-updated-at-down.sql, migrations/sqls/20240814102304-alter-licence-version-created-and-updated-at-up.sql, migrations/sqls/20240814103242-alter-licence-version-purposes-created-and-updated-at-down.sql, migrations/sqls/20240814103242-alter-licence-version-purposes-created-and-updated-at-up.sql, src/lib/services/licences.js
https://eaflood.atlassian.net/browse/WATER-4579
Alters the water.licence_versions and water.licence_version_purposes to set the date_created and date_updated to default now.
This has been done as part migrating the legacy import licence service to the water-abstraction-system. Rather than adding this logic in the system code it makes sense to add the migration and have the database handle this logic for us.
=> Add migration for licence versions and licence versions purposes

migrations/20240814134405-alter-water-charge-batch-type.js, migrations/sqls/20240814134405-alter-water-charge-batch-type-down.sql, migrations/sqls/20240814134405-alter-water-charge-batch-type-up.sql, src/lib/models/batch.js
https://eaflood.atlassian.net/browse/WATER-4200
In order to enable the triggering of a two-part tariff supplementary bill run we first have to create a new data type for it in our DB.
In this PR the data type is going to be updated to add a new batch type of `tpt_supplementary`. Any issues that adding this new data type may cause will also be actioned in this PR.
=> Add new `batch_type` for TPT supplementary to DB

src/modules/change-email/controller.js, src/modules/change-email/lib/helpers.js, test/modules/change-email/controller.test.js, test/modules/change-email/lib/helpers.test.js
https://eaflood.atlassian.net/browse/WATER-4632
We received a report that the external app's change email journey was broken. We quickly confirmed this.
The [first part of the fix](https://github.com/DEFRA/water-abstraction-tactical-idm/pull/886) was some mis-ordered logic in the **water-abstraction-tactical-idm** project.
After spotting this, we thought we were done. However, the feature was breaking at the point you entered the security code.
We tracked it down to an issue in this project. It seems we create a `water.event` record upon confirmation of the change being verified. Or we would if it didn't blow up.
We first spotted that it was using a deprecated method for creating the event (the method and the deprecation were all created by the previous team!)
It also saved the record …
=> Fix external change user email journey

src/lib/services/charge-versions.js
https://eaflood.atlassian.net/browse/WATER-4622
> Part of the work to flag licences for SROC 2PT supplementary billing
We recently added support for sending a request to the [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system) to let it know a new charge version had been added. The intent is for **water-abstraction-system** to determine if the licence needs to be flagged for SROC two-part tariff supplementary billing because of this.
The only problem is we ain't built the endpoint yet! 🤦
We've just realised we've broken the create charge version journey because the request is getting a failed response (404). We're not far away from adding the endpoint. But even so, we don't want a failure to flag the licence to cause the charge version record to get messed up. …
=> Handle failed request to system supplementary

migrations/20240816144249-alter-versions-mod-log-column.js, migrations/sqls/20240816144249-alter-versions-mod-log-column-down.sql, migrations/sqls/20240816144249-alter-versions-mod-log-column-up.sql
https://eaflood.atlassian.net/browse/WATER-4563
https://eaflood.atlassian.net/browse/WATER-4564
https://eaflood.atlassian.net/browse/WATER-4565
> Part of the work to display a licence's history to users (mod log)
In [Add mod_log fields 2 return, licence & charge ver.](https://github.com/DEFRA/water-abstraction-service/pull/2598), we added a data migration to add a new `mod_log` field to the charge, licence, and return version tables in the `water` schema. This field was intended to hold details from the linked NALD mod log record, such as who, when, and why the version was created.
However, we've since learned that a version in NALD can have multiple mod log records. Therefore, we want to change the name to make that clear. We also change the default to avoid complexity in the code. Now, …
=> Alter name & default for versions `mod_log` field

migrations/20240819214901-fix-errant-licence-version.js, migrations/sqls/20240819214901-fix-errant-licence-version-down.sql, migrations/sqls/20240819214901-fix-errant-licence-version-up.sql
https://eaflood.atlassian.net/browse/WATER-4625
We had a report that when creating a new charge version for licence **AN/033/0058/018/R01** and selecting use abstraction data, the service used an old abstraction volume.
We tracked the issue down to the fact that there are 2 'current' licence versions linked to the licence (only one should ever be current). When the user selects the 'use abstraction data' option, the legacy code selects the first 'current' licence version connected to the licence. This explains why the value is coming from an older version.
We think the version got in there from a 'blip', probably caused by the licence in NALD being duplicated and _then_ corrected with the updated data. Then we believe the import happened in the middle of this, hence the 'blip'.
Simply …
=> Delete errant licence version

migrations/20240827145508-water-add-licence-version-purpose-points-table.js, migrations/sqls/20240827145508-water-add-licence-version-purpose-points-table-down.sql, migrations/sqls/20240827145508-water-add-licence-version-purpose-points-table-up.sql
https://eaflood.atlassian.net/browse/WATER-4645
> Part of the work to migrate return versions from NALD to WRLS
We've been extending and amending the import of return versions from NALD to WRLS as part of our work to switch from NALD to WRLS to manage them. To support this we [Created a return-requirement-points table](https://github.com/DEFRA/water-abstraction-service/pull/2540) and [updated the import](https://github.com/DEFRA/water-abstraction-import/pull/933) to import them.
Users select these points as part of the return requirements setup journey we've built. We extract them from the JSON blob stored in the `permit.licence` table. The problem we've encountered is the import service only populates the points for licences that.
- Have not ended
- Have a current licence version …
=> Add a new licence version purpose points table

migrations/20240930084009-fix-licence-wrong-region.js, migrations/sqls/20240930084009-fix-licence-wrong-region-down.sql, migrations/sqls/20240930084009-fix-licence-wrong-region-up.sql
https://eaflood.atlassian.net/browse/WATER-4686
Back in June, `WA/055/0015/022` was flagged to us as having been raised twice in NALD and, therefore, causing an issue with the import. The duplication was because the licence was first set up against the Midland region and then again against Wales. Midlans is the correct region, so they deleted that one in NALD when the problem was spotted.
However, because of the nightly import, WRLS's licence record was set up against the Midland region. We don't update the region when importing licence information, so when the record was deleted in NALD, our version stayed with the Midland region. Since then, a Midland annual bill run has been created and sent.
So, to fix the licence, we need to
- correct the region the `water.licences` is against
- …
=> Data fix licence with wrong region

migrations/20240930084009-fix-licence-wrong-region.js, migrations/sqls/20240930084009-fix-licence-wrong-region-down.sql, migrations/sqls/20240930084009-fix-licence-wrong-region-up.sql
https://eaflood.atlassian.net/browse/WATER-4686
Back in June, `WA/055/0015/022` was flagged to us as having been raised twice in NALD and, therefore, causing an issue with the import. The duplication was because the licence was first set up against the Midland region and then again against Wales. Midlans is the correct region, so they deleted that one in NALD when the problem was spotted.
However, because of the nightly import, WRLS's licence record was set up against the Midland region. We don't update the region when importing licence information, so when the record was deleted in NALD, our version stayed with the Midland region. Since then, a Midland annual bill run has been created and sent.
So, to fix the licence, we need to
- correct the region the `water.licences` is against
- …
=> Data fix licence with wrong region, again!

migrations/20241002152917-alter-points.js, migrations/sqls/20241002152917-alter-points-down.sql, migrations/sqls/20241002152917-alter-points-up.sql
https://eaflood.atlassian.net/browse/WATER-4645
> Part of the work to migrate return versions from NALD to WRLS
We recently [Added new points and sources tables & amend existing](https://github.com/DEFRA/water-abstraction-service/pull/2638) to the service. This not only supports our work on return versions, it means we can move away from abstracting point information from the licence JSON blob in `permit.licence`.
We're also looking to migrate the pages linked to from the view licence summary, which are currently in the legacy [water-abstraction-ui](https://github.com/DEFRA/water-abstraction-ui). One of them is information on points. We thought we'd captured everything 'point' related in the change but have since spotted 'Means of abstraction'.
This is linked to an abstraction purpose …
=> Add abstraction method to lic. purpose points

migrations/20241009153943-fix-is-credited-back-flags.js, migrations/sqls/20241009153943-fix-is-credited-back-flags-down.sql, migrations/sqls/20241009153943-fix-is-credited-back-flags-up.sql
https://eaflood.atlassian.net/browse/WATER-4689
Our Billing & Data users reported that presroc supplementary bill runs had been miscalculated for three licences. In all cases, a previous transaction was expected to be credited in the bill run but wasn't.
This meant the bills created were debiting the customers more than expected.
> The reason for the supplementary was either the licence being transferred or ended
When we dug into what was happening, we found that the transactions we were expecting to be included and reversed were not being selected by the `findHistoryByBatchId()` SQL query.
```SQL
-- Key extract from the src/lib/connectors/repos/queries/billing-transactions.js - findHistoryByBatchId
select t.*, il.licence_id, il.licence_ref, i.invoice_account_number, i.invoice_account_id, …
```
=> Data fix migration for miss-flagged transactions

migrations/20241012131720-fix-is-credited-back-flags-pt2.js, migrations/sqls/20241009153943-fix-is-credited-back-flags-up.sql, migrations/sqls/20241012131720-fix-is-credited-back-flags-pt2-down.sql, migrations/sqls/20241012131720-fix-is-credited-back-flags-pt2-up.sql
https://eaflood.atlassian.net/browse/WATER-4710
In the last change, we added a [Data fix migration for miss-flagged transactions](https://github.com/DEFRA/water-abstraction-service/pull/2644). In the legacy PRESROC supplementary billing engine, a flag is added to the debit: `is_credited_back` when a debit is reversed and used as a credit. It also sets `source_transaction_id` on the new transaction so it is possible to see the link between the two.
We found that the PRESROC supplementary can mess up these flags when it fails. We found
- transactions with `is_credited_back` set to true, even though their IDs do not appear in any `source_transaction_id`
- transactions with a populated `source_transaction_id`, but the source transaction does not have its `is_credited_back` flag set to true …
=> Alter fix script for miss-tagged credited trans.

migrations/20241126154953-fix-miss-linked-return-versions.js, migrations/sqls/20241126154953-fix-miss-linked-return-versions-down.sql, migrations/sqls/20241126154953-fix-miss-linked-return-versions-up.sql
https://eaflood.atlassian.net/browse/WATER-4794
> TL;DR; Never amend a licence reference in NALD!
While working on WATER-4734, we pulled together a list of all licences deleted from NALD that still exist in WRLS.
Because we have the latest version of the WATER-4654 (return version data clean-up) changes in our non-prod environments (excluding pre), we were expecting no deleted licences to be flagged as having return logs. However, six came back in the results.
We know the changes to clean the return versions handle return versions linked to 'completed' return logs. If this scenario occurs, we won't delete it until it can be looked at. So, when cleaning the licences, we can do a bit of a shortcut: any WRLS licence due to be deleted which still has a `water.return_version` record must do so …
=> Move return versions to correct licence

migrations/20250105142302-create-licence-end-date-changes.js, migrations/sqls/20250105142302-create-licence-end-date-changes-down.sql, migrations/sqls/20250105142302-create-licence-end-date-changes-up.sql
https://eaflood.atlassian.net/browse/WATER-4546
> Part of the work to migrate management of return versions to WRLS from NALD
During the import from NALD, if a licence end date is changed, for example, if it has been revoked in NALD, our return version functionality needs to know about it. This is so we can reissue the return logs for the licence to match the changed end date.
We are actively trying to move away from the legacy code base, so this work was always going to be done in [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system). Initially, it would be triggered by our [own import process due to replace the legacy one](https://eaflood.atlassian.net/browse/WATER-4535). But that was when we thought ReSP would be taking over from NALD.
Now, the plan is for WRLS …
=> Add new licence changes table

config.js, index-background.js, index.js, package-lock.json, package.json
https://github.com/DEFRA/water-abstraction-team/issues/111
Along with most other Defra services, we add this as a project standard. But we've been (rightly) challenged on what value this adds.
On [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system), we concluded it was very little and was against our ethos of 'minimal and simple', so [we removed it](https://github.com/DEFRA/water-abstraction-system/pull/1080).
This change removes it from this app.
> Note: we don't remove the `description:` property from the routes. Eventually, this repo will become redundant, so it was deemed unnecessary.
=> Remove blipp plugin

src/lib/models/batch.js
https://eaflood.atlassian.net/browse/WATER-4201
> Part of the work to support two-part tariff bill runs
We are working on adding support for two-part tariff supplementary bill runs to the service. We've [spiked the logic](https://github.com/DEFRA/water-abstraction-system/pull/1412) to understand how we can do this, but when doing it was being flagged as an error.
No errors were thrown within [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system), so we looked at this project. That's when we spotted, after triggering `src/modules/billing/jobs/refresh-totals.js`, an error was being thrown. This was because of the previous team's decision to validate all data both to and from the DB, and it not knowing about the new `two_part_supplementary` batch type.
=> Add new TPT supplementary batch type

migrations/20250309174530-fix-dupe-licence-billing-history.js, migrations/sqls/20250309174530-fix-dupe-licence-billing-history-down.sql, migrations/sqls/20250309174530-fix-dupe-licence-billing-history-up.sql
https://eaflood.atlassian.net/browse/WATER-4800
After spotting that WRLS is carrying a lot of data that no longer exists in NALD because it has been deleted, we have started a series of tasks to 'clean up' WRLS licence data.
One scenario we face is a licence deleted in NALD but linked to a 'sent' bill run in WRLS (see WATER-4734 for more details).
Our queries highlighted `MD/0280003/012`` as one of two licences we found in this state.
After digging, we connected the dots and realised that `MD/0280003/012` and `MD/028/0003/012` were the same licence. Things have broken in WRLS because the licence number has been amended in NALD, resulting in two WRLS records.
WRLS sees `MD/0280003/012` as a deleted licence because there is no NALD record with the same licence number. The problem is that it …
=> Fix bill history caused by edited licence in NALD

.env.example, config.js, src/lib/queue-manager/start-up-jobs-service.js, test/lib/queue-manager/start-up-jobs-service.test.js
https://eaflood.atlassian.net/browse/WATER-4961
We are moving the notification logic in the service repo. As part of this code migration we need to disable the old batch notification job.
This change adds a feature toggle 'ENABLE_BATCH_NOTIFICATIONS_JOB'. This will default to true and be on by default.
=> Add enable batch notification job feature toggle

src/lib/models/scheduled-notification.js, src/lib/queue-manager/start-up-jobs-service.js
https://eaflood.atlassian.net/browse/WATER-4961
We had an assumption that using a status of 'sending' for a scheduled notification did not conflict with the existing legacy code.
This is not the case.
To avoid interacting with the legacy notification status update mechanism we have introduced a new status for scheduled notifications which is 'pending'.
This is, for all intents and purposes, the same as sending (without the legacy code attempting to update the status).
The legacy code report will be updated to allow this new 'pending' status.
We also previously added a feature toggle to turn off the whole batch notification jobs when instead we should have only toggle the notification check status.
This change update the toggle to only 'turn off' the check status logic.
=> Update notification messageStatuses to include pending

src/lib/queue-manager/start-up-jobs-service.js
A CSV file (`billing-metadata/charge-categories.csv``) containing a list of charge categories is held in the `wabs3-maintenance`` bucket.
Every 6 hours, a Bullmq job checks for changes and either inserts or updates the changes.
But it is pointless!
The file has never changed since it was first dropped. Also, because it sits in the `production` bucket, we couldn't upload a different one without a Normal RfC. This means we'd need to wait 10 business days for the changes to appear.
If the data is managed using a seed file and/or migrations, the job and all associated code would be unnecessary. We'd also be able to release the changes under a Standard RfC, which means the changes could appear as quickly as the next day.
_They are_ now managed by a seed process in …
=> Remove charge categories sync job

src/lib/queue-manager/job-registration-service.js, src/modules/billing/jobs/sync-charge-categories.js, test/modules/billing/jobs/sync-charge-categories.test.js
In [Remove charge categories sync job](https://github.com/DEFRA/water-abstraction-service/pull/2687), we thought we'd stopped the charge categories sync job from running. As we highlighted in that change, we don't tend to remove code, because we are wary of how stuff is often reused in the legacy code, and deleting code can break things.
So, instead, we tend to remove things at the 'edges'. In #2687, we stopped starting the job when the app starts. We know it has config to automatically repeat the job, so we figured not starting it would mean it couldn't repeat. How wrong we were!
Looking at the logs in `pre`, it still seems to be running. So, in this change, we'll stop the job itself from registering and remove the repeat config.
=> Actually stop charge categories sync job!

migrations/20250512143930-alter-licence-gauging-stations.js, migrations/sqls/20250512143930-alter-licence-gauging-stations-down.sql, migrations/sqls/20250512143930-alter-licence-gauging-stations-up.sql
https://eaflood.atlassian.net/browse/WATER-4999
As part of the work migrating the "Monitoring stations - Tag details page" we are now required to capture the user that created the Tag.
This PR will create a `created_by` column in the `water.licence_gauging_stations` table to enable us to capture the user ID.
=> Migration - Add `created_by` to `licence_gauging_stations`

src/modules/companies/controller.js, src/modules/companies/routes.js
https://eaflood.atlassian.net/browse/WATER-4796
We are updating the service to allow customers to upload returns quarterly (four times a year instead of just once).
The current logic is tied to displaying the link and generating the CSVs for the cycle you are currently in. To enable quarterly, we have to break that tie-in and move to a more flexible "I have a due return; give me the CSV!"
We've already made a change to allow the link always to be displayed (if you have bulk uploads enabled and have due returns) in [Always display bulk upload link on external site](https://github.com/DEFRA/water-abstraction-ui/pull/2677).
This change supports our changes to the [CSV template generation](https://github.com/DEFRA/water-abstraction-ui/pull/2679). The logic in the UI calls the …
=> Update returns for company endpoint for quarterly

src/modules/companies/routes.js
https://eaflood.atlassian.net/browse/WATER-4796
We are updating the service to allow customers to upload returns quarterly (four times a year instead of just once).
In [Update returns for company endpoint for quarterly](https://github.com/DEFRA/water-abstraction-service/pull/2692), we made a change to the API endpoint that supplies the returns data for CSV templates generated for users, to support the change [in the water-abstraction-ui](https://github.com/DEFRA/water-abstraction-ui/pull/2679).
However, during testing, we discovered that returns which show as `NOT DUE YET` in the internal UI and aren't even listed in the external UI are included in the CSV templates generated.
These need to be excluded. This change reinstates the filters we previously removed, including the 'end date' …
=> Exclude not-ended rtns from generated CSV template

src/modules/internal-search/lib/search-returns.js, test/modules/internal-search/lib/search-returns.test.js
https://eaflood.atlassian.net/browse/WATER-5085
While testing another feature of the service, it was noted that the way we create return requirements differs from NALD's approach (NALD now uses unique references, whereas we didn't!)
One of the things that highlighted this was multiple results appearing in the internal search. Users were accustomed to seeing only a single result.
There _are_ return requirements with duplicate references that we have imported from NALD, but they only apply to much older ones (pre-2008-04-01). We couldn't understand why searches for these returned no results until we found this filter.
Perhaps, knowing that WRLS was not originally importing old return submission data, it was felt there was no need to include them. But now _all_ NALD returns data has been …
=> Remove date filter on internal search for returns

migrations/20250619081908-fix-deleted-rtn-req-points.js, migrations/sqls/20250619081908-fix-deleted-rtn-req-points-down.sql, migrations/sqls/20250619081908-fix-deleted-rtn-req-points-up.sql
https://eaflood.atlassian.net/browse/WATER-5098
When we started work on moving returns management from NALD to WRLS, we found that the previous team were already importing some return version information.
- return versions (NALD_RET_VERSIONS)
- return requirements (NALD_RET_FORMATS)
- return requirement purposes (NALD_RET_FMT_PURPOSES)
However, it wasn't importing points and was missing some necessary information. So, we updated the import to include them. We then noticed that users could delete records at various levels of the 'return information' hierarchy in NALD, but this wasn't being reflected in WRLS. Hence the epic https://eaflood.atlassian.net/browse/WATER-4654.
We ensured that some limits were in place, though, to prevent data from becoming corrupted in WRLS. However, we …
=> Fix deleted return requirement points

src/modules/internal-search/lib/search-returns.js, test/modules/internal-search/lib/search-returns.test.js
https://eaflood.atlassian.net/browse/WATER-5127
Whilst testing WATER-5006, our QA team raised a concern that something was broken.
They were searching for a return reference they could see in a licence's returns, but the search was saying 'No results found'.
When we investigated, we found the legacy search has been written to exclude results from licences that have ended. It will only search for return references for 'current licences'.
We don't know what value there was in this in the first place. However, now that WRLS is responsible for managing returns, this quirk is not only confusing but could also block users from carrying out their duties.
=> Include returns for 'ended' licences in search

migrations/20250703121500-fix-deleted-licence-bill-transactions.js, migrations/sqls/20250703121500-fix-deleted-licence-bill-transactions-down.sql, migrations/sqls/20250703121500-fix-deleted-licence-bill-transactions-up.sql
https://eaflood.atlassian.net/browse/WATER-4800
A while back, we added a data fix migration: [Fix bill history caused by edited licence in NALD](http://github.com/DEFRA/water-abstraction-service/pull/2676).
This was for a licence which was amended in NALD. The original licence number was mis-typed, but rather than creating a new licence record, they amended the existing one. This led to two licence records being created in WRLS. The issue was that bills had been raised against the record with the wrong licence ref.
Pull request #2676 was to link those bill and bill licence records to the correct licence record. Then the clean job in [water-abstraction-import](https://github.com/DEFRA/water-abstraction-import) could safely remove the incorrect one.
We thought it had been, but we've since …
=> Fix billing transactions for deleted licence

migrations/20250902140511-alter-scheduled-notification.js, migrations/sqls/20250902140511-alter-scheduled-notification-down.sql, migrations/sqls/20250902140511-alter-scheduled-notification-up.sql
https://eaflood.atlassian.net/browse/WATER-5229
The legacy code always populates the `send_after` field with the current time when creating a notification, and only sometimes the `date_created` field.
The new code in [water-abstraction-system](https://github.com/DEFRA/water-abstraction-system) always populates `date_created`, and never populates `send_after`. We now consider it a redundant field.
Our issue is that our acceptance tests rely on an endpoint that returns the last notification created for a specified email address. But the disparity between how the two systems create notifications means it can no longer find the last email, which has broken some of the tests.
We need to fix it so it can!
This change runs a migration that does two things.
- updates the table so that …
=> Auto-populate scheduled_notification date_created

migrations/20250925094115-add-template-id-to-scheduled-notification.js, migrations/sqls/20250925094115-add-template-id-to-scheduled-notification-down.sql, migrations/sqls/20250925094115-add-template-id-to-scheduled-notification-up.sql
https://eaflood.atlassian.net/browse/WATER-5280
The Notify template ids where not previously stored.
This migration adds the column to record the Notify template id.
https://docs.notifications.service.gov.uk/node.html#templateid-required
=> Add migration to add a template id column to scheduled notification

migrations/20251006130947-add-overall-status-to-events.js, migrations/sqls/20251006130947-add-overall-status-to-events-down.sql, migrations/sqls/20251006130947-add-overall-status-to-events-up.sql
https://eaflood.atlassian.net/browse/WATER-5306
The `overall_status` column is populated with the overall status of related notifications. This status is calculated based on the statuses of all notifications associated with an event. It provides a quick reference to the overall status of the event without needing to check each notification individually.
The statuses are calculated as follows:
- If one notification has a status of returned, then show RETURNED
- If no notifications are returned, but one has a status of error, then show ERROR
- If no notifications are returned or errored, but one has a status of pending, then show PENDING
- If no notifications are returned, errored, or pending, then show SENT
The `status_counts` column is a JSONB object that contains counts of each …
=> Add `overall_status` and `status_counts` columns to events table
