- src/controllers/tasks/import.js
- src/lib/nald.js
{
licence,				- licence data for current version
version_end_date,		- expiry date
version_effective_date,	- date last modified
original_effective_date	- original start date
party,				- primary contact
address				- primary address
}
and updated call to document_header to include Modified and Expires keys in metadata field in the format YYYYMMDD
> added current_version object to licence

- .gitignore
- migrations/20180605103805-update-renewal-notification.js
- migrations/20180606085631-update-hof-resume-notification.js
- migrations/20180606093429-update-hof-stop-reduce-notification.js
- migrations/20180606101104-update-hof-warning-notification.js
- migrations/sqls/20180605103805-update-renewal-notification-down.sql
- migrations/sqls/20180605103805-update-renewal-notification-up.sql
- migrations/sqls/20180606085631-update-hof-resume-notification-down.sql
- migrations/sqls/20180606085631-update-hof-resume-notification-up.sql
- migrations/sqls/20180606093429-update-hof-stop-reduce-notification-down.sql
- migrations/sqls/20180606093429-update-hof-stop-reduce-notification-up.sql
- migrations/sqls/20180606101104-update-hof-warning-notification-down.sql
- migrations/sqls/20180606101104-update-hof-warning-notification-up.sql
- Render the address across multiple lines
- Adds blockquote and sibling h1 styles.
- Hide expiry date if there is not one in the renewal warning.
> bugfix/WATER-1086: Notifications updates

- package.json
- src/modules/import/lib/transform-returns-helpers.js
- src/modules/import/load.js
- test/modules/import/lib/transform-returns-helpers.js
WATER-1392
Updates the returns import to include the purpose alias in the metadata.
> Feature: Add purpose alias to return metadata

- package-lock.json
- src/modules/import/lib/transform-returns-helpers.js
- test/modules/import/lib/transform-returns-helpers.js
Updates the imported `due_date` value to be a date that is 28 days after
the `end_date` instead of the last day of the next month.
> Fix: Change due date to 28 days after end date

- package-lock.json
- src/controllers/taskRunner.js
- src/lib/logger/vendor/winston-airbrake.js
- src/modules/import/index.js
- src/modules/import/load.js
- src/modules/import/transform-crm.js
- src/modules/import/transform-permit.js
- src/modules/notify/index.js
- src/modules/returns-invitation/index.js
- src/modules/returns/lib/api-connector.js
- src/modules/returns/lib/route-helpers.js
- test/modules/returns/lib/route-helpers.js
WATER-1741
Adds extra logging around Joi validation error seen in Errbit. Hoping to
capture more information about the issue by logging some context.
This changes the winston airbrake logger in a way which pushes better
data to errbit
> Fix: Investigation of isNil validation error

- .labrc.js
- config.js
- package-lock.json
- package.json
- src/lib/licence-transformer/nald-helpers.js
- src/modules/licences/controller.js
- src/modules/licences/lib/extractConditions.js
- src/modules/licences/lib/extractPoints.js
- src/modules/licences/routes.js
- src/modules/routes.js
- test/modules/licences/controller.js
- test/modules/licences/lib/extractConditions.js
- test/modules/licences/lib/extractPoints.js
WATER-1530
Adds a new resource that takes a CRM document id, finds the internal
licence id, then finds the full licence in the permit repo.
Currently returns the raw data, but could be changes to return a better
format.
> Feat: A document licence resource

- package-lock.json
- src/lib/connectors/crm/documents.js
- src/lib/connectors/idm.js
- src/modules/licences/controller.js
- src/modules/licences/routes.js
- test/lib/connectors/crm/documents.js
- test/lib/connectors/crm/entities.js
- test/lib/connectors/idm.js
- test/modules/licences/controller.js
- test/modules/licences/routes.js
WATER-1833
Gets all the users and their roles that are associated by company with a
licence.
> Feat: Adds resource to get document users

- package-lock.json
- src/modules/communications/controller.js
- src/modules/communications/routes.js
- src/modules/routes.js
- test/modules/communications/controller.js
- test/responses/crm/documentHeader/index.js
WATER-1891
Adds a new resource at `water/{version}/communications/{id}
Combines the relevant information to provide a consumer with enough
information to show a message that has been previously sent.
> Feat: Adds a communication resource

- src/modules/import/lib/transform-returns-helpers.js
- test/modules/import/lib/transform-returns-helpers.js
WATER-1963
Add isUpload flag to return metadata to enable checking of xml return requirements
> Add isUpload flag to return metadata

- src/views/pdf-notifications/includes/custom.css
- src/views/pdf-notifications/includes/declaration-contact-us.html
- src/views/pdf-notifications/macros/cover-details.njk
- src/views/pdf-notifications/macros/cover-text.njk
- src/views/pdf-notifications/macros/header.njk
- src/views/pdf-notifications/macros/returns-title.njk
- src/views/pdf-notifications/pages/declaration.njk
- src/views/pdf-notifications/pages/guidance.njk
- src/views/pdf-notifications/pages/initial-questions.njk
> Feat: Updates the returns form with latest content

- src/views/pdf-notifications/includes/declaration-contact-us.html
- src/views/pdf-notifications/macros/cover-details.njk
- src/views/pdf-notifications/macros/cover-text.njk
- src/views/pdf-notifications/pages/declaration.njk
- src/views/pdf-notifications/pages/guidance.njk
- src/views/pdf-notifications/pages/initial-questions.njk
> Feat: Updates paper forms with latest content

- src/views/pdf-notifications/includes/declaration-contact-us.html
- src/views/pdf-notifications/pages/guidance.njk
Updates to email address and a tiny content change
WATER-1950
> Fix: Fixes to the returns form

- src/modules/import/extract.js
- src/modules/import/lib/nald-queries.js
- test/lib/nald.js
WATER-2116
Updates the import process so that the 'import' schema is not deleted
until the import has been completed in a new schema.
>  Feat: Import data into new schema when in progres

- import.js
Removes some logger config that is now incorrect after a recent change
to the logger implementation.
> Fix: Tidies up bad logger code

- config.js
- src/controllers/imported_licences.js
- src/lib/connectors/crm/documents.js
- src/lib/connectors/crm/entities.js
- src/lib/connectors/crm/kpis.js
- src/lib/connectors/crm/service-version.js
- src/lib/connectors/crm/verifications.js
- src/lib/connectors/idm.js
- src/lib/connectors/import.js
- src/lib/connectors/permit.js
- src/lib/connectors/returns.js
- src/lib/connectors/service-version-factory.js
- src/modules/river-levels/routes.js
- src/modules/routes.js
- src/modules/service-status/controller.js
- src/modules/service-status/routes.js
- src/routes/water.js
- test/lib/connectors/crm/documents.js
- test/lib/connectors/crm/entities.js
- test/lib/connectors/crm/service-version.js
- test/lib/connectors/idm.js
- test/lib/connectors/import.js
- test/lib/connectors/permit.js
- test/modules/service-status/controller.js
> Feat: Adds service status endpoint

- src/modules/users/controller.js
- test/modules/users/controller.js
Updated internal user checks to use application in config in users controller
> Update internal user check

- src/lib/connectors/crm/documents.js
- src/modules/routes.js
- src/modules/unlink-licence/controller.js
- src/modules/unlink-licence/routes.js
- test/lib/connectors/crm/documents.js
- test/modules/unlink-licence/controller.js
WATER-2237
Add CRM connector to unlink licence. Create unlink-licence route and controller.
> Feat: Unlink Licence

- src/lib/connectors/crm/documents.js
- src/modules/charge-versions/controller.js
- test/lib/connectors/crm/documents.js
> Feat: Return charge versions for expired licences

- src/modules/licences/controller.js
- src/modules/licences/routes.js
- test/modules/licences/controller.js
WATER-2215
Create route & controller function for endpoint.
> Add endpoint to get company details by documentId

- data/condition_titles.csv
WATER-2297
Adds the missing clause and sorts the CSV contents to ease comparison
with the NALD_LIC_COND_TYPES tables.
> Fix: Adds missing derogation clause

- .codeclimate.json
- src/lib/connectors/repository/BillingBatchRepository.js
- src/lib/connectors/repository/BillingInvoiceRepository.js
- src/lib/connectors/repository/index.js
- src/lib/response.js
- src/modules/billing/controller.js
- src/modules/billing/routes.js
- test/lib/connectors/repository/BillingInvoiceRepository.js
- test/lib/response.js
- test/modules/billing/controller.js
- test/modules/billing/routes.js
WATER-2385
Adds three new resources
- GET /billing/batch/:batchId
- GET /billing/batch/:batchId/invoices
- GET /billing/invoices/:invoiceId
The last resource may need to change as decisions are made as to where
the transaction values are stored and retrieved from.
> Feat: Create APIs to surface batch data

- migrations/20191203170213-performance-indexes.js
- migrations/sqls/20191203170213-performance-indexes-down.sql
- migrations/sqls/20191203170213-performance-indexes-up.sql
Queries that are called often and take a relatively long time.
> Fix: Improves performance of some queries

- src/lib/models/agreement.js
- src/lib/models/batch.js
- src/lib/models/charge-element.js
- src/lib/models/date-range.js
- src/lib/models/index.js
- src/lib/models/licence.js
- src/lib/models/open-date-range.js
- src/lib/models/region.js
- src/lib/models/transaction.js
- src/lib/models/validators.js
- test/lib/models/agreement.js
- test/lib/models/batch.js
- test/lib/models/charge-element.js
- test/lib/models/date-range.js
- test/lib/models/licence.js
- test/lib/models/open-date-range.js
- test/lib/models/region.js
- test/lib/models/transaction.js
Implements changes and additions to models to allow them to support data needed for transactions
> Adding models

- src/lib/connectors/repository/ChargeVersionRepository.js
- src/modules/billing/service/charge-version-year.js
- src/modules/billing/services/batch-service.js
- src/modules/billing/services/invoice-licences-service.js
- src/modules/billing/services/invoice-service.js
- src/modules/billing/services/transactions-service.js
- test/modules/billing/service/charge-version-year.js
- test/modules/billing/services/batch-service.js
- test/modules/billing/services/invoice-service.js
- test/modules/billing/services/transactions-service.js
Omits compensation charges when licence is for a water undertaker or batch is two-part supplementary billing.
> Compensation charges

- src/lib/models/batch.js
- src/lib/models/model.js
- src/lib/models/validators.js
- src/modules/billing/controller.js
- src/modules/billing/routes.js
- src/modules/billing/services/batch-service.js
- src/modules/billing/services/invoice-accounts-service.js
- test/lib/models/batch.js
- test/modules/billing/controller.js
- test/modules/billing/routes.js
- test/modules/billing/services/batch-service.js
WATER-2447
Part of the UI integration story, this allows the batches to be
requested by the UI.
> Feat: Adds endpoint to get batches

- src/lib/connectors/repos/billing-batches.js
- src/lib/connectors/repos/billing-transactions.js
- test/lib/connectors/repos/billing-batches.js
- test/lib/connectors/repos/billing-transactions.js
Adds test coverage for 2 new repository modules that use Bookshelf:
- billingBatches
- billingTransactions
> Add tests for billing batches repo

- .labrc.js
- src/modules/acceptance-tests/controller.js
- src/modules/acceptance-tests/lib/batches.js
- src/modules/acceptance-tests/lib/events.js
- src/modules/acceptance-tests/routes.js
- src/modules/billing/controller.js
- src/modules/billing/jobs/populate-batch-charge-versions.js
- test/modules/acceptance-tests/controller.js
- test/modules/acceptance-tests/lib/batches.js
- test/modules/billing/jobs/populate-batch-charge-versions.js
- Delete all events for acceptance test users
- Delete all batches from Anglian and Midlands regions
- Delete any new batches created by the acceptance test users
- Delete any jobs created by the acceptance test users.
> Chore: Delete acceptance test batches

- migrations/20200206102906-add-display-name-to-regions.js
- migrations/sqls/20200206102906-add-display-name-to-regions-down.sql
- migrations/sqls/20200206102906-add-display-name-to-regions-up.sql
> Feat: Adds display name to regions

- config.js
> Fix: Correct notification names in config file

- migrations/20200210133430-licence-end-dates-and-suspend-from-billing-flag.js
- migrations/sqls/20200210133430-licence-end-dates-and-suspend-from-billing-flag-down.sql
- migrations/sqls/20200210133430-licence-end-dates-and-suspend-from-billing-flag-up.sql
Add start_date, expired_date, lapsed_date, revoked_date, suspend_from_billing flag to water.licences
> water.licences migration - add dates & suspend flag

- src/lib/connectors/repository/ChargeVersionRepository.js
- src/modules/billing/jobs/populate-batch-charge-versions.js
- test/lib/connectors/repository/ChargeVersionRepository.js
- test/modules/billing/jobs/populate-batch-charge-versions.js
WATER-2478
Add handler to identify the correct charge versions for two part tariff
> Identify correct charge versions for Two Part Tariff

- migrations/20200213130850-update-batch-status-complete-to-ready.js
- migrations/sqls/20200213130850-update-batch-status-complete-to-ready-down.sql
- migrations/sqls/20200213130850-update-batch-status-complete-to-ready-up.sql
- src/lib/models/batch.js
- src/modules/billing/jobs/create-charge-complete.js
- src/modules/billing/jobs/populate-batch-charge-versions-complete.js
- src/modules/billing/jobs/prepare-transactions-complete.js
- src/modules/billing/services/job-service.js
- test/lib/models/batch.js
- test/modules/billing/jobs/create-charge-complete.js
- test/modules/billing/jobs/populate-batch-charge-versions-complete.js
- test/modules/billing/jobs/prepare-transactions-complete.js
- test/modules/billing/services/batch-service.js
- test/modules/billing/services/job-service.js
WATER-2514
Migration to update water.batch_status ENUM. 
Update batch model & relevant jobs.
> Chore: Update batch statuses

- config.js
- src/lib/connectors/charge-module/ChargeModuleRequest.js
- src/lib/connectors/s3.js
- test/lib/connectors/charge-module/ChargeModuleRequest.js
- test/lib/connectors/s3.js
Fixes an issue where requests to Cognito were not proxied
> Use proxy for cognito requests

- migrations/20200221105402-licence-agreement-id-default-guid.js
- migrations/sqls/20200221105402-licence-agreement-id-default-guid-down.sql
- migrations/sqls/20200221105402-licence-agreement-id-default-guid-up.sql
Adds missing default gen_random_uuid()  to column water.licence_agreements.licence_agreement_id
> Adds missing default gen_random_uuid() 

- src/modules/billing/services/batch-service.js
- test/modules/billing/services/batch-service.js
- Enable send batch operation to be retried
- Batch is no longer marked in error
> Handle errors approving batches

- src/modules/billing/mappers/transaction.js
- test/modules/billing/mappers/transaction.js
WATER-2581
Creates fuller transaction descriptions for two part tariff and
compensation charges
> Feat: Adds verbose transaction descriptions

- migrations/20200318175347-transactions-volume-tpt-error.js
- migrations/sqls/20200318175347-transactions-volume-tpt-error-down.sql
- migrations/sqls/20200318175347-transactions-volume-tpt-error-up.sql
Adds migration to add calculated_volume and two_part_tariff_error
columns to the billing_transactions table
> Feat: Updates fields in billing_transactions

- src/lib/connectors/bookshelf/Licence.js
- src/lib/connectors/bookshelf/LicenceAgreement.js
- src/lib/connectors/bookshelf/index.js
- src/lib/connectors/repos/index.js
- src/lib/connectors/repos/licence-agreements.js
- test/lib/connectors/repos/licence-agreements.js
Adds an additional Bookshelf repo for licenceAgreements
> Adds licenceAgreement repo

- src/lib/models/transaction.js
- src/modules/billing/controller.js
- src/modules/billing/routes.js
- src/modules/billing/services/batch-service.js
- test/modules/billing/controller.js
- test/modules/billing/routes.js
- test/modules/billing/services/batch-service.js
WATER-2600
Checks that batch is in review status.
Checks that all twoPartTariffErrors have been resolved.
Updates batch status to processing.
Saves an 'approve-review' event.
Kicks off prepare-transactions job to continue bill run process.
> Adds endpoint for updating tpt bill run to ready status.

- src/modules/import/register-subscribers.js
- test/modules/import/register-subscribers.js
task/config-nald-import-non-prod
-- changed non-production schedule to every hour for testing
> Config NALD import schedule to hourly for non-prod

- migrations/20200501124121-add-invoice-and-company-ids-to-charge-version.js
- migrations/sqls/20200501124121-add-invoice-and-company-ids-to-charge-version-down.sql
- migrations/sqls/20200501124121-add-invoice-and-company-ids-to-charge-version-up.sql
Adds the fields to the water.charge_versions table:
- company_id - stores CRM company ID of licence holder
- invoice_account_id - stores CRM invoice account ID
> Add company_id and invoice_account_id fields to charge versions

- integration-tests/billing/tests/index.js
- migrations/20200527151040-rename-bill-run-id.js
- migrations/sqls/20200527151040-rename-bill-run-id-down.sql
- migrations/sqls/20200527151040-rename-bill-run-id-up.sql
- src/lib/models/batch.js
- src/modules/billing/mappers/batch.js
- src/modules/billing/services/batch-service.js
- test/lib/models/batch.js
- test/modules/billing/services/batch-service.js
Follows recent change in CM API
> Renames batch property 'billRunId' to 'billRunNumber' 

- migrations/20200528161826-reasons-for-change.js
- migrations/sqls/20200528161826-reasons-for-change-down.sql
- migrations/sqls/20200528161826-reasons-for-change-up.sql
- src/lib/connectors/bookshelf/ChangeReason.js
- src/lib/connectors/bookshelf/index.js
- src/lib/connectors/repos/change-reasons.js
- src/lib/connectors/repos/index.js
- src/modules/change-reasons/controller.js
- src/modules/change-reasons/routes.js
- src/modules/routes.js
- test/lib/connectors/repos/change-reasons.js
- test/modules/change-reasons/controller.js
Creates a table and API to get a list of change reasons.
These reasons are selected when adding a new charge version.
> Add change reasons endpoint when creating new charge version

- src/modules/billing/services/invoice-service.js
- test/modules/billing/services/invoice-service.js
Fixes an issue with the two-part tariff remove licence flow.
The CM call generated an error because the transactions had not yet been created for the batch.  Adds logic to skip the CM call unless the batch is in the correct status.
> FIx issue where licence could not be deleted in TPT run

- package-lock.json
- package.json
- src/lib/models/contact-v2.js
- src/lib/models/invoice-account-address.js
- src/lib/models/invoice-account.js
- src/lib/models/invoice.js
- src/modules/billing/mappers/address.js
- src/modules/billing/mappers/company.js
- src/modules/billing/mappers/contact.js
- src/modules/billing/mappers/index.js
- src/modules/billing/mappers/invoice-account-address.js
- src/modules/billing/mappers/invoice-account.js
- src/modules/billing/mappers/invoice.js
- src/modules/billing/services/charge-processor-service/index.js
- src/modules/billing/services/invoice-service.js
- test/lib/models/contact-v2.js
- test/lib/models/invoice-account-address.js
- test/lib/models/invoice-account.js
- test/modules/billing/mappers/invoice.js
- test/modules/billing/services/charge-processor-service/index.js
- test/modules/billing/services/invoice-service.js
- test/modules/billing/services/supplementary-billing-service.js
- Adds InvoiceAccountAddress service model
- Adds agent company and contact to Invoice model
- Handles upstream changes in CRM invoice accounts API
- Rewrite of invoice service code for clarity and to introduce company/contact data
- Simplifies charge processor as all CRM account/address mapping handled in mapping code
> Invoice account model changes

- src/lib/connectors/repos/queries/billing-volumes.js
- src/modules/billing/mappers/transaction.js
- test/modules/billing/mappers/transaction.js
* fixes wrong case in billing volumes query
* fixes issue with undefined billing volumes in transaction mapper
> Bugfix: Fix issues with billing volumes query and mapping

- src/modules/billing/services/charge-processor-service/index.js
- test/modules/billing/services/charge-processor-service/index.js
* Uses chargeVersion.elements to get billingVolumes instead of transactions
> Bugfix: Removes duplicate chargeElements issue

- src/modules/billing/mappers/totals.js
- src/modules/billing/services/invoice-service.js
- test/modules/billing/mappers/totals.js
- test/modules/billing/services/invoice-service.js
Now that invoices are split by financial year, the previous code which summed transaction totals from the charge module across financial years has been removed.
Also tidies up tests.
> Fixes bug with totals in batch summary/invoice view

- integration-tests/billing/services/batches.js
- integration-tests/billing/services/charge-module-transactions.js
- integration-tests/billing/services/data/purpose-uses.js
- integration-tests/billing/services/purpose-uses.js
- integration-tests/billing/tests/index.js
- integration-tests/billing/tests/transaction-tests.js
- src/lib/connectors/charge-module/bill-runs.js
- test/lib/connectors/charge-module/bill-runs.js
WATER-2726
Retrieves the transaction from the charge module and compares with the
batch transaction when running a scenario.
> Feat: Transaction comparison in integration tests

- src/modules/internal-search/controller.js
WATER-2724
Catches and logs the internal search error to aid debugging of errors in
the future
> Feat: Handle internal search error

- src/lib/models/purpose.js
- src/modules/billing/services/two-part-tariff-service/prepare-charge-elements.js
- src/modules/billing/services/two-part-tariff-service/prepare-returns.js
- src/modules/billing/services/two-part-tariff-service/two-part-tariff-matching.js
- test/modules/billing/services/two-part-tariff-service/prepare-charge-elements.js
- test/modules/billing/services/two-part-tariff-service/prepare-returns.js
- test/modules/billing/services/two-part-tariff-service/sample-data/sample-matching-data-1.js
- test/modules/billing/services/two-part-tariff-service/sample-data/sample-matching-data-2.js
- test/modules/billing/services/two-part-tariff-service/sample-data/sample-matching-data-3.js
- test/modules/billing/services/two-part-tariff-service/sample-data/sample-matching-data-4.js
- test/modules/billing/services/two-part-tariff-service/sample-data/sample-matching-data-5.js
- test/modules/billing/services/two-part-tariff-service/sample-data/sample-matching-data-6.js
- test/modules/billing/services/two-part-tariff-service/testing-sample-data.js
- test/modules/billing/services/two-part-tariff-service/two-part-tariff-matching.js
- test/modules/billing/test-data/test-charge-element-data.js
This data is no longer required as it is stored in the database.
> Chore: Removes use of TPT_PURPOSE_USE_CODES

- .codeclimate.json
- src/lib/connectors/repos/licence-agreements.js
- src/lib/controller.js
- src/lib/services/licences.js
- src/lib/services/service.js
- src/modules/licences/controllers/agreements.js
- src/modules/licences/controllers/licences.js
- src/modules/licences/routes.js
- src/modules/licences/routes/agreements.js
- test/lib/connectors/repos/licence-agreements.js
- test/lib/services/licences.js
- test/modules/licences/controllers/agreements.js
- test/modules/licences/routes/agreements.js
WATER-2791
Adds two new endpoint to the water service to get:
- an agreement by it's id
- all agreements for a licence
> Feat: Add agreement and licence agreement endpoints

- src/lib/mappers/contact.js
- src/lib/mappers/invoice-account-address.js
- test/lib/mappers/invoice-account-address.js
- test/modules/billing/services/invoice-service.js
- test/modules/billing/services/volume-matching-service/data-service.js
bugfix/2795
-- invoice account address mapper updated
-- invoice service tests fixed
> Bugfix/2795 - Invoice Account Address Mapper fixed

- migrations/20200824122140-create-valid-purpose-combinations-table.js
- migrations/sqls/20200824122140-create-valid-purpose-combinations-table-down.sql
- migrations/sqls/20200824122140-create-valid-purpose-combinations-table-up.sql
- Migration script that creates a PostgreSQL table for holding valid purpose combinations.
> Added table migration scripts

- migrations/20200825110253-set-default-billrun-flag-value.js
- migrations/sqls/20200825110253-set-default-billrun-flag-value-down.sql
- migrations/sqls/20200825110253-set-default-billrun-flag-value-up.sql
This fixes 2833 in the sprint 28 release branch.
Changes are already present in the `develop` branch
> Replica branch rebased against the release branch

- package-lock.json
- package.json
- src/modules/batch-notifications/config/returns/lib/create-event.js
- test/lib/services/returns/index.js
For return batch notifications (invitations, reminders), the due date is now calculated by the helpers rather than in the water-service.
This means the special due date of 2020-10-16 is used for the winter/all year cycle ending 2020-03-31
> Use return due dates from helpers for returns batch notifications

- integration-tests/billing/services/scenarios.js
- src/modules/acceptance-tests/controller.js
- src/modules/acceptance-tests/lib/batches.js
- src/modules/acceptance-tests/lib/scenarios.js
- test/modules/acceptance-tests/controller.js
- test/modules/acceptance-tests/lib/batches.js
feat/water-2793
-- call to integration tests to create scenario from acceptance test set-up
> WATER 2793 - Create charge test data for Acceptance tests

- migrations/20200902102305-non-chargable-change-reasons.js
- migrations/sqls/20200902102305-non-chargable-change-reasons-down.sql
- migrations/sqls/20200902102305-non-chargable-change-reasons-up.sql
WATER-2740
Adds the change reason type to the change_reasons table to allow
chargable and non chargable reasons to be kept in the same table
> Feat: Change reason type

- src/lib/connectors/repos/licence-agreements.js
- src/lib/services/licences.js
- src/modules/licences/controllers/agreements.js
- src/modules/licences/routes/agreements.js
- test/lib/connectors/repos/licence-agreements.js
- test/lib/services/licences.js
- test/modules/licences/controllers/agreements.js
- test/modules/licences/routes/agreements.js
> Feat: Delete licence agreement

- test/lib/mappers/charge-version.js
Fixes an issue where a merge conflict resolution had not been successful in the charge version mapper test script.
> Fix merge conflict in charge version test script

- src/modules/invoice-accounts/controller.js
- src/modules/invoice-accounts/routes.js
- src/modules/routes.js
- test/modules/invoice-accounts/controller.js
- test/modules/invoice-accounts/routes.js
feat/water-2689
-- new route to get an invoice account by id
> New route to get invoice account by Id

- migrations/20200930155059-set-unique-constraint-on-financial-agreement-types-table.js
- migrations/sqls/20200930155059-set-unique-constraint-on-financial-agreement-types-table-down.sql
- migrations/sqls/20200930155059-set-unique-constraint-on-financial-agreement-types-table-up.sql
Supports https://github.com/DEFRA/water-abstraction-import/pull/209
> Adds UNIQUE constraint on ALTER TABLE water.financial_agreement_types

- integration-tests/billing/services/agreements.js
- integration-tests/billing/services/purpose-primary.js
- integration-tests/billing/services/purpose-secondary.js
- integration-tests/billing/services/purpose-uses.js
- src/lib/connectors/repos/queries/billing-batch-charge-versions.js
- src/lib/connectors/repos/queries/billing-invoice-licences.js
- src/lib/connectors/repos/queries/billing-invoices.js
https://eaflood.atlassian.net/browse/WATER-2875
> Removed some unnecessary spaces and SQL terminators

- src/lib/mappers/change-reason.js
- src/lib/mappers/charge-version.js
- src/lib/mappers/invoice-account.js
- src/lib/models/change-reason.js
- test/lib/mappers/change-reason.js
- test/lib/mappers/charge-version.js
- test/lib/models/change-reason.js
> Updates mappers to use new object mapper

- src/lib/roles.js
- src/modules/charge-versions/routes/charge-version-workflows.js
- test/modules/charge-versions/routes/charge-version-workflows.js
Fixes issue where role name for charge_version_workflow_reviewer didn…'t match IDM role name
> charge_version_workflow_reviewer role name fix

- config.js
- migrations/20201109125820-compound-charge-version-external-ids.js
- migrations/sqls/20201109125820-compound-charge-version-external-ids-down.sql
- migrations/sqls/20201109125820-compound-charge-version-external-ids-up.sql
- src/lib/connectors/import/index.js
- src/lib/connectors/repos/billing-batches.js
- src/lib/connectors/repos/queries/billing-batches.js
- src/lib/roles.js
- src/lib/services/charge-versions.js
- src/modules/billing/controller.js
- src/modules/billing/routes.js
- src/modules/billing/services/batch-service.js
- test/lib/connectors/import/index.js
- test/lib/connectors/repos/billing-batches.js
- test/modules/billing/controller.js
- test/modules/billing/services/batch-service.js
* Converts external_id field in water.charge_versions table to use unique varchar e.g regionCode:licenceId:versionNumber 
* Converts external_id field in water.charge_elements table to use unique varchar, e.g. regionCode:id
* Adds endpoint to truncate all billing/charge version tables and call import module to reschedule charge version import
> Adds API endpoint in non-prod to delete all billing data

- package-lock.json
- src/lib/connectors/charge-module/transactions.js
- src/lib/connectors/repos/billing-batch-charge-version-years.js
- src/lib/models/licence-version-purpose.js
- src/lib/models/transaction.js
- src/modules/billing/mappers/batch.js
- src/modules/billing/mappers/charge-module-decorators.js
- src/modules/billing/mappers/transaction.js
- src/modules/billing/services/invoice-service.js
- test/lib/connectors/charge-module/transactions.js
- test/lib/connectors/repos/billing-batch-charge-version-years.js
- test/lib/models/licence-version-purpose.js
- test/lib/models/transaction.js
- test/modules/billing/mappers/charge-module-decorators.js
- test/modules/billing/mappers/transaction.js
- test/modules/billing/services/supplementary-billing-service.js
WATER-2850
* Creates transaction CM connector
* Calls CM for additional data for each minimum charge transaction
* Updates cmToModel transaction mapper to include new details
> Feat: Updates minimum charge transactions with charge data 

- src/lib/connectors/repos/queries/events.js
- src/modules/kpi-reporting/lib/mappers.js
- test/modules/kpi-reporting/controller.js
- test/modules/kpi-reporting/lib/mappers.js
Fixes issues with KPI tests breaking each calendar year by converting mappers to pure functions
> Fixes issue with KPI tests

- config.js
- src/lib/connectors/repos/licences.js
- src/lib/connectors/repos/queries/licences.js
- src/lib/services/licences.js
- test/lib/connectors/repos/licences.js
- test/lib/services/licences.js
WATER-2911
* Removes start date from query and config
* Updates tests
> Feat: Removes start date when finding licences without charge info

- config.js
- src/lib/connectors/repos/queries/licences.js
Fixes a slow query when getting licences without charge versions
> Fix slow query fetching licences without charge versions

- migrations/20210203123742-nald-bill-header-fields.js
- migrations/sqls/20210203123742-nald-bill-header-fields-down.sql
- migrations/sqls/20210203123742-nald-bill-header-fields-up.sql
Creates necessary migrations to import NALD bill run headers
> Add additional columns/constraints for import of bill run headers 

- src/lib/connectors/repos/queries/billing-invoices.js
> Fixes constraint when upserting billing invoice

- migrations/20210205130145-billing-invoice-index.js
- migrations/sqls/20210205130145-billing-invoice-index-down.sql
- migrations/sqls/20210205130145-billing-invoice-index-up.sql
- src/lib/connectors/repos/queries/billing-invoices.js
Fixes a billing bug introduced by changes to the billing invoice table unique constraints.
> Fix issue with billing invoice constraints

- migrations/20210212115853-billing-volumes-volume-type-to-numeric.js
- migrations/sqls/20210212115853-billing-volumes-volume-type-to-numeric-down.sql
- migrations/sqls/20210212115853-billing-volumes-volume-type-to-numeric-up.sql
WATER-3017
* Changes volume data type in billing_volumes table to numeric specifying decimal places
> Bugfix: Billing volumes volume rounding error

- src/lib/services/charge-elements.js
- src/lib/to-fixed.js
- src/lib/unit-conversion.js
- test/lib/services/charge-elements.js
- test/lib/to-fixed.js
- test/lib/unit-conversion.js
> Fix unit conversion issue converting licence purpose to charge element

- config.js
- src/modules/billing/mappers/charge-module-decorators.js
- src/modules/billing/services/charge-processor-service/transactions-processor.js
- test/modules/billing/mappers/charge-module-decorators.js
- test/modules/billing/services/charge-processor-service/data.js
- test/modules/billing/services/charge-processor-service/transactions-processor.js
WATER-3000
* Updates charge module decorators to handle min charge transactions which don't have charge period dates associated with them
> Adds new minimum charge rule

- src/modules/billing/services/volume-matching-service/models/charge-element-container.js
- test/modules/billing/services/volume-matching-service/models/charge-element-container.js
> Feat: Prioritise unsupported source in tpt matching

- src/modules/charge-versions/controllers/charge-version-workflow.js
bugfix/water3001-patch-workflow-if-exist
-- charge version workflow controller updated
> bugfix -- water-3001 patch charge version workflow if it exists

- integration-tests/billing/fixtures/test-licences.yaml
- integration-tests/billing/fixtures/test-returns.yaml
feat/water-3020
-- additional return and return requirements added to yaml files
> Water - 3020 - external returns regression tests

- migrations/20210322093951-anti-frost-tpt-flag.js
- migrations/sqls/20210322093951-anti-frost-tpt-flag-down.sql
- migrations/sqls/20210322093951-anti-frost-tpt-flag-up.sql
> Set is_two_part_tariff to true for 390 - anti-frost storage

- src/lib/mappers/invoice.js
- src/lib/services/invoice-service.js
- src/modules/invoice-accounts/controller.js
- src/modules/invoice-accounts/routes.js
- test/modules/invoice-accounts/controller.js
* Fixes pagination on invoice account invoices endpoint
* Renames `billingBatch` to `batch` in API response
> Fixes pagination not implemented on invoice account invoices endpoint

- integration-tests/billing/fixtures/2PT1.yaml
- integration-tests/billing/fixtures/2PT2.yaml
- integration-tests/billing/fixtures/AB1.yaml
- integration-tests/billing/fixtures/AB2.yaml
- integration-tests/billing/fixtures/SB1-1.yaml
- integration-tests/billing/fixtures/SB1-2.yaml
- integration-tests/billing/fixtures/SB2-1.yaml
- integration-tests/billing/fixtures/SB2-2.yaml
- integration-tests/billing/fixtures/test-charge-versions.yaml
bugfix/charge-element-test-data-fix
-- factorsOverridden field added to yaml fixtures for charge elements
> Bugfix - factors overridden field added to charge elements test data

- .env.example
- config.js
- src/lib/models/return.js
- test/lib/models/return.js
`WATER-3159`
Allow returns grace period to be configured with .env variable.
> Allow TPT returns grace period to be configured with env var

- src/lib/notify/index.js
- src/modules/notify/controller.js
- src/modules/notify/routes.js
- test/lib/notify/index.js
- test/modules/notify/controller.js
bugfix/water-3041
-- new route to proxy sending notify emails via the water service
> Water-3041 - New route to proxy notify calls via the water service

- src/lib/models/charge-element.js
- test/lib/models/charge-element.js
`WATER-3160`
Modifies ChargeElement constructor so that `isSection127AgreementEnabled` defaults to true
> WATER-3160 - ChargeElement isSection127AgreementEnabled flag default to true

- src/lib/connectors/repos/queries/billing-batch-charge-version-years.js
- src/lib/connectors/repos/queries/billing-invoices.js
- src/lib/services/invoice-service.js
- src/modules/billing/services/batch-service.js
- test/lib/services/invoice-service.js
- test/modules/billing/services/batch-service.js
feat/water-3105
-- delete rebilling invoice licences and transactions added to delete process
-- delete by originalInvoiceId removed from invoice service
> Water 3105 - delete re-billed invoices

- migrations/20210608110410-financial-agreement-unique-constraint.js
- migrations/sqls/20210608110410-financial-agreement-unique-constraint-down.sql
- migrations/sqls/20210608110410-financial-agreement-unique-constraint-up.sql
`WATER-3238`
Migration to fix missing constraint on financial agreement code
> Fix unique constraint on financial agreement code

- migrations/20210608110410-financial-agreement-unique-constraint.js
- migrations/sqls/20210608110410-financial-agreement-unique-constraint-down.sql
- migrations/sqls/20210608110410-financial-agreement-unique-constraint-up.sql
WATER-3238
Migration to fix missing constraint on financial agreement code
> Fix unique constraint on financial agreement types table

- integration-tests/billing/fixtures/2PT1.yaml
bugfix/yaml-test-data-fix
-- 2PT1 financial agreement unique constraint corrected
> 2PT1 test data fix

- migrations/20210611103959-missing-licence-gauging-stations-field.js
- migrations/20210616114846-make-waa-restriction-date-nullable.js
- migrations/sqls/20210611103959-missing-licence-gauging-stations-field-down.sql
- migrations/sqls/20210611103959-missing-licence-gauging-stations-field-up.sql
- migrations/sqls/20210616114846-make-waa-restriction-date-nullable-down.sql
- migrations/sqls/20210616114846-make-waa-restriction-date-nullable-up.sql
- src/lib/connectors/bookshelf/LicenceGaugingStations.js
- src/lib/connectors/bookshelf/index.js
- src/lib/connectors/repos/licence-gauging-stations.js
- src/lib/mappers/licence-version-purpose-conditions.js
- src/lib/models/licence-version-purpose-condition.js
- src/lib/roles.js
- src/lib/services/gauging-station-service.js
- src/lib/services/licence-gauging-stations-service.js
- src/modules/gauging-stations/controller.js
- src/modules/gauging-stations/helpers.js
- src/modules/gauging-stations/routes/index.js
- test/lib/connectors/bookshelf/LicenceGaugingStations.js
- test/lib/connectors/repos/licence-gauging-stations.js
- test/lib/services/gauging-stations.js
- test/modules/gauging-stations/controller.js
Original ticket: https://eaflood.atlassian.net/browse/WATER-3114
Goes along with: https://github.com/DEFRA/water-abstraction-tactical-idm/pull/737
> Adds new endpoint for posting a new linkage

- src/lib/connectors/repos/licence-gauging-stations.js
- src/lib/roles.js
- src/lib/services/licence-gauging-stations-service.js
- src/modules/gauging-stations/controller.js
- src/modules/gauging-stations/routes/index.js
- test/lib/connectors/repos/licence-gauging-stations.js
- test/modules/gauging-stations/controller.js
Original ticket: https://eaflood.atlassian.net/browse/WATER-3116
> Adds an endpoint for removing licenceGaugingStation records

- integration-tests/billing/fixtures/test-licences.yaml
- integration-tests/billing/fixtures/test-returns.yaml
feat/water-3232
-- void return added to returns data
>  Test data for water-3232

- integration-tests/billing/fixtures/test-returns.yaml
- integration-tests/billing/services/fixture-loader/FixtureLoader.js
- integration-tests/billing/services/fixture-loader/SetLoader.js
- integration-tests/billing/services/returns-loader.js
feat/water-3232
-- fixtures loader extended to receive custom reference data
-- returns loader now calculates future return due dates
-- set loader adds refs to existing fixtures loader instance
> WATER-3232 - Fixtures loader extended and due and completed returns data added

- src/lib/connectors/repos/billing-batches.js
- src/modules/billing/services/batch-service.js
- test/lib/connectors/repos/billing-batches.js
- test/modules/billing/services/batch-service.js
bugfix/water-3278
--get 2pt batches in connectors now includes supplementary batches because you can have 2PT invoices in supplementary batches.
> BUGFIX - WATER 3278 - 2PT duplicate charges

- migrations/20210804123339-flip-credit-note-signs.js
- migrations/sqls/20210804123339-flip-credit-note-signs-down.sql
- migrations/sqls/20210804123339-flip-credit-note-signs-up.sql
- src/modules/billing/mappers/transaction.js
- src/modules/billing/services/cm-refresh-service.js
- test/modules/billing/mappers/transaction.js
Original ticket: https://eaflood.atlassian.net/browse/WATER-3285
> Flips CM credit notes to being negative, to bring CM inline with NALD

- integration-tests/billing/fixtures/sets.json
- integration-tests/billing/fixtures/test-gauging-stations.yaml
- integration-tests/billing/services/gauging-stations.js
- integration-tests/billing/services/queries/gauging-stations.js
- integration-tests/billing/services/tear-down.js
- migrations/20210809074146-add-test-cols-on-gs.js
- migrations/sqls/20210809074146-add-test-cols-on-gs-down.sql
- migrations/sqls/20210809074146-add-test-cols-on-gs-up.sql
> Adds a test gauging station + teardown routines

- src/lib/mappers/charge-element.js
Original ticket: https://eaflood.atlassian.net/browse/WATER-3300
Goes along with: https://github.com/DEFRA/water-abstraction-ui/pull/1907
> WATER-3300

- src/lib/mappers/invoice.js
- src/lib/models/invoice.js
- src/modules/billing/jobs/rebilling.js
- test/lib/mappers/invoice.js
- test/lib/models/invoice.js
- test/modules/billing/jobs/rebilling.js
Feat/water 3104 rebilling
-- batch id added to the invoice model and mapper. 
-- this is needed to create the necessary links in the UI to flick between the original, rebill and reversal invoices for rebilling.
> Water - 3104 rebilling - Batch Id added to Invoice model to match DB

- src/modules/billing/jobs/rebilling.js
- test/modules/billing/jobs/rebilling.js
bugfix/water-3245
-- rebilling job update process of original invoice fixed
> Bugfix - water -3245 - rebilling

- src/modules/billing/mappers/transaction.js
- test/modules/billing/mappers/transaction.js
feat/water-3293
-- min charge flag set to true for all transactions sent to the CM
> WATER - 3293 - Minimum Charge flag

- src/modules/billing/mappers/transaction.js
- test/modules/billing/mappers/transaction.js
feat/water-3293
-- only 2PT transactions are not subject to minimum charge
> WATER - 3293 - set min charge to false for 2PT transactions

- src/lib/licence-transformer/nald-transformer.js
- test/lib/licence-transformer/nald-transformer.js
Original ticket: https://eaflood.atlassian.net/browse/WATER-3368
Service PR: https://github.com/DEFRA/water-abstraction-service/pull/1549
UI PR: https://github.com/DEFRA/water-abstraction-ui/pull/1965
CRM PR: https://github.com/DEFRA/water-abstraction-tactical-crm/pull/871
> Make expired licences searchable again

- src/modules/billing/services/supplementary-billing-service/supplementary-processor.js
- test/modules/billing/services/supplementary-billing-service/supplementary-processor.js
Reverts DEFRA/water-abstraction-service#1559
> Revert "Bugfix/water 3370"

- src/lib/models/contact-v2.js
- test/lib/models/contact-v2.js
See: https://eaflood.atlassian.net/browse/WATER-3372
This is a requirement for PR: https://github.com/DEFRA/water-abstraction-ui/pull/1968
> WATER-3372: Generate the fullName for a companyContact in the service

- src/lib/connectors/charge-module/bill-runs.js
- src/modules/billing/services/batch-service.js
- test/lib/connectors/charge-module/bill-runs.js
- test/modules/billing/services/batch-service.js
Ticket: https://eaflood.atlassian.net/browse/WATER-3369
> Updates CM connector to use new v3 endpoint for creating batches

- src/lib/connectors/crm-v2/companies.js
- src/lib/services/company-contacts.js
- src/modules/companies/controller.js
- src/modules/companies/routes.js
- test/lib/services/crm-service.js
See: https://eaflood.atlassian.net/browse/WATER-3349
Please note this PR is a dependant upon PR:
https://github.com/DEFRA/water-abstraction-tactical-crm/pull/873
And is a prerequisite for PR:
https://github.com/DEFRA/water-abstraction-ui/pull/1970
> WATER-3349: Delete a company contact

- src/modules/contacts/routes.js
See: https://eaflood.atlassian.net/browse/WATER-3379
Please note this PR depends on:
https://github.com/DEFRA/water-abstraction-tactical-crm/pull/875
And is a prerequisite for:
https://github.com/DEFRA/water-abstraction-ui/pull/1975
> WATER-3379: Update a contact, add a new charge version it throws error

- integration-tests/billing/fixtures/2PT1.yaml
- integration-tests/billing/services/bookshelf-loader.js
See https://eaflood.atlassian.net/browse/WATER-3371
This is a prerequisite for PR: https://github.com/DEFRA/water-abstraction-ui/pull/1978
> WATER-3371: Recalculating charges with no change to charge versions

- integration-tests/billing/fixtures/historic-billing-2PT1.yaml
- integration-tests/billing/fixtures/historic-billing-2nd-part-trans.yaml
- integration-tests/billing/fixtures/historic-billing-annual-trans.yaml
- integration-tests/billing/fixtures/historic-billing-batch.yaml
- integration-tests/billing/fixtures/sets.json
- integration-tests/billing/services/fixture-loader/FixtureLoader.js
- integration-tests/billing/services/fixture-loader/SetLoader.js
- integration-tests/billing/services/fixture-loader/adapters/BookshelfAdapter.js
- integration-tests/billing/services/lib/financial-date-range.js
- src/modules/acceptance-tests/controller.js
See: https://eaflood.atlassian.net/browse/WATER-3390
Please note this is a prerequisite for PR: https://github.com/DEFRA/water-abstraction-ui/pull/1991
> WATER 3390: Recalculating charges with no change to charge versions for the historic Data

- src/lib/connectors/repos/licences.js
- src/lib/connectors/repos/queries/licences.js
- src/lib/services/licences.js
- src/modules/billing/jobs/prepare-transactions.js
- src/modules/billing/services/batch-service.js
- src/modules/billing/services/licences-service.js
- test/lib/connectors/repos/licences.js
- test/lib/services/licences.js
- test/modules/billing/services/batch-service.js
See: https://eaflood.atlassian.net/browse/WATER-3411
> WATER 3411: Licences remain marked for Supp Billing even after progressing through Bill run

- integration-tests/billing/fixtures/historic-billing-2PT1.yaml
See https://eaflood.atlassian.net/browse/WATER-3390 for the differing regression test scenarios.
Please note this PR is a dependency of: https://github.com/DEFRA/water-abstraction-ui/pull/2000
> WATER-3390: Recalculate charges with changes

- src/modules/billing/services/batch-service.js
- src/modules/billing/services/licences-service.js
feat/water-3411
-- remove supplementary billing flag by region
and batch timestamp for empty batches
> WATER 3411 - remove suppl. billing flag for empty batches

- src/modules/billing/services/batch-service.js
- test/modules/billing/services/batch-service.js
Licence stuck in supplementary bill run are now considered for next supplementary bill run.
See: https://eaflood.atlassian.net/browse/WATER-3411?focusedCommentId=367780
> WATER-3411: Licence stuck in supplementary bill run

- migrations/20211216190900-add-supported-sources-order-and-region.js
- migrations/sqls/20211216190900-add-supported-sources-order-and-region-down.sql
- migrations/sqls/20211216190900-add-supported-sources-order-and-region-up.sql
- src/lib/mappers/supported-source.js
- src/lib/models/supported-source.js
- src/modules/billing/jobs/sync-supported-sources.js
- test/lib/mappers/supported-source.js
- test/modules/billing/jobs/sync-supported-sources.js
See: https://eaflood.atlassian.net/browse/WATER-3422
> WATER-3422: Add order and region to supported sources

- migrations/20220106105612-change-licence-reprocess-to-yes.js
- migrations/sqls/20220106105612-change-licence-reprocess-to-yes-down.sql
- migrations/sqls/20220106105612-change-licence-reprocess-to-yes-up.sql
- src/lib/models/constants.js
- src/lib/services/licences.js
- src/modules/billing/services/batch-service.js
- test/lib/services/licences.js
- test/modules/billing/jobs/lib/batch-job.js
- test/modules/billing/services/batch-service.js
See: https://eaflood.atlassian.net/browse/WATER-3411?focusedCommentId=368336
> WATER-3411: Fix licences stuck in marked for reprocess

- package-lock.json
- src/lib/connectors/repos/queries/events.js
- src/lib/services/events.js
- src/lib/services/scheduled-notifications.js
- src/modules/notifications/controller.js
- src/modules/notifications/routes.js
- test/lib/services/event.js
- test/modules/notifications/controller.js
Service PR: https://github.com/DEFRA/water-abstraction-service/pull/1604
UI PR: https://github.com/DEFRA/water-abstraction-ui/pull/2011
Original ticket: https://eaflood.atlassian.net/browse/WATER-3380
> Feat/water 3380/notification filtering

- src/lib/connectors/repos/queries/charge-versions.js
Prevent bill run for sroc before set date WATER-3417
> Updated charge-versions.js

- src/lib/mappers/charge-element.js
feat/water-3401
-- charge element mapper fixed to map additional charges and adjustments
> WATER 3401 - charge element mapper updated

- src/modules/billing/jobs/refresh-totals.js
Reverts DEFRA/water-abstraction-service#1615
> Revert "Update refresh-totals.js"

- integration-tests/billing/fixtures/test-bulk-returns.yaml
- integration-tests/billing/services/returns-loader.js
Reverts DEFRA/water-abstraction-service#1626
> Revert "Water-3529 fix cypress test bulk upload"

- src/modules/billing/jobs/refresh-totals.js
- test/modules/billing/jobs/refresh-totals.js
Relates to https://eaflood.atlassian.net/browse/WATER-3553
> Checks if 2PT batch is empty and marks it accordingly

- migrations/20220224164015-create-note-table.js
- migrations/sqls/20220224164015-create-note-table-down.sql
- migrations/sqls/20220224164015-create-note-table-up.sql
- src/lib/connectors/bookshelf/ChargeVersion.js
- src/lib/connectors/bookshelf/Note.js
- src/lib/connectors/bookshelf/index.js
- src/lib/connectors/repos/charge-versions.js
- src/lib/connectors/repos/notes.js
- src/lib/mappers/charge-version.js
- src/lib/mappers/note.js
- src/lib/models/charge-version.js
- src/lib/models/note.js
- src/lib/services/charge-versions.js
- test/lib/connectors/repos/charge-version.js
- test/lib/services/charge-versions.js
See: https://eaflood.atlassian.net/browse/WATER-3415
This is a prerequisite for: https://github.com/DEFRA/water-abstraction-ui/pull/2048
> WATER-3415: Addition of Notes to Charge Information review page

- migrations/20220228143747-remove-billing-charge-categories-data.js
- migrations/sqls/20220228143747-remove-billing-charge-categories-data-down.sql
- migrations/sqls/20220228143747-remove-billing-charge-categories-data-up.sql
Migration script for water-3423 to update prod
> Migration script for water-3423

- config.js
- migrations/20220303154108-add-waa-email-to-scheduled-notification-cats.js
- migrations/sqls/20220303154108-add-waa-email-to-scheduled-notification-cats-down.sql
- migrations/sqls/20220303154108-add-waa-email-to-scheduled-notification-cats-up.sql
- src/lib/connectors/crm-v2/companies.js
- src/modules/batch-notifications/config/water-abstraction-alerts/lib/get-recipients.js
- test/lib/connectors/crm-v2/companies.js
- test/modules/batch-notifications/config/water-abstraction-alerts/lib/get-recipients.js
UI: https://github.com/DEFRA/water-abstraction-ui/pull/2054
CRM: https://github.com/DEFRA/water-abstraction-tactical-crm/pull/879
Service: https://github.com/DEFRA/water-abstraction-service/pull/1642
Originating tickets: 
- https://eaflood.atlassian.net/browse/WATER-3383
- https://eaflood.atlassian.net/browse/WATER-3540
> Adds WAA Email support

- config.js
- index.js
- src/lib/connectors/repos/purpose-uses.js
- src/modules/charge-versions/controllers/charge-versions.js
- src/modules/charge-versions/jobs/map-to-json.js
- src/modules/charge-versions/jobs/start-upload.js
- src/modules/charge-versions/jobs/update-charge-information.js
- src/modules/charge-versions/lib/charge-information-upload.js
- src/modules/charge-versions/lib/csv-adapter/csv-parser.js
- src/modules/charge-versions/lib/csv-adapter/index.js
- src/modules/charge-versions/lib/csv-adapter/mapper.js
- src/modules/charge-versions/lib/csv-adapter/validator.js
- src/modules/charge-versions/lib/error-event.js
- src/modules/charge-versions/lib/event-factory.js
- src/modules/charge-versions/register-subscribers.js
- src/modules/charge-versions/routes/charge-versions.js
- test/modules/charge-versions/jobs/map-to-json.js
- test/modules/charge-versions/jobs/start-upload.js
- test/modules/charge-versions/lib/csv-adapter/mapper.js
- test/modules/charge-versions/lib/csv-adapter/validator.js
- test/modules/charge-versions/routes.js
See: https://eaflood.atlassian.net/browse/WATER-3495?focusedCommentId=388905
Note that this is required for: 
https://github.com/DEFRA/water-abstraction-ui/pull/2055
> WATER-3495: Upload Charge Information

- src/modules/charge-versions/lib/charge-information-upload.js
- src/modules/charge-versions/lib/csv-adapter/validator.js
- test/modules/charge-versions/lib/csv-adapter/validator.js
See also: https://github.com/DEFRA/water-abstraction-ui/pull/2076
> WATER-3495: - fix upload validation

- src/modules/charge-versions-upload/jobs/update-charge-information-save.js
- src/modules/charge-versions-upload/jobs/update-charge-information-start.js
- src/modules/charge-versions-upload/jobs/update-charge-information-to-json.js
- src/modules/charge-versions-upload/lib/helpers.js
- src/modules/charge-versions-upload/lib/mapper/chargeVersionMapper.js
- src/modules/charge-versions-upload/lib/mapper/index.js
- src/modules/charge-versions-upload/lib/validator/index.js
- test/modules/charge-versions-upload/lib/mapper/chargeVersionMapper.js
- test/modules/charge-versions-upload/lib/validator/validator.js
Additional optimization for: https://eaflood.atlassian.net/browse/WATER-3551
> WATER-3551: Optimize upload

- src/lib/connectors/repos/notes.js
- src/lib/mappers/index.js
- src/lib/services/charge-versions.js
- src/lib/services/notes-service.js
- test/lib/connectors/repos/notes.js
- test/lib/services/charge-versions.js
- test/lib/services/notes-service.js
See: https://eaflood.atlassian.net/browse/WATER-3526
This also requires: https://github.com/DEFRA/water-abstraction-ui/pull/2098
> WATER-3526: Copy note information

- src/modules/charge-versions-upload/jobs/update-charge-information-save.js
- src/modules/charge-versions-upload/jobs/update-charge-information-start.js
- src/modules/charge-versions-upload/jobs/update-charge-information-to-json.js
- src/modules/charge-versions-upload/lib/helpers.js
- src/modules/charge-versions-upload/lib/mapper/chargePurposesMapper.js
- src/modules/charge-versions-upload/lib/mapper/index.js
- src/modules/charge-versions-upload/lib/validator/index.js
- test/modules/charge-versions-upload/lib/mapper/additionalChargesMapper.js
See: https://eaflood.atlassian.net/browse/WATER-3551
> WATER-3551: Improve performance

- config.js
- src/modules/returns/controllers/csv-upload.js
- src/modules/returns/lib/jobs/persist-returns.js
- src/modules/returns/lib/jobs/start-upload.js
- src/modules/returns/lib/jobs/validate-returns.js
- src/modules/returns/lib/returns-upload-validator.js
- src/modules/returns/lib/upload-preview-mapper.js
- src/modules/returns/routes/csv-upload.js
- test/modules/returns/controllers/csv-upload.js
-- validation repetition removed
-- json file now uploaded to S3 saves validation values
-- tests fixed
-- bull mq job lock increased on all return upload jobs
> Bugfix - bulk returns upload

- package.json
- src/lib/mappers/company.js
- src/lib/services/invoice-service.js
- src/modules/billing/controllers/batches.js
- src/modules/billing/mappers/api/invoice.js
- test/modules/billing/mappers/api/invoice.js
WATER 3644
Theres are multiple names associated with companies this work will introduce a new flow to determine what name to show (just an if else in the UI )
```
if invoice.faoContact 
elif invoice.billingContact.agentCompanyName 
elif invoice.billingContact.roleContact.licenceHolder
elif invoice.billingContact.roleContact.billing
else invoice.name
```
> fix: billing contact account name

- package.json
Addresses: https://github.com/DEFRA/water-abstraction-team/issues/11
> chore: remove nodemon

- package-lock.json
- package.json
DEFRA/water-abstraction-team#31
Using [sroc-charging-module-api](https://github.com/DEFRA/sroc-charging-module-api/blob/main/package.json) tidy up the `package.json` to ensure
- it's consistent with the other repos
- it's correct
- any unused scripts are removed
> Tidy up `package.json`

- src/modules/charge-versions-upload/lib/validator/index.js
We noticed that the CSV upload function iterates over arrays by using a `while` loop and `shift()` to get each element to be handled. In our testing we found that replacing these with `for...of` loops was more performant; a ~700 line file previously took 6 mins to import locally with the process using ~1GB memory, whereas changing to a `for...of` loop took 3.5 mins to import using ~150MB memory.
> Refactor CSV upload for performance

- src/lib/services/charge-versions.js
- src/modules/charge-versions-upload/jobs/update-charge-information-save.js
As with other parts of the charge versions upload code, we switch out a `do...while` loop with `shift()` for ` regular `for...of` loop to help optimise it.
> Refactor `update-charge-information-save` loop

- index-background.js
- index.js
- integration-tests/billing/services/scenarios.js
- test/controllers/notify.test.js
- test/controllers/sessions.test.js
- test/routes/water.test.js
Whilst working on [Set up background tasks module](https://github.com/DEFRA/water-abstraction-service/pull/1766) we found ourselves making some changes to the root index.js files.
Minor things around organising the imports, changes to the messaging during shutdown, and applying strict mode.
To help avoid the change losing focus and to reduce its size, we're moving those changes to this one.
> Minor housekeeping changes to root index files

- integration-tests/billing/services/crm-v1-loader.js
- integration-tests/billing/services/returns-loader.js
- integration-tests/billing/tests/annual/AB1.js
- integration-tests/billing/tests/annual/AB2.js
- integration-tests/billing/tests/supplementary/SB1.js
- integration-tests/billing/tests/supplementary/SB2.js
- integration-tests/billing/tests/two-part-tarrif/2PT1.js
- integration-tests/billing/tests/two-part-tarrif/2PT2.js
- src/lib/mappers/company.js
- src/lib/mappers/invoice.js
- src/lib/mappers/notify.js
- src/lib/models/contact-v2.js
- src/lib/models/invoice-account.js
- src/lib/object-mapper.js
- src/lib/services/returns/index.js
- src/modules/batch-notifications/config/returns/lib/create-event.js
- src/modules/billing/jobs/lib/update-invoices-worker.js
- src/modules/billing/lib/charge-period.js
- src/modules/gauging-stations/helpers.js
- src/modules/returns/lib/upload-preview-mapper.js
- test/lib/mappers/company.test.js
- test/lib/mappers/invoice-account-address.test.js
- test/modules/billing/test-data/test-billing-data.js
- test/modules/charge-categories/routes.test.js
- test/modules/returns/lib/returns-upload-validator.test.js
Lodash is used a lot in our codebase. Although we are not totally removing this module, some of the functions in the code using lodash are unnecessary. Here we are removing the unnecessary ones are replacing it with vanilla js.
This PR is focusing on the 'Omit' and 'Last' function.
> Removing 'Omit' and 'Last' Lodash Functions

- integration-tests/billing/services/fixture-loader/adapters/BookshelfAdapter.js
- src/lib/connectors/repos/lib/envelope.js
- src/lib/mappers/charge-module.js
- src/lib/mappers/notify.js
- src/lib/models/address.js
- src/lib/models/contact.js
- src/lib/models/model.js
- src/modules/billing/jobs/sync-charge-categories.js
- src/modules/billing/services/supplementary-billing-service/data-service.js
- src/modules/billing/services/supplementary-billing-service/supplementary-processor.js
- src/modules/communications/controller.js
- src/modules/licences/controllers/agreements.js
- src/modules/notifications/controller.js
- src/modules/returns-notifications/lib/message-helpers.js
- src/modules/returns/lib/returns-upload-validator.js
- test/lib/models/model.test.js
- test/modules/billing/services/supplementary-billing-service/data-service.test.js
- test/modules/notifications/controller.test.js
Lodash is used a lot in our codebase. Although we are not totally removing this module, some of the functions in the code using lodash are unnecessary. Here we are removing the unnecessary ones are replacing it with vanilla js.
This PR is focusing on the 'pick' function
> Removing Lodash 'Pick' function

- src/lib/connectors/charge-module/lib/got-cm.js
This adds logging to `src/lib/connectors/charge-module/lib/got-cm.js` to allow us to see the detail the [sroc-charging-module-api](https://github.com/DEFRA/sroc-charging-module-api) returns in its responses.
> Add error logging to got-cm

- scripts/returns/test-return.js
- src/lib/mappers/event.js
- src/lib/mappers/invoice.js
- src/lib/models/billing-volume.js
- src/lib/models/charge-element.js
- src/lib/models/charge-purpose.js
- src/lib/models/date-range.js
- src/lib/models/factory/crm-contact-list.js
- src/lib/models/invoice.js
- src/lib/models/notification-event.js
- src/lib/models/return-line.js
- src/lib/models/transaction.js
- src/lib/object-mapper.js
- src/lib/to-fixed.js
- src/lib/unit-conversion.js
- src/modules/billing/jobs/lib/update-invoices-worker.js
- src/modules/billing/mappers/transaction.js
- test/modules/addresses/routes.test.js
- test/modules/billing/services/cm-refresh-service.test.js
- test/modules/billing/services/invoice-licences-service.test.js
- test/modules/charge-versions-upload/routes.test.js
- test/modules/contacts/routes.test.js
- test/modules/licences/controllers/documents.test.js
- test/modules/returns/lib/returns-upload-validator.test.js
- test/modules/returns/routes.test.js
- test/responses/permits/licence/index.js
- test/test-helpers.js
Lodash is used a lot in our codebase. Although we are not totally removing this module, some of the functions in the code using lodash are unnecessary. Here we are removing the unnecessary ones are replacing it with vanilla js.
This PR is focusing on the 'isNull' and 'cloneDeep' functions
> Remove 'isNull' and 'cloneDeep' lodash function

- src/lib/connectors/ea-address-facade.js
- src/lib/validate.js
- src/modules/batch-notifications/lib/event-helpers.js
- src/modules/charge-versions-upload/jobs/update-charge-information-save.js
- src/modules/charge-versions-upload/lib/error-event.js
- src/modules/charge-versions-upload/lib/helpers.js
- src/modules/charge-versions-upload/lib/mapper/index.js
- src/modules/companies/lib/returns.js
- src/modules/internal-search/lib/build-response.js
- src/modules/returns/controllers/csv-upload.js
- src/modules/returns/lib/jobs/error-event.js
- src/modules/returns/lib/jobs/persist-returns.js
- src/modules/returns/lib/jobs/validate-returns.js
- test/lib/mappers/charge-module.test.js
- test/modules/billing/services/invoice-licences-service.test.js
- test/modules/companies/lib/returns.test.js
- test/modules/gauging-stations/jobs/sync-gauging-stations.test.js
- test/modules/internal-search/lib/search-users.test.js
- test/modules/returns/lib/returns-upload-validator.test.js
Lodash is used a lot in our codebase. Although we are not totally removing this module, some of the functions in the code using lodash are unnecessary. Here we are removing the unnecessary ones are replacing it with vanilla js. This PR is focusing on the 'set' function
> Remove 'set' lodash function

- src/lib/connectors/crm-v2/invoice-accounts.js
- src/lib/connectors/crm/documents.js
- src/lib/connectors/returns.js
- src/lib/models/invoice.js
- src/lib/services/returns/index.js
- src/modules/batch-notifications/config/returns/lib/return-notification-recipients.js
- src/modules/billing/controllers/batches.js
- src/modules/billing/services/charge-processor-service/lib/agreements.js
- src/modules/billing/services/charge-processor-service/transactions-processor.js
- src/modules/billing/services/charge-version-service/index.js
- src/modules/billing/services/supplementary-billing-service/supplementary-processor.js
- src/modules/billing/services/transactions-service.js
- src/modules/billing/services/volume-matching-service/models/charge-element-group.js
- src/modules/returns/lib/csv-adapter/date-parser.js
- src/modules/returns/lib/returns-upload-validator.js
- src/modules/returns/lib/xml-adapter/mapper.js
- test/modules/billing/services/volume-matching-service/models/charge-element-group.test.js
Lodash is used a lot in our codebase. Although we are not totally removing this module, some of the functions in the code using lodash are unnecessary. Here we are removing the unnecessary ones are replacing it with vanilla js. This PR focuses on removing 'flatMap'.
> Remove 'flatMap' Lodash function

- src/modules/billing/services/batch-service.js
- test/modules/billing/services/batch-service.test.js
https://eaflood.atlassian.net/browse/WATER-4040
Removing the flag from a licence for a SRoC bill run puts the Pre-SRoC supplementary flag on the licence.
> Removing SRoC flag sets Pre-SRoC supplementary flag

- src/modules/notify/index.js
https://eaflood.atlassian.net/browse/WATER-4236
We recently made changes to try and stop multiple requests for the same task at the same time leading to duplicate jobs being added to the queue, for example, sending duplicate invites because someone managed to double-click the button in the UI.
To do that we came up with a solution whereby the UI generates a job ID for that user and session and then sends it in the payload. This in turn would be passed through to `enqueue()` in the second arg `options` as `jobId`.
Only in the land of notifications `options` isn't actually something to config things, but is the data itself handily named `n`!
So, we didn't see that in `src/modules/notify` and `src/modules/returns-notifications` (and possibly other places we don't know about) the second arg …
> Fix email sending for non-notifications

- src/lib/connectors/system/supplementary-billing.js
https://github.com/DEFRA/water-abstraction-system/pull/1239
During recent refactoring for the Supplementary billing flag process, the route was updated to better reflect the naming conventions in the repo. This PR is to update the routes when the service is called.
> Update Supplementary Billing flag route
